### ISSUE TITLE
Validation on disabled fields is not working

### ISSUE THREAD

**Issue by Kayparker** [1000hz/bootstrap-validator#101]
I have a situation where I have a disabled field and the value for it comes from the bootstrap modal search. I store the ID of the element selected from the search into the hidden field and the text field in the disabled TEXTBOX which is configured to be required.

The style for this text box do not change to red neither it stop form submission.

**Comment by 1000hz** [comment]
Use `readonly` instead of `disabled`

**Comment by 1000hz** [comment]
Actually, it turns out browsers consider readonly fields valid so that won't work.

**Comment by 1000hz** [comment]
You will have to add a custom validator to check if the field is required, then you can use the readonly attribute and have it work.

So something like this:
```js
$('#myForm').validator({
  custom: {
    required: function ($el) { return !!$.trim($el.val()) }
  },
  errors: {
    required: 'Please fill out this field.'
  }
})
```

```html
<div class="form-group">
  <input type="text" data-required="true" readonly>
  <div class="help-block with-errors"></div>
</div>
```

**Comment by Kayparker** [comment]
Thanks for the help code. Can you please get me more details? How this custom validator is linked to my input in HTML?

Following is my HTML block I want to apply custom validator on it

<div class="input-group" style="margin-bottom: 10px;">
	@Html.TextBoxFor(model => model.CrossStreet, new { @class = "form-control", @id = "selectedIntersection", @readonly = "readonly", @required = "required"})
</div>

**Comment by 1000hz** [comment]
`required` needs to be a `data-required` attribute. I'm not sure what language your snippet is, but you'd need to replace `@required`.

**Comment by vimjain** [comment]
Hi,

I am trying use custom validation but it is not working. Can you give me an example with html and js.

**Comment by jmzc** [comment]
Maybe I'm wrong , but I think that you need to include both of them : required and data-required.
At least I had to do it 

 <input type="text" required="true" data-required="true" readonly>
