### ISSUE TITLE
How can a submit button bypass the validation

### ISSUE THREAD

**Issue by Kayparker** [1000hz/bootstrap-validator#104]
I have two buttons on the form "Save", "Cancel"

I want that your awsome plugin does it job on Save click but not on "cancel" submit. Can you please advise?

**Comment by 1000hz** [comment]
the submit button should have a `type="submit"` and the cancel button should have `type="button"`

**Comment by BWeesy** [comment]
I believe this is related to this issue.

I have a required text field, a submit button (type = "submit"), and a cancel button (type = "button").
Starting from a pristine form, if I focus on the text field and then click the cancel button, the cancel method is blocked by the form validation starting.

Is there any way to stop the cancel button firing the validation for the entire form?

**Comment by KrunalSoniCygnet** [comment]
what if i have two submit button but i have to select any action based upon the click of particular button
