### ISSUE TITLE
custom validation function documentation

### ISSUE THREAD

**Issue by bkdotcom** [1000hz/bootstrap-validator#105]
> Object structure is: {foo: function($el) { return true || false } }

> Adding the validator to an input is done just like the others, data-foo="bar"

What is `"bar"`?   Is it used or passed to the custom validator function?
wouldn't  `data-custom="foo"` or `data-custom-validator="foo"`  make more sense?

**Comment by 1000hz** [comment]
That's basically there to illustrate that custom validators can use the value of the attribute as a parameter, accessed within the validator via `$el.data('foo')`

Imagine you had some captcha field `<input type="text" data-captcha="s3Gdg">`
```js
custom: {
  captcha: function ($el) {
    return $el.val() === $el.data('captcha')
  }
}
```

**Comment by 1000hz** [comment]
>What is "bar"? Is it used or passed to the custom validator function?
wouldn't data-custom="foo" or data-custom-validator="foo" make more sense?

The way it's currently designed keeps usage consistent with the other validators (data-minlength, data-match), allows you to have multiple custom validators on a single field, and is concise.

**Comment by bkdotcom** [comment]
gotcha 
if I look at `<input data-foo="bar" required />`   there is nothing there to tell me that "foo" is a validator that I've defined (no semantics).   likewise without having a consistent attribute name, it's difficult to search though my html to find inputs with custom validation

`data-custom="myFunction"`  provides a consistent attribute name    
`data-custom="myFunctionA, myFunctionB"`    multiple validators could be comma separated

'tis my only beef.   It's a great & simple to use plugin.

**Comment by bkdotcom** [comment]
additionally, it's worth documenting that you can't currently have upper/camel-cased validators

    custom: {
      myValidator: function ($el) {
        // data-myValidator="foo"  becomes data-myvalidator="foo".... and case-sensitivity
        return false
      }
    }

**Comment by bkdotcom** [comment]
... in the meantime, I've settled on using  `data-functionname="custom-validator"`

**Comment by nelson6e65** [comment]
I want to make a conditional required... 

```js
requiredif: function($this) {
    console.log("Runing custom validator");

    selectorName = $this.attr("data-requiredif");

    isActive = $("input:checkbox[name='" + selectorName + "']").is(":checked");

    console.log(isActive); 
    console.log(!$this.val() === false); // always true

    if (isActive && !$this.val() === false) {
        return true;
    }

    return false;
}
```

But... Custom validators only runs if there is content in the field? Because it only enter to function while I'm typing, not when I click con Submit `button` or unfocus the field.

**Comment by nelson6e65** [comment]
btw, 

> ```js
custom: {
  captcha: function ($el) {
    return $el.val() === $el.data('captcha')
  }
}
```

will not work, unless you change `===` for `==` if you use only numbers in `data-captcha`, like `data-captcha="12345"`.

And still, by the way, errors in this is not take in count for submit button disable/validation (it's skipped).

**Comment by rumentab** [comment]
Hi, 1000Hz
I have a problem with custom validation of a field. I was wondering is the problem that I have an AJAX request in the validation function. Actually the function works and returns correct values (true or false) but the field is always validated as invalid.
`<input type="text" class="form-control" id="username" placeholder="<?php echo lang("Username", $lang); ?>" name="username" autofocus required autocomplete="off" data-custom="uniqueusername" data-uniqueusername="true" />

$("#user_regform").validator({
				disable: true,
				custom: {
					"uniqueusername": function(el) {
						$.ajax({
							url:'/lib/validator.php',
							type:'POST',
							data: {username: $(el).val()},
							success: function(result) {
								console.log(Boolean(result));
								return Boolean(result);
							}
						});
					}
				},
				errors: {
					"uniqueusername":"<?php echo lang("Username in use", $lang);?>",
				}
			});
`

**Comment by dserve38** [comment]
Hi,
@rumentab I have the same problem, which should come from the asynchronism of the Ajax call.
Have you found a workaround ?

**Comment by QuadeHale** [comment]
You guys could try using the jQuery promises instead? 
```
$.ajax({
    url:'/lib/validator.php',
    type:'POST',
    data: {username: $(el).val()},
}).done(result => {
  console.log(Boolean(result))
  return Boolean(result)
}).fail(err => {
  console.log('Error:', err)
})
```

Haven't tried it yet and have no need(thanks for the tip regarding capitalized letters though, that fixed me up)
