### ISSUE TITLE
Multiselect plugin validation

### ISSUE THREAD

**Issue by kritochin** [1000hz/bootstrap-validator#108]
Hi. I have a form with with several controls. One of them is a multiselect, for which Im using a plugin. I want to validate that at least one option is selected, so I implemented the following:
JS:
$.fn.validator.Constructor.VALIDATORS.validateMultiselect = function ($el) {
                var arrSelect = $el.val()
                return (arrSelect != null && arrSelect.length != 0);
}

HTML:

![image](https://cloud.githubusercontent.com/assets/3598010/7056674/736d3f6c-de13-11e4-86ca-5ec1756a39ef.png)

On a submit the validation is working, but I dont get the error message. I do get error messages for the other controls. 

Pleasy any thoughts of what I am missing?

Gracias.

**Comment by 1000hz** [comment]
Sorry this is late, but the custom validator name doesn't get converted from `dasherized-name` to `camelCaseName` for you. You need to name it just `multiselect` and tag your element with `data-multiselect="true"`
