### ISSUE TITLE
Is that possible to manually call validator?

### ISSUE THREAD

**Issue by katopz** [1000hz/bootstrap-validator#110]
I'm using backbonejs delegate events and I need to validate thing after submit button clicked something like...
```js
onSubmit: function () {
    $('#user-profile-form').validator().validate(successFunc, errorFunc);
}
```
At present I've to use (yes it work but not backbone events related)
```js
$('#user-profile-form').validator().on('submit', function (e) {...}
```
Or maybe the question should be how to beautifully use with backbonejs events?

Thanks

**Comment by 1000hz** [comment]
Check out the [project docs](http://1000hz.github.io/bootstrap-validator/#validator-methods).

```js
$('#user-profile-form').validator('validate')
```
is how you would manually trigger the validator. Then you can bind to the `validated.bs.validator` event for your callback functions.

Though if you initialize the validator before the form is submitted, it should automatically validated whenever the `submit` event is fired.

**Comment by katopz** [comment]
Cool! Thanks!
