### ISSUE TITLE
Scroll to first "not valid" field on form submit

### ISSUE THREAD

**Issue by barbushin** [1000hz/bootstrap-validator#113]
Problem:
1. There is a big form (2-3 screens)
2. User click Submit
3. One of first fields in the head of form are invalid, but user don't see this field and errors, and don't undestand why form is not submitted.

Solution: scroll to first not valid field, so user will fix it, and fix all other not valid fields untill scrolling down to Submit button.

**Comment by 1000hz** [comment]
See the solution I posted in #52

**Comment by barbushin** [comment]
This is not solution, it's workaround. 

I just think that this is very important(required) feature and it must be included in `bootstrap-validator` by default. Otherwise every user must use this JavaScript code every time, for every form - that's wierd.
