### ISSUE TITLE
Suggestion: custom validator return value

### ISSUE THREAD

**Issue by bkdotcom** [1000hz/bootstrap-validator#114]
currently custom validators return true/false  
error message comes from the errors object

Perhaps custom validator could/should return a string  
This would mimic/mirror the javascript validation API's [setCustomValidity\(\)](http://www.w3schools.com/js/js_validation_api.asp) method

non-empty string -> there's an error:   the string is the error message  
empty string = input is valid

**Comment by 1000hz** [comment]
Custom validators now return error strings when invalid in v0.11.0

**Comment by jcuypers** [comment]
Hi, it would be great to include this feedback clearly in the documentation/examples.   spent a lot of time finding this out and as far as I could see a lot of other people are/were breaking their head over the custom validation.  Anyway, great work.  thank you.
