### ISSUE TITLE
Compatibility with selectpicker?

### ISSUE THREAD

**Issue by nextpulse** [1000hz/bootstrap-validator#115]
Anyone have any tips or know if this is compatible with bootstrap selectpicker?

**Comment by xplicit** [comment]
I have run into issue, that selectpicker (https://github.com/silviomoreto/bootstrap-select) is not validated with bootstrap-validator. The cause of this behaviour is that selectpicker makes the underlying `select` element hidden when bootstrap-validator validates only visible fields https://github.com/1000hz/bootstrap-validator/blob/1c73a7a5f05ed320ecb788e89ea09dc949226d59/js/validator.js#L32

If remove `:visible` part from selector bootstrap-validator starts to validate selectpicker, but this is bad solution. Any ideas how this issue could be resolved are appreciated.

**Comment by xward1** [comment]
I had the same issue using bootstrap-select (selectpicker).  I solved it by doing this:

```javascript
$('.selectpicker').on('change', function() {
    var m, h, x, $el = $(this);
    var fg = $el.parents('div.form-group');
    if ($el[0].hasAttribute('required') || $el.is('[required]')) {
      if ($el[0].checkValidity() === false) {
        m = $el.data('error');
        h = '<ul class="list-unstyled"><li>' + m + '</li></ul>';
        fg.addClass('has-errors').find('div.help-block').html(h);
        //console.log(m);
      }
      else {
        fg.removeClass('has-errors').find('div.help-block').html('');
      }
    }
  });
```

**Comment by maximelebreton** [comment]
+1
