### ISSUE TITLE
Input type="number" validation doesn't work

### ISSUE THREAD

**Issue by bartek-gluszak** [1000hz/bootstrap-validator#12]
Hi,

I've checked input of email type or with pattern, it works OK. But the validator doesn't catch error with input type="number" when I enter something other then number (with min, max attributes or without).

**Comment by desfero** [comment]
The same for me. Try to remote `required` attribute from input and in firefox it did not validate text as invalid number.
See this example: http://jsbin.com/fajemap/edit?html,output
