### ISSUE TITLE
Prevent Mutliple submit

### ISSUE THREAD

**Issue by engcanada** [1000hz/bootstrap-validator#124]
I need validador.js be modified so it prevents duplicate submission when submit button is clicked.
I don't myself want to mess around with since I am not very knowledgeable in query.

Thanks

**Comment by bkdotcom** [comment]
separation of concerns?
this doesn't seem to be validation related

```
// disables submit btn on submit, and makes inputs read only
$("form").on.submit(function(e){
    $form = $(this);
    $form.find('input, select, textarea').prop('readonly', true);
    $form.find('input[type=submit], button').prop('disabled', true);
});
```
