### ISSUE TITLE
Add behaviour to set the focus on the first error field when the submit button is pushed ...

### ISSUE THREAD

**Issue by thierryho** [1000hz/bootstrap-validator#128]
I've just modify the code to add this behaviour but it will be nice to add it as a option to enable or disable it.

Part of modified code  : 

```javascript
Validator.prototype.onSubmit = function (e) {
        this.validate()
        if (this.isIncomplete() || this.hasErrors()) {
            $(".has-error:first input").focus();   // added this line
            e.preventDefault()
        }
    }
```

**Comment by PsychoJaps** [comment]
Thank you for this. I have made a slight change so as to focus on other kinds of form elements (input, select, textarea, etc):

```javascript
Validator.prototype.onSubmit = function (e) {
        this.validate()
        if (this.isIncomplete() || this.hasErrors()) {
            $(".has-error:first :input").focus(); //slight change here using :input
            e.preventDefault()
        }
}
```

**Comment by thierryho** [comment]
Great thank you for your feedback.

**Comment by yanickrochon** [comment]
This should be an option and pushed to master.

**Comment by nelson6e65** [comment]
:+1:

**Comment by nelson6e65** [comment]
:+1: Yes, should be nice this option!

@thierryho @PsychoJaps, I don't know how to use this (What is `Validator`?):
 
> ```js
Validator.prototype.onSubmit = function (e) {
        this.validate()
        if (this.isIncomplete() || this.hasErrors()) {
            $('html, body').animate({ scrollTop: $(".has-error:first :input").offset().top - 50 }, 500);
            $(".has-error:first :input").focus();
            e.preventDefault()
        }
}
```

But I wrapped your code following documentation listening `on('submit')` event  (http://1000hz.github.io/bootstrap-validator/#validator-events) and do what I wanted. Thanks!

```js
$('#model-add-form').validator().on('submit', function (e) {
    if (e.isDefaultPrevented()) {
        // handle the invalid form...

        $('html, body').animate({ scrollTop: $(".has-error:first :input").offset().top - 50 }, 500);
        $(".has-error:first :input").focus();

    } else {
        // everything looks good!
    }
})
```

**Comment by 1000hz** [comment]
Just wanted to mention this is gonna be added as an option in the next version of the plugin, but I was pretty much gonna add what @nelson6e65 just posted. :+1:

**Comment by ajayasekara** [comment]
asasasas
