### ISSUE TITLE
Validate certain field only on blur

### ISSUE THREAD

**Issue by garygreen** [1000hz/bootstrap-validator#129]
Seems there's only a way for it to validate on keypress, is there a way to override this on a per-field level?

**Comment by 1000hz** [comment]
You could do something like
```js
$('#myField').on('input.bs.validator', function (e) {
  e.stopImmediatePropagation()
})
```

**Comment by garygreen** [comment]
That might would but ideally it would be nice to override on a per-field level. Something like `data-validator-trigger="change,blur"`
