### ISSUE TITLE
Validate on blur without delay

### ISSUE THREAD

**Issue by garygreen** [1000hz/bootstrap-validator#130]
It would be good to add option to automatically validate straight away when blur from the field, as it will make the validation feel more speedy to the user.

**Comment by 1000hz** [comment]
Yeah, this seems like a good idea. I'll need to think about how to implement it cleanly.

**Comment by garygreen** [comment]
Yup. I think the whole delay and triggering of the validation needs a bit of refinement.

For instance, if there has already has an error shown, validation should next run as soon as it can i.e. on keypress and without delay. 
Or just 'reset' the ui to remove the error/success msg as soon as key is pressed, as it won't be known if it's valid until the validation is actually run after the delay.
The whole plugin feels pretty slow imo because of all this delay stuff

**Comment by Simonn-** [comment]
+1

**Comment by chenster** [comment]
+1
