### ISSUE TITLE
Hidden field's validation

### ISSUE THREAD

**Issue by ArturGabrys** [1000hz/bootstrap-validator#134]
Hi,
Thank you for your fix https://github.com/1000hz/bootstrap-validator/issues/65

but now I have situation where hidden input (radio buttons in this case) should be validate is there any parameter which could turn ON validation for specific hidden fields?

I have a rate system, pretty basic 5 stars, hidden radio's and you need to click on the label which is a star to choose a rate. Since radio are hidden form is submited without selecting rate.

Thank you.

**Comment by octagonal** [comment]
Did you find a workaround for this? I need it as well.

**Comment by xplicit** [comment]
I've got same issue see https://github.com/1000hz/bootstrap-validator/issues/115

**Comment by xplicit** [comment]
I have workarounded this issue by changing `inputSelector` var in the line https://github.com/1000hz/bootstrap-validator/blob/1c73a7a5f05ed320ecb788e89ea09dc949226d59/js/validator.js#L32 

to

`:input:not([type="submit"], button):enabled:visible, .selectpicker`

`.selectpicker` is the class of the element which always will be validated even it's hidden

**Comment by yanickrochon** [comment]
Would be nice to specify the input selector from the options.

**Comment by 1000hz** [comment]
You can specifiy it by overriding `$.fn.validator.Constructor.INPUT_SELECT` in your code without having to edit the validator source.

**Comment by yanickrochon** [comment]
Fair enough. Thanks.

**Comment by r00t4bl3** [comment]
I have same problem using this validator for star rating system which element to be validated is hidden by CSS. I'm overriding INPUT_SELECT at first, but it's not working. So I checked the code and found that it's INPUT SELECTOR now. Here's what I'm using (and it's working fine) now:

JS:
`$.fn.validator.Constructor.INPUT_SELECTOR = ':input:not([type="submit"], button):enabled:visible, .rating-radio';`

HTML:
`<input type="radio" id="star5" name="rating" value="5" required="" data-rating="true" class="rating-radio"><label class = "full" for="star5" title="Awesome - 5 stars"></label>`

Replace `.rating-radio` with your own class.

**Comment by vicbiz** [comment]
hi, 1000hz
I really thank you for great validator. I'm trying to use this validator with chosen selector(https://harvesthq.github.io/chosen/) but it's not working.  I tried 

$.fn.validator.Constructor.INPUT_SELECTOR = ':input:not([type="submit"], [type="reset"], button):enabled:visible, .chosen-select, .select2';

but not working....

Can you please help me on this?

**Comment by vicbiz** [comment]
I figured out, there is another input field came from chosen selector. so I added "search-field input" and works fine. 

$.fn.validator.Constructor.INPUT_SELECTOR = ':input:not([type="submit"], [type="reset"], button, **.search-field input**):enabled:visible, .chosen-select, .select2';
