### ISSUE TITLE
How to mark an HTML5 field as not required?

### ISSUE THREAD

**Issue by paulobranco** [1000hz/bootstrap-validator#136]
I have a input type="email". it is not required, however on IE9 if I submit the form with nothing in this field it still blocking the submittion and marks the field as required. I can change the type of the field to text and it works ok, however I will lose the email keyboard friendly on mobile devices.

Can I set an input type email as not required for IE9?

**Comment by nickelleon** [comment]
IE9 doesn't support input[type=email] and that may be why you're receiving odd issues with it.

http://caniuse.com/#search=email

**Comment by paulobranco** [comment]
Hi Nickelleon, thanks for your reply. I understand that IE9 does no support type="email", however I am using the recommended script for IE9 support (H5F).

It is for one form where the field is not required. I have implemented an workaround that changes the type of the field to text on page load if the browser is IE9 and below.

**Comment by 1000hz** [comment]
It seems like H5F doesn't implement any email address validation. Though it shouldn't mark the field as invalid. Did you remember to activate H5F?

```js
H5F.setup(document.getElementById("myForm"))
```
