### ISSUE TITLE
IE 9 can't work, error info can't be shown

### ISSUE THREAD

**Issue by yinjun622** [1000hz/bootstrap-validator#138]

**Comment by nelson6e65** [comment]
:no_mouth::question:

**Comment by nickelleon** [comment]
According to the documentation:

"Cross-browser Compatibility:
Because this plugin depends on the HTML5 Constraint Validation API, Internet Explorer 9 and older are not supported. If you need to support these browsers, you must add a polyfill like Ryan Seddon's H5F."

**Comment by Arlen22** [comment]
What was the last version that supported IE 8 and 9?

**Comment by 1000hz** [comment]
They have always required a polyfill
