### ISSUE TITLE
Trigger custom error *after* validation?

### ISSUE THREAD

**Issue by willy0275** [1000hz/bootstrap-validator#145]
I have a situation where I'd like to validate the form first, and when the form is valid I then submit the form with a jQuery ajax call which returns a json with possible server side errors. More specifically, there is one input where the text is invalid if it exists already in the database. I know I could use a custom error handler with ajax, but I don't want that check to be done when the user is entering data on the form, I need to manually trigger that error after the form is validated and the ajax call is done. 

I'm guessing I would need something like this: 

```
$().validator('error', {
    'name-of-input',
    'error-message'
});
```
This method would mark the input as having an error, so the red border and highlighted label would show up and the error-message would show up in the related error div. 

Is there a way currently to achieve this?

**Comment by 1000hz** [comment]
The plugin doesn't have any support for server-side validation apart from the `remote` validator that checks an individual field as you type.

You'd need to manually add any errors and `.has-error` classes to any input groups, though I  have a feeling that each error would disappear immediately as soon as the user starts typing in the field (which probably isn't the behavior you want).

**Comment by willy0275** [comment]
Thanks. I'm surprised that there were no other similar requests. Let's say you have an input for a username, and you want to check at the last second, before inserting the data in the database, if the username already exists. You will then need to return an error to the client from the server. That's somewhat typical. 

Your form validator is my favorite from all the ones I've tried, but it's the only one that won't allow manual error triggers outside the standard validation workflow. For example, jQuery Validation Plugin (http://jqueryvalidation.org/) has a Validator.showErrors() method which can manually trigger errors. 

Thanks again, I'll ponder what's the cleanest and easiest technique to plug my custom error in. Maybe the .has-error class will be enough.

**Comment by 1000hz** [comment]
I'm just curious, why don't you want to check the username on the fly as the user is typing? You'll need an API endpoint to run the validation against, but I'm trying to think of any other reasons aside from simple design preference.

**Comment by willy0275** [comment]
I could check it as the user is typing, but in this case it's a big form and it could take a few minutes for the user to finish filling the form before submit. So the check has to be done again on server-side. I am not checking the username in real-time at the moment because it's not that critical to know right away and I'm a little lazy (it's for a client's admin, not a public page). But lazy as I am, I can't avoid that final check on the server.

**Comment by 1000hz** [comment]
I see. Well, if you change your mind it seems like you could probably solve your problem pretty easily using the `remote` validator. You just need to set up an API endpoint that receives a value and returns a `200 Success` if valid or anything else (like `400 Bad Request`) if it's invalid. Then point your field to your endpoint:

```html
<input type="text" name="username" data-remote="/api/validations/username">
```

Check out https://github.com/1000hz/validator-remote-example for a reference on what the API is expected to behave like.

**Comment by willy0275** [comment]
Thanks for the tips!

**Comment by willy0275** [comment]
By the way one thing I misunderstood and I can see now with the profiler 
while testing, is that remote validation is *also* done at form submit 
time, so that you can actually enforce validating remotely at the final 
submit stage. I thought the remote call was only done when interacting 
with the input directly. It's not really clear in the doc. Thanks again!
