### ISSUE TITLE
Is there a way to have setCustomValidity not interfere with validator?

### ISSUE THREAD

**Issue by willy0275** [1000hz/bootstrap-validator#146]
I am programming a form in French so I needed to have the default Chrome message "Please fill out this field" to be changed to the equivalent in French. Using

```
oninvalid="this.setCustomValidity('Ce champs est requis')"
```

on an input works, but then once the message shows up it never disappears. It seems to interfere with validator. Is there a way to circumvent this?

**Comment by 1000hz** [comment]
either pass in your custom message via options to have it apply globally to the whole form:
```js
$('#myForm).validator({errors: {native: 'Ce champs est requis'}})
```
or set `data-error` on the individual field:
```html
<input type="text" data-error="Ce champs est requis" required>
```

**Comment by willy0275** [comment]
The problem is, my input also has a remote call validation, and when I 
use data-error, the error from my remote call stops showing. Can you 
have both a data-error *and* remote error at the same time?

I will try with the errors option tonight and see if it works better, 
thanks.

**Comment by willy0275** [comment]
When trying the with the errors option, 

```
$(function() {
    $('#myform).validator({errors: {native: 'Ce champs est requis'}})
}
```
I still get "Please fill out this field." when field is empty. When I try 
```
<input type="text" class="required form-control" name="navigation-title" required data-error="Ce champs est requis" data-remote="validate-navigation-title.php" />
```
I get the correct French message initially when field is left empty, but then my remote message never shows up. It seems that using data-error overrides any message from remote?

Just to be clear, I need two different messages for the same input. One for field is empty, and one for value already exists in database...

**Comment by 1000hz** [comment]
I think you could set `data-native-error` instead of just `data-error`
