### ISSUE TITLE
How to tell if the form is valid after validating?

### ISSUE THREAD

**Issue by vicentor** [1000hz/bootstrap-validator#148]
After using `$('#frm_employee_dependent').validator('validate');`, how can I tell the result is valid or not?

I'm using a button instead of a submit type input, so I need to know if it's okay to continue or not.

**Comment by 1000hz** [comment]
There are a few ways you could do it. One way is to check if your submit button has a `.disabled` class applied to it. Another is to check if any of your `form-group`s have the `.has-error` class.

**Comment by vicentor** [comment]
Alrighty!
I made this to solve my problem.

    function form_validate(attr_id){
		var result = true;
		$('#'+attr_id).validator('validate');
		$('#'+attr_id+' .form-group').each(function(){
			if($(this).hasClass('has-error')){
				result = false;
				return false;
			}
		});
		return result;
	}

**Comment by sajjad-shirazy** [comment]
`if($('#form').has('.has-error')){
    //it's not valid
}`

**Comment by phpnets** [comment]
@vicentor, 1000hz,
how we can makesure $('#'+attr_id).validator('validate'); will finished before checking the has-error class in your answer. Because JavaScript will run in different threads. it may not be the line by line execution.

**Comment by loicbisiere** [comment]
@phpnets It seems that validator("validate") return a synchronous flow as suggested by @1000hz is this comment : https://github.com/1000hz/bootstrap-validator/issues/247#issuecomment-162685431

@1000hz Could you please confirm this validation strategy is synchronous ? :
```
if ($('#myForm').validator('validate').has('.has-error').length === 0) {
  // form is valid
}
```

Thank you.

**Comment by 1000hz** [comment]
It is for now, but that will probably change whenever I add support for async validators (via Promises). In that case, there will also need to be more events (such as one when all validators have finished running).

**Comment by Arctic7** [comment]
`$('#myForm').validator('validate').has('.has-error').length`
very good, solved my problem, I have to say the Bootstrapvalidator is the best form validation plugin for Bootstrap.
