### ISSUE TITLE
How to make it works?

### ISSUE THREAD

**Issue by jrosette** [1000hz/bootstrap-validator#150]
Hi,

This is one week now i'm trying to use this superb validator and was not able to get it works here is the code I did:

*******************

    <form data-toggle="validator" role="form">
                            <br>
                            <div class="form-group">
                                <div class='input-group'>
                                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                    <input type="text" class="form-control" id="mail" placeholder="Adresse mail" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                    <input type="text" class="form-control" id="firstname" placeholder="Entrez votre prenom">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                    <input type="text" class="form-control" id="name" placeholder="Entrez votre nom">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputPassword" class="control-label"></label>
                                <div class="form-group">
                                    <div class="input-group">
                                        <span class="input-group-addon"><span class="fa fa-lock"></span></span>
                                        <input  data-toggle="validator" id="inputPassword" data-minlength="6" type="password" class="form-control" placeholder="Mot de passe" data-match-error="Minimum of 6 characters" required>
                                    </div>
                                    <span class="help-block with-errors"></span>
                                </div>    
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-lock"></span></span>
                                    <input  id="txtConfirmPassword" type="password" class="form-control" placeholder="Retapez votre mot de passe" data-match="#inputPassword" data-match-error="Votre mot de passe ne correspond pas au precedent." required>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <br>                
                        </form> 

******************************

i used validator.min.js and also validator.js but no one give me success, Can someone can help me to solve this issue, please?

Br,

Jérémie

**Comment by rene-s** [comment]
Please be more specific.

**Comment by 1000hz** [comment]
It seems to work for me when I copy/paste your code into JSBin.
http://jsbin.com/nuqayetoye/1/edit?html,css,js,output

I'm going to close the issue, but feel free to comment again if you haven't figured out the problem already.

**Comment by jrosette** [comment]
Hi guys,

Thx for your support , I don't know why it was not.working I spent two days on that . finally I decided to move to validite.js and succeed to do what I want. Thx again
