### ISSUE TITLE
How do I make a field invalid by code?

### ISSUE THREAD

**Issue by paulobranco** [1000hz/bootstrap-validator#151]
Question
How do I exclude a field to do not validate on focus out?

**Comment by 1000hz** [comment]
`$('#myForm').validator().off('focusout.bs.validator')`

**Comment by paulobranco** [comment]
Is there something like

$('#fieldId).valiator('invalid.bs.validator');

to make the field invalid?

**Comment by 1000hz** [comment]
There is no API for that, but you might be able to accomplish something like that with a custom validator.

```js
var invalidFields = {}
function manualValidator($el) {
  return !invalidFields[$el.attr('id')]
}

$('#myForm').validator({
  custom: {
    manual: manualValidator
  },
  errors: {
    manual: "This field is invalid"
  }
})

function invalidateField($el) {
  invalidFields[$el.attr('id')] = true
  $el.trigger('input')
}
```
