### ISSUE TITLE
It will be good to multiple error messages

### ISSUE THREAD

**Issue by sudarshann** [1000hz/bootstrap-validator#153]
HI I have been using this for my projects. 
I find it very useful
It will be very good if you can make features to accept multiple error messages like
data-remote-400-error=""
data-remote-failed-error=""
data-remote-offline-error=""

and some other combinations too

**Comment by 1000hz** [comment]
The remote validator will display whatever error the endpoint responded with. Currently, the server must put the error in the `HTTP status text`, but in the future that may change to the response body.

See https://github.com/1000hz/validator-remote-example

**Comment by mlts** [comment]
I think this information should be in the wiki, because I spent like 5 hours looking for it. 

Thanks!

**Comment by 1000hz** [comment]
I thought I had added this to the docs. I'll double check. Sorry about the trouble!
