### ISSUE TITLE
horizontal forms

### ISSUE THREAD

**Issue by duffnering** [1000hz/bootstrap-validator#154]
I know the docs state that each input should be within a single .form-group, but I use horizontal form fields, such as first name and last name -- both are contained within the same .form-group. This results in both fields being marked invalid when only one is actually invalid.
Is there a means to accomplish this? Maybe something I am overlooking?
Thanks for your help!

**Comment by 1000hz** [comment]
You can use the bootstrap grid classes. Check out the password fields on the docs page.

**Comment by duffnering** [comment]
Thank you for your reply.
Maybe I am not understanding your answer. I currently have my form layout as referenced by the password fields on the docs page. Here is an excerpt:

<div class="form-group">
	<label for="first_name" class="col-sm-2 control-label">First</label>
	<div class="col-sm-4">
		<input type="text" id="first_name" name="first_name" class="form-control" value="<?php echo $sc_first_name; ?>" placeholder="First Name" required>
	</div>
	<label for="last_name" class="col-sm-2 control-label">Last</label>
	<div class="col-sm-4">
		<input type="text" id="last_name" name="last_name" class="form-control" value="<?php echo $sc_last_name; ?>" placeholder="Last Name" required>
	</div>
</div>

The issue is both inputs show invalid when either field is invalid, rather than only the actual invalid field being shown invalid. Both fields are contained by a single .form-group, which according to the validator docs, is not really supported.

Am I misunderstanding your answer?

**Comment by 1000hz** [comment]
```html
  <div class="form-group">
    <label for="inputPassword" class="control-label">Password</label>
    <div class="form-group col-sm-6">
      <input type="password" data-minlength="6" class="form-control" id="inputPassword" placeholder="Password" required>
      <span class="help-block">Minimum of 6 characters</span>
    </div>
    <div class="form-group col-sm-6">
      <input type="password" class="form-control" id="inputPasswordConfirm" data-match="#inputPassword" data-match-error="Whoops, these don't match" placeholder="Confirm" required>
      <div class="help-block with-errors"></div>
    </div>
    </div>
  </div>
```

Check out how there are `.form-group`s with grid classes nested inside of another `.form-group`
