### ISSUE TITLE
How to disable ajax event

### ISSUE THREAD

**Issue by barttom** [1000hz/bootstrap-validator#155]
Hello!
I want to disable ajax validation and validate forms only, when user click on submit.
How can i do that?

**Comment by 1000hz** [comment]
Not sure what you mean. Don't use the `data-remote` validator if you don't want any ajax validations? 

Do you mean you don't want to validate fields as the user types in them? If so, you can do this:
```js
$('#myForm').off('input.bs.validator change.bs.validator focusout.bs.validator')
```

**Comment by barttom** [comment]
Yeah, thats what i need. I figure out it by myself, but thanks for reply!
