### ISSUE TITLE
Tabs Validation Not Working

### ISSUE THREAD

**Issue by carolgit** [1000hz/bootstrap-validator#156]
Não valida form completo quando dividido em tabs

**Comment by 1000hz** [comment]
I'm sorry, I don't speak Portuguese so I don't really understand your issue. Can you try to recreate your problem on JSBin?

Here's a template to get you started.
http://jsbin.com/bisusunusi/1/edit

**Comment by karamelichkin** [comment]
1000hz, here
http://jsbin.com/hoguvivilo/2/edit?html,output

i have same issue

**Comment by traone** [comment]
Same here also. Validates only fields which are visible.

**Comment by 1000hz** [comment]
In the latest version (v0.9.0) you can override the input selector like this:
`$.fn.validator.Constructor.INPUT_SELECTOR = ':input:not([type="submit"], button):enabled'`
http://jsbin.com/suboqivaqo/edit?html,js,output

In the future, there will be explicit overrides enabled to force a particular input to be validated / unvalidated

**Comment by spurgeonbj** [comment]
Hi! 

Thanks for the nice utility. 

I love this, but am also facing the same issue.

I tried using it on a big form, spread across multiple tabs.

It works only on the first tab.

When I moved all controls to that tab, it works. 

However, having a long form is not intuitive and ideal.

I understand from your response that this can be made to work.

Can you please be more specific and give a sample snippet?

Do we need to use your above snippet for every control?

Looking forward to your kind response.

Thanks!

**Comment by 1000hz** [comment]
This has been fixed in v0.11.0. Invisible fields are no longer ignored.

**Comment by spurgeonbj** [comment]
Thanks a ton! God bless you!
