### ISSUE TITLE
the class that error, success, warning changed

### ISSUE THREAD

**Issue by ilovezy** [1000hz/bootstrap-validator#158]
hello there, I really need this plugin now, but there is some change in bootstrap 3.2.0, look, the error, warning and success class add a prefix 'has-', would you please update this plugin to match the bootstrap ? thanks
![x](https://cloud.githubusercontent.com/assets/8774988/8449991/f29577fa-2008-11e5-8b16-abc9f9ce9df8.png)

**Comment by 1000hz** [comment]
They already have these prefixes.

**Comment by ilovezy** [comment]
ouch! I'm so sorry, I mistake used another plugin called jqBootstrapValidation, it's their problem,ohhhhh ,sorry
