### ISSUE TITLE
 $().validator('destroy') block e.isDefaultPrevented() with code to test now

### ISSUE THREAD

**Issue by giugit** [1000hz/bootstrap-validator#159]
You Can easily verify the problem following these step

1) Click Send (The Alert Invalid is showed correctly)
2) Now click on New ( that run function ResetFormSMS() ) and then Send Again (From Now the alert Valid is Showed but this in incorrect)

Thank You!

<!DOCTYPE html>

<head>
	<script src="http://code.jquery.com/jquery.min.js"></script>
	<link href="http://getbootstrap.com/dist/css/bootstrap.css" rel="stylesheet" type="text/css" />
	<script src="http://getbootstrap.com/dist/js/bootstrap.js"></script>
	<script src="http://1000hz.github.io/bootstrap-validator/dist/validator.min.js"></script>
</head>

<body>

	<form id="ModuloSMS" data-toggle="validator" role="form" method="post" action="">
		<div id="SMSLOGINKO">
			<div class="row">		
				<div class="form-group col-sm-6">
					<label for="userSMS2" class="control-label">User *</label>
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-user"></i></span>
						<input type="text" class="form-control" id="userSMS2" name="userSMS2" placeholder="User Name" required>
					 </div>   
				</div>
			</div>
		</div>
		<div>
			<div class="form-group">
				<button type="button" class="btn btn-info" id="NuovoMessaggioSMS" onclick="ResetFormSMS()">New</button>
				<button type="submit" class="btn btn-success" id="InvioMessaggioSMS">Send</button>
			</div>
		</div>
	</form>

	<script>
	
	function ResetFormSMS() {
		$('#ModuloSMS').validator('destroy');
		$('#ModuloSMS').validator();

	}

  $(document).ready(function() {

	$('#ModuloSMS').validator('destroy');
	$('#ModuloSMS').validator();

	//Modulo Invio SMS form submit
		$("#ModuloSMS").validator().on('submit', function (e) {
			if (e.isDefaultPrevented()) {
				alert('invalid!')
			}
			else 
			{	alert('valid!')
				var postData = $(this).serializeArray();

				}
		    
		});
  });
	</script>

</body>
</html>

**Comment by 1000hz** [comment]
Oh I see what's happening. Once the validator is reset, your submit handler now bound ahead of the validator handlers. You'll need to unbind/rebind that in your reset function.
