### ISSUE TITLE
Specify Minimum Required jQuery Version

### ISSUE THREAD

**Issue by fishermand46** [1000hz/bootstrap-validator#160]
I can't find anywhere in the docs that specifies the minimum jQuery version this library is compatible with. I see that you use 1.10.2 in your demo, but I'm not sure if that's the minimum required or not?

I spun up a [JSFiddle](https://jsfiddle.net/fishermand46/hstggb1y/) to test it out with different versions, and it looks like the semantics of $.map changed from v1.7.2 to v1.8.3. [This](https://github.com/1000hz/bootstrap-validator/blob/1c73a7a5f05ed320ecb788e89ea09dc949226d59/js/validator.js#L183) is the line it's choking on in v1.7.2.

Thanks!

**Comment by 1000hz** [comment]
Bootstrap itself has a hard dependency of jquery >= 1.9.1, but this plugin as you mention is still compatible with 1.8.3.

Changing [Line 185](https://github.com/1000hz/bootstrap-validator/blob/1c73a7a5f05ed320ecb788e89ea09dc949226d59/js/validator.js#L185) to 

`.append($.map(errors, function (error) { return $('<li/>')[method](error)`**[0]**` }))`

would extend compatibility to v.1.7.2, but I don't think I'm gonna make that change to the plugin in the interest of progress.

I'll be sure to add the `jquery >= 1.8.3` dependency to the bower.json file. Thanks!
