### ISSUE TITLE
Summernote Validation

### ISSUE THREAD

**Issue by MehGokalp** [1000hz/bootstrap-validator#162]
I try many way to validate summer note note but i can't. Here is my code
JS:
```javascript
$('#frm').validator({
	custom: {
		summernote: function($el){
			var code=$el.code()
			if(code.length<=11) return false//Summernote default has <p><br/></p>
			else return true
		}
	},
	errors: {
		summernote: 'This field can\'t be empty'
	}
})
```
Html:
```html
<div class="form-group col-md-12">
	<label class="control-label">Metin:</label><br />
	<textarea class="summernote" data-editor="1" name="metin" required data-summernote="validate"></textarea>
	<div class="help-block with-errors"></div>
</div>
```

Then i have tried this way:
Js:
```javascript
$.fn.validator.Constructor.VALIDATORS.summernote = function ($el) {
	if($el.code().length<=11) return false//Summernote default has <p><br/></p>
	else return true
}
```
Html:
```html
<div class="form-group col-md-12">
	<label class="control-label">Metin:</label><br />
	<textarea class="summernote" data-editor="1" name="metin" required data-summernote="validate" data-summernote-error="This field can't be empty"></textarea>
	<div class="help-block with-errors"></div>
</div>
```
So anybody help?

**Comment by 1000hz** [comment]
Not sure if you typed this example up just now or copy/pasted it from your code, but you have a typo in
```js
if($el.code().lenght<=11) return false
```

should be 
```js
if($el.code().length<=11) return false
```

**Comment by MehGokalp** [comment]
Ops. You are right in this example it's wrong. In document i wrote length :)

**Comment by 1000hz** [comment]
You are using the custom validator correctly, so I don't know what could be wrong. Maybe that `.code()` jQuery plugin isn't working. Are you getting any console errors?

**Comment by MehGokalp** [comment]
Nope :(

**Comment by 1000hz** [comment]
I just looked into what summernote does and it seems like it hides and replaces your textarea with its own and doesn't carry over the data-attributes, so the validator doesn't try to validate it. You should open an issue on summernote to preserve data-attributes on the replaced element.

In the meantime, you can just be sure to add the validator attributes to the summernote element once it's been added
```js
$('#summernote').summernote();
$('.note-codable').attr('required', true).attr('data-summernote', true)
```
