### ISSUE TITLE
select with a "multiple" attribute is not getting styled

### ISSUE THREAD

**Issue by freshlySqueezedBananas** [1000hz/bootstrap-validator#163]
Hey!

First of all, thank you for this awesome plugin. So simple to use, yet very effective.

Only having one problem though. A select with "multiple" attribute parent .form-control is not getting styled. Remove said attribute et voilá, it works as expected. 

Wandered around the src code, but to no avail. Any lights on this?

**Comment by 1000hz** [comment]
Seems to work. Did you make sure to put `value=""` on your initial option?
Here's an example:
http://jsbin.com/viqaweyoqo/1/edit?html,output

**Comment by 1000hz** [comment]
Wait nevermind, having an initial option doesn't make sense for a multiple select

**Comment by 1000hz** [comment]
But, it should still work without that.

Here's an updated example:
http://jsbin.com/hagewoyowi/1/edit?html,output

**Comment by freshlySqueezedBananas** [comment]
Wow, fast answer on a sunday, thank you! :)

Actually I do have a 1st option without value="" as I'm using select2.js. Adding the value attribute indeed solved the issue. But messed with select2.js behaviour as now shows the 1st option with a string, instead of an empty field with a placeholder displayed.

So the problem is with select2.js and not bootstrap-validator. Will have to do a custom workaround I guess. 

Wondering why it works in a regular select, but not when added the multiple attribute. As same are built with the same ui generator, and so, the template's body is exactly the same. Any hint?

Thanks for the availability!

**Comment by 1000hz** [comment]
I'm not really sure. The best I can do is tell you to make sure that select2 is keeping a native `select` element visible, or else the validator won't see anything to check. Good luck!
