### ISSUE TITLE
Does the validator work with jquery ajaxForm, which is used to pass multiple files? 

### ISSUE THREAD

**Issue by PritiShah** [1000hz/bootstrap-validator#164]
I have a requirement where in I submit multiple files via jquery ajaxForm method (jquery.form.js)

I am using bootstrap validator 4.5 on a form which submits multiple files along with data. It seems this validator does not recognize the jquery ajaxForm method  (used to submit data and file) and hence nothing happens on submit button. 

Just wanted to check if this is an issue with 4.5 version. 

Thanks,
Priti

**Comment by 1000hz** [comment]
I think you might be in the wrong project. This plugin doesn't have a version 4.5.

**Comment by PritiShah** [comment]
Very sorry about the incorrect version typo - its actually  v0.4.5

Thanks,
Priti

**Comment by 1000hz** [comment]
Hmm, there's no v0.4.5 of this plugin either. There were a few different validator plugins targeting bootstrap. Maybe you're using a different one?

**Comment by PritiShah** [comment]
Yes, there are many validator plugins  for bootstrap floating on the net, and its kind of getting confusing since each has about the same name! 

I am using bootstrapValidator.js and its min - bootstrapValidator.min.js.

**Comment by PritiShah** [comment]
Thanks for your time. It seems like I am in  a different project after all!
