### ISSUE TITLE
Dropdown menus in Safari trigger error till they lose focus.

### ISSUE THREAD

**Issue by aoatridge** [1000hz/bootstrap-validator#168]
When you select an item from the drop down menu the error is triggered till you loose focus on that element. This only happens on Safari mac/pc.  I have tried with the newest version of bootstrap-validator but still get the same results. I don't think I missed anything and the page passes W3C Validation.

I created a stripped out version of my form here to weed out any other scripts.
https://mituberos.com/test.html

Thanks

**Comment by 1000hz** [comment]
Fixed in v0.11.0. See also #293
