### ISSUE TITLE
glyphicon not enabled in JS

### ISSUE THREAD

**Issue by stephenyang1987** [1000hz/bootstrap-validator#170]
It seems glyphicon-warning-sign or glyphicon-success not working in the validator.js

**Comment by 1000hz** [comment]
It works. Be sure you follow the Bootstrap conventions for form markup. In particular, you need a `has-feedback` class on your `.form-group`, and a `form-control-feedback` class on your icon.

Here's an example:
http://jsbin.com/bubiteyoga/1/edit?html,output
