### ISSUE TITLE
.min.js file returns compilation error

### ISSUE THREAD

**Issue by erandros** [1000hz/bootstrap-validator#171]
`validator.min.js:9 Uncaught SyntaxError: Unexpected token )`

The lib works great, btw.

**Comment by 1000hz** [comment]
What version are you using? This doesn't happen on the docs page, which is using the latest version (0.8.1)

Someone opened a pull request to fix this the other day (#169) but I didn't really know what they were running into and why.

**Comment by erandros** [comment]
I used the .min.js from the /dist in master branch.

**Comment by 1000hz** [comment]
Ah ok. Thanks for the report, I'll get it fixed.

**Comment by 1000hz** [comment]
I just released 0.9.0 which should fix this issue
