### ISSUE TITLE
AJAX throws error when using data-disable

### ISSUE THREAD

**Issue by kzisme** [1000hz/bootstrap-validator#175]
Currently, I'm trying to add validation to a form.  After trying a few different things I found out that
using:

<input type="submit" id="submit-button" class="btn btn-lg btn-primary" value="Submit" data-disable="true" />

Throws an error and creates an error when I attempt to POST.  If I change the input type to "button" it works, or if data-disable is removed as well.  

Here is my current AJAX call:
```
        $.ajax({

            type: "POST",

            contentType: 'application/json',

            url: apiRootURL + '/Requests/',

            dataType: "json",

            data: encompassRequest,

            async: true,

            success: function (data) {

                window.location.assign("/Home")

            },

            error: function (request, textStatus, errorThrown) {

                if (errorThrown == "Forbidden")

                    alert("Error:\nUser not authorized to add requests");

                else {

                    alert("Error:\n" + errorThrown)

                }

            }

        });
```

I was just trying to see if I'm doing something wrong or if this is a bug that someone else has experienced.

**Comment by 1000hz** [comment]
Did you mean to paste a code snippet after "I found out that using:" ? I don't really understand your issue.

**Comment by kzisme** [comment]
Yeah, sorry the missing line is: 

```
                <input type="submit" id="submit-button" class="btn btn-lg btn-primary" value="Submit" data-disable="true" />
```

Does that help at all?

**Comment by 1000hz** [comment]
Are you sure you're using the right plugin? I'm not sure what `data-disable="true"` on the submit button is intending to do. Before I dig a bit deeper, can you confirm you're working with http://1000hz.github.io/bootstrap-validator?

**Comment by kzisme** [comment]
Correct,  I'm using the plugin based off of the linked docs.  

Specifically: http://1000hz.github.io/bootstrap-validator/#validator-options 

Unless I'm using the disable option incorrectly - I'm trying to disable the submit button until all fields that are 'required' are valid.

**Comment by 1000hz** [comment]
I see. That's how it behaves by default so you don't need to specify it, and for future reference those options are meant to be defined on the actual form element or passed to the `.validator()` function as an object.

What error is being thrown?

**Comment by kzisme** [comment]
On form submit - I just receive an alert error (browser) and on the browser console there are two warnings.  

1. Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the user experience
2. Setting 'XMLHttpRequest.withCredentials' for synchronous requests is deprecated.

After that the page refreshes.

**Comment by 1000hz** [comment]
It sounds like you're not really having issues with the plugin, or maybe you're not instantiating it on your form.

You either need to add `data-toggle="validator"` to your form element or call `$('#myForm').validator()` to get it set up. The page is refreshing because the browser is handling the form submit, which results in a POST being sent to the server. Once the validator is instantiated, it will prevent the submit if the form is invalid, but if you want to submit via AJAX after that, you'll need to put your ajax call in a submit event handler and call `event.preventDefault()` before you make the request. So something along the lines of:

```js
$('#myForm')
  .validator()
  .on('submit', function (e) {
    e.preventDefault()
    $.ajax({
      // ... ajax request stuff here
    })
  })
```

**Comment by kzisme** [comment]
That's probably my issue...I will test it tomorrow and get back to you.  

I'm instantiating the plugin with data-toggle="validator" instead of using $('#myForm').validator() because if I use the latter I get an error of validator is undefined.  It ~does~ work fine with data-toggle though.

**Comment by 1000hz** [comment]
If that's the case, then the plugin isn't being loaded on your page, at least before your page scripts are running. Are you getting any actual validation behavior (fields turning red if they're invalid, etc.)?

**Comment by kzisme** [comment]
Yeah all the validation behavior works aside from submitting.  Should the plugin be the last script on the page?

**Comment by 1000hz** [comment]
You should load it after jquery but before the rest of your page scripts that are trying to use it.

**Comment by kzisme** [comment]
I figured as such - that's how I have it

**Comment by kzisme** [comment]
I added the event handling, removed the `data-disable="true"`, checked the order in which my scripts were being called and made certain that jquery was being called before the plugin script.  

Added event handling as such 

```
 $('#myForm').validator().on('submit', function (e) {
            e.preventDefault()
            $.ajax({
          // ... ajax request stuff here
                  type: "POST",
                  contentType: 'application/json',
                  url: apiRootURL + '/Requests/',
                  dataType: "json",
                  data: request,
                  async: true,
                  success: function (data) {
              window.location.assign("/Home")
          },
          error: function (request, textStatus, errorThrown) {
              if (errorThrown == "Forbidden")
                  alert("Error:\nUser not authorized to add requests");
              else {
                  alert("Error:\n" + errorThrown)
              }
          }
      })
  })
``` 

Everything works as expected now - but I do still have two re-occurring warnings.

```
1. Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
browserLink:37 
2.Setting 'XMLHttpRequest.withCredentials' for synchronous requests is deprecated.
```
 Any idea on those warnings?  Also thanks for the help!
