### ISSUE TITLE
custom validators not working

### ISSUE THREAD

**Issue by Dhruuva** [1000hz/bootstrap-validator#179]
Hi!  

Please see this sample  http://jsfiddle.net/dhruuva/tjt5sgf0/

 my Custom validation rule have no any reaction. Please point me what i missed ?

Best regards

**Comment by 1000hz** [comment]
Your jsfiddle isn't loading the plugin right because raw.githubusercontent.com isn't serving the file with the correct MIME type. Try loading it from `http://1000hz.github.io/bootstrap-validator/dist/validator.min.js` instead.

**Comment by Dhruuva** [comment]
Ok! Greet
Ye You are  Right it 's working now 
Thanks
