### ISSUE TITLE
Strong password pattern doesn't work

### ISSUE THREAD

**Issue by Dhruuva** [1000hz/bootstrap-validator#181]
So, I try create rule for strong password, just  it's must have at least one digit uppercase and lowercase letters.

 and regex is ^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])$  and rezult is here
 http://jsfiddle.net/dhruuva/3pvyym0o/
May be  somebody have any idea how it must work?
Best Regards

**Comment by 1000hz** [comment]
The pattern attribute of HTML Inputs matches against the whole string, so you don't need `^$` in your regex. Try this: `pattern="(.*[\d]+[A-Z]+.*)|(.*[A-Z]+[\d]+.*)"`

**Comment by Dhruuva** [comment]
Ou  Thank You !  Now I see my mistake
