### ISSUE TITLE
Enhancement: allow passing additional arguments for remote validation

### ISSUE THREAD

**Issue by vikashb72** [1000hz/bootstrap-validator#184]
Greetings,

would it be possible  update the Remote Validator so that i can pass addition parameters to the 
remote script ie add additional args to the enpoint ( data stored in data-remote-args :

Not sure if this is acceptable.

diff:
--- validator.js.original
+++ validator.js

<pre>
@@ -149,8 +149,17 @@
 
     if (!errors.length && $el.val() && $el.data('remote')) {
       this.defer($el, function () {
+/*
         var data = {}
         data[$el.attr('name')] = $el.val()
+*/
+        var data = $el.attr('name') + '=' + $el.val();
+
+        if ( $el.data('remote-args').length ) {
+           data += "&" + $el.data('remote-args');
+        }
+        
+
</pre>

html ( smarty template ):
<pre>

input type="text" class="form-control" name="OrgName" id="EditOrgName" placeholder="Organisation Name" value="101'' data-remote="/validate.php" 
data-remote-args="OrgID=101" required>
</pre>

**Comment by 1000hz** [comment]
Does setting `data-remote="/validate.php?OrgID=101"` not work?

**Comment by vikashb72** [comment]
Damn
Didn't try

Works as suggested
Thanks

**Comment by RationalEar** [comment]
How about sending some of the input fields in the form for remote validation. As an example, you may have two input fields which need to be validated against each other on the server side and therefore need to send both fields to the server.

**Comment by tsawyer** [comment]
> How about sending some of the input fields in the form for remote validation. As an example, you may have two input fields which need to be validated against each other on the server side and therefore need to send both fields to the server.

I'm looking for a way to do that as well.
