### ISSUE TITLE
Data-remote custom respons possible?

### ISSUE THREAD

**Issue by transonly** [1000hz/bootstrap-validator#186]
Hi,

I'm getting the 200 OK and 400 response code back ok but offcourse i'd like the 400 code to be somewhat descriptive about what's going wrong eg. username in use.
Can this be done while leaving your script intact?

**Comment by 1000hz** [comment]
Yes, your server needs to respond with the HTTP status text of the error you want. Here's an example server that displays custom errors.

https://github.com/1000hz/validator-remote-example

In a future version, the plugin will use the response body as the error message instead of status text.

**Comment by Trinea** [comment]
@1000hz hi, when it can  use the response body as the error message instead of status text now?

now if i have specified data-remote-error or data-error, it cannot use response status text as error message also

**Comment by geerdes** [comment]
@1000hz: Maybe a simple solution (which needs to be implemented) is to use different data-remote-error attributes for each response error code. For example:
data-remote-error-400="Message 1" data-remote-error-401="Message 2"
