### ISSUE TITLE
Link several elements

### ISSUE THREAD

**Issue by roipoussiere** [1000hz/bootstrap-validator#189]
I have 2 inline numbers input, in a single `form-group`. The error message is displayed under the line if one of the two number is out of bounds:

```html
<div class="form-group">
	<div> <label class="control-label" for="drawing-width">Drawing size</label> </div>
	<div class="input-group">
		<input id="drawing-width" type="number" disabled class="form-control">
	</div>
	<span class="input-group-separator"> x </span>
	<div class="input-group">
		<input id="drawing-height" type="number" disabled class="form-control">
	</div>
	<span class="help-block">Width and height of the drawing.</span>
	<div class="help-block with-errors"></div>
</div>
```

The problem is:
- When I fill the first element with a wrong value,
- then I focus the second element with a good value,
- then I focus out the second element,

... the error message for the first element disappear.

To prevent this, I have to trigger the second element when focus out the first, and vice-versa:

```javascript
$('#drawing-width').on('focusout', function() {
	$('#drawing-height').trigger('input');
});
$('#drawing-height').on('focusout', function() {
	$('#drawing-width').trigger('input');
});
```
Note than I trigger `input` event and not `focusout` event to prevent recursive errors.

Maybe this trick should be implemented in the validator ?

**Comment by 1000hz** [comment]
Each input needs to be in their own `.form-group` container. You can nest `.form-group`s within another `.form-group` if needed.
