### ISSUE TITLE
Changing the color of required elements

### ISSUE THREAD

**Issue by papakonstantinouko** [1000hz/bootstrap-validator#191]
Hello, the color used on the required elements is #a94442, not red. How can I change it to red? I attach an image for you to see the difference. The error message is in red (after I changed the color on the element), the border of the input has that weird red color.

![error](https://cloud.githubusercontent.com/assets/4752620/9577179/6d8090ce-4fd6-11e5-9c29-a1f16211bb01.PNG)

**Comment by 1000hz** [comment]
You need to override border-color on `.has-error .form-control`. This is coming from Bootstrap.
