### ISSUE TITLE
How to submit not valid data - the "cancel" submit button?

### ISSUE THREAD

**Issue by ecomeback** [1000hz/bootstrap-validator#195]
Hi, is it possible to submit the form by different submit buttons, if the data is valid/not valid? The form data should be sent even (I use a session token) although the data is not valid, if you use the action "cancel"  button, but the data should not be sent if the action "save" button was clicked. 
Thanks in advance.

**Comment by 1000hz** [comment]
I'm not sure I understand your use case, but if you want to make the validator submit the form even when the form might be invalid, you can remove the submit handler which runs validations on submit.

```js
$('#myForm').off('submit.bs.validator')
```

**Comment by 1000hz** [comment]
closing the issue, but feel free to ask more questions here if you still need help.
