### ISSUE TITLE
Custom Validator not working

### ISSUE THREAD

**Issue by dangnelson** [1000hz/bootstrap-validator#196]
I have a if else jQuery statement that is returning a true or false, but when validating I can't even get the console logs to show up...

    $('#estimate').validator({

        custom: {
            'distance': function() { 
                if( $("#distance-group").hasClass("invalid")){
                    return false;
                    console.log("ERROR")
                }else{
                    return true;
                    console.log("NO ERROR")
                }
            }
        },
        errors: {
            'distance': "Nope"
        }
    })

**Comment by 1000hz** [comment]
You need to put `data-distance="true"` on your input you want validated. The console.logs aren't showing up because you have them after the returns.

See here:
http://jsbin.com/nuwajejinu/edit?html,js,console,output

**Comment by dangnelson** [comment]
Thanks!

**Comment by kwsim539** [comment]
Your example does not work.
