### ISSUE TITLE
Applies validator to all forms on page unintentionally

### ISSUE THREAD

**Issue by ChaseGiunta** [1000hz/bootstrap-validator#199]
Using `data-toggle="validator"` on one form, applies the bootstrap validator to all the forms on a page.

**Comment by 1000hz** [comment]
I think this issue is on your end somewhere. I can't reproduce it.

http://jsbin.com/rafapukeke/edit?html,output

**Comment by ChaseGiunta** [comment]
Apologies. This was due to an unclosed `div` nested within the first form. In case anyone runs into this, make sure all div tags within your required form are closed, or it will break the closing `</form>` detection.
