### ISSUE TITLE
Example usage of delay attribute

### ISSUE THREAD

**Issue by petjb** [1000hz/bootstrap-validator#203]
Hi guys - great plugin, I'm finding it really useful. However I'm having trouble getting the delay attribute to work - this is for an email address field, and I don't want the form to throw an error when someone is still typing in their email address.

I've tried this:

<input value="" id="email" name="email" type="email" class="form-control input-md" data-error="Please enter your email address" data-delay="5000" required>

...but clearly that's not the way to do it, as that doesn't seem to change the default 500ms timeout.

I'd really appreciate some advice on how to get this working, either at the HTML level on the field, or via Javascript.

Cheers!

**Comment by 1000hz** [comment]
Looks like your code sample got stripped or something, but you wanna do either `<form data-toggle="validator" data-delay="1500">` if you're using the data API to initialize the plugin via markup, or `$('#myForm').validator({delay: 1500})` if you're initializing it via js.

**Comment by petjb** [comment]
Brilliant, thanks Cina. I was trying to assign the data-delay to the form field, not the form. Thanks again! :)

**Comment by migee** [comment]
Had same issue, thought the docs were referring to the field :)

**Comment by streetcoder** [comment]
I do not find any difference between data-delay="1500" and default delay time.
