### ISSUE TITLE
how to validate one element inside form? + How to delay custom validation

### ISSUE THREAD

**Issue by VinzzB** [1000hz/bootstrap-validator#205]
Hello,

Is i possible to (re-)validate one (or more) specific element(s) inside a form with multiple input elements?
The only option i found in the documentation validates the whole form.

Next:
It seems that the delay option is not working on custom validation methods? Custom validators are called immediately when the user starts typing. (or when input changes). Is it possible to delay this?

Greetz, Vinzz

**Comment by 1000hz** [comment]
You can trigger an input element on a field to force a validation.

`$('#myField').trigger('input')`

About the delay on custom validators: it works as it should. Here's a test case.
http://jsbin.com/zorimuseye/edit?html,js,output

**Comment by VinzzB** [comment]
Thanks for the validation trigger!

The delay works, but i thought it was working the same way as the autocomplete from jQuery Ui. jQuery Ui resets the timer when a keystroke was pressed within the timer time-out time, resulting in less ajax calls. A call is made only when the user stops typing for x ms. (= the delay)

**Comment by VinzzB** [comment]
okay, i figured it out:
The custom validator is called immediately and multiple times, only the error response is delayed!
You can check this by adding a console.log('called!'); in your custom validator.

```javascript
$('#myForm').validator({
  custom: {
    customvalidator: function ($el) {
      console.log("called!");
      return false      
    }
  },
  errors: {
    customvalidator: "This error should have been delayed by 3 seconds"
  }
})
```

**Comment by 1000hz** [comment]
Yeah, that's how all the validators work. It's by design so that if the field becomes valid, the error message is immediately cleared. That's what the "Patient to inform user of errors and eager to let them know the errors have been resolved" feature bullet point in the readme is about.

**Comment by VinzzB** [comment]
ok, That makes sense :-)  thanks for the info (and fast response!) 

I'm using this validator in combination with jQuery UI autocomplete fields, The autocomplete will load a list (from ajax) when the user stops typing (delay 500ms) (or when typing slowly :-) ) But the list is never retrieved when typing fast and directly going to an other field. So, i thought i could intercept this by the validator. (field must be validated!)

This is how my autocomplete works: (example street)
1. create autocomplete object on field $().autocomplete()
2. user types in a street and a list of suggestions (max 10) are retrieved from server and stored in a Js var array. (all handled by the autocomplete widget)
3. Custom Validator checks if value is in local Js Array. If so, then it's validated. If not, then retrieve list with suggestions from server, store list locally and validate again. But my current custom validator script makes to many ajax calls. 
The only option i see here is making a timer inside the custom validator which triggers the custom-validator again after a specified time-out time .(which could result in an infinite loop?).
Or i can just (re-)validate when the focus is lost on that field. Which isn't very good. An error message will be visible when focused and correct input was entered.

Do you see an other alternative to solve this?

btw, i know there is an ajax validator built-in, but it does not fit my requirements (when used with autocomplete)

I've also forked this project and added support for jQuery UI SelectMenu. Other jQ-UI options will be added later on.
