### ISSUE TITLE
data-disable="false" is not working for the button with type submit 

### ISSUE THREAD

**Issue by rsmmukesh** [1000hz/bootstrap-validator#207]
data-disable="false" is not working for the button with type submit .. now it is always disabled   .......

< button id="btnLogin"  type="submit" data-disable="false" name="btnLogin" class="btn btn-info">Log In< / button >

**Comment by 1000hz** [comment]
The `data-disable` option goes on the `<form>` element, not the `<button>`

**Comment by rsmmukesh** [comment]
ok .. thank you... now it is working fine...
