### ISSUE TITLE
Email confirm validator does not recognize matching email addresses

### ISSUE THREAD

**Issue by polomint82** [1000hz/bootstrap-validator#208]
Also getting an invalid match on the following 

<div class="form-group">
    <input type="email" id="txtEmail" placeholder="Email Address" class="form-control" runat="server" maxlength="50" required />
    <div class="help-block with-errors"></div>
</div>

<div class="form-group">
    <input type="email" id="txtConfirmEmail" data-match="txtEmail" data-match-error="Email Addresses do not match." placeholder="Confirm Email" class="form-control" runat="server" maxlength="50" />
    <div class="help-block with-errors"></div>
</div>

**Comment by 1000hz** [comment]
Please provide more info

**Comment by 1000hz** [comment]
Ah, github was hiding your code example because you didn't put it in code backticks. I've edited your post.

You need to provide a jQuery selector to `data-match` so you need `data-match="#txtEmail"`

**Comment by polomint82** [comment]
Apologies for the incorrect post. I removed the "#" in my code sample in a last ditch effort to get it working. Even with the "#txtEmail" it still doesn't recognize the match.

thanks for you quick response btw.

**Comment by 1000hz** [comment]
Seems to be working...

http://jsbin.com/satonovuho/edit?html,output

**Comment by polomint82** [comment]
Yeah, I suspect it's something to do with asp.net appending the control id's of parent containers. When I look at the rendered versions of the control they txtemail is now "cph_main_txtemail". That's where I'll focus my efforts. Thanks again.
