### ISSUE TITLE
not working with mvc4

### ISSUE THREAD

**Issue by nasirkZai** [1000hz/bootstrap-validator#209]
I used boostrap validation in static html page is awesome tool. you guys done a great job . but validation is not working with mvc without any error on firebug .
 i am using following file  for css
```
<link rel="stylesheet" href="/Content/css/jquery-ui.css">
<link rel="stylesheet" href="/Content/site.css">
<link rel="stylesheet" href="/Content/css/bootstrap.css">
<link rel="stylesheet" href="/Content/css/font-awesome.css">
<link rel="stylesheet" href="/Content/css/style.css">
<script src="/Scripts/modernizr-2.5.3.js">
```
my jquery files are 
![untitled](https://cloud.githubusercontent.com/assets/8584014/10243860/06413104-6915-11e5-8e19-7b016ee4636f.png)
```
<script src="/Scripts/jquery-2.1.4.js">
<script src="/Scripts/bootstrap.js">
<script src="/Scripts/validator.js">
<script src="/Scripts/appCustom.js">
```
why Validation is not working ?? does validator.js has any conflict??

**Comment by 1000hz** [comment]
I'd need more information to help you out, but this seems like more of a question for StackOverflow since it's not an issue with the plugin itself.
