### ISSUE TITLE
custom validators and not-required fields

### ISSUE THREAD

**Issue by watery** [1000hz/bootstrap-validator#214]
I've added a custom validator to an `<input type="text />` field in a form, but although the field is not required, if there's no text in it the validation fails because the custom validator is invoked anyway.

Since that custom validator could be reused elsewhere, I shouldn't adapt its code to this specific situation.
Instead, I think the validation should skip the custom validator when the field is not required, or at least offer some way to, i.e., mark a custom validator as optional.

**Comment by exodus4d** [comment]
I have some problems with this fix :(

I have a custom validator to an `<input type="text />`, too. But my custom function validates this field as `true` if some **other** form fields are filled as well.
It is a "captcha" input field, which should be required (not empty) in case some other fields are filled.

Now my custom function is not called anymore if its field is empty or the last character in this field is deleted.

**Comment by dotnetron** [comment]
I am having the same problem as exodus4d above. I have a custom validation function that only designates a field as required if another field is filled out with a certain value. Now my custom validation function is not getting invoked when the field is empty.

**Comment by ajmueller** [comment]
@exodus4d @dotnetron @1000hz with the latest release I've found that I can remove this additional line added in ab026120349440de49935dd847cee6c2c894865a and custom validations similar to the ones you describe, plus the standard ones, work as expected.  I believe other changes made in recent releases related to custom validators has alleviated the need for this line (e.g. custom validators no longer execute on non-required fields when the field is empty).
