### ISSUE TITLE
select2 multiple not validating

### ISSUE THREAD

**Issue by carborgar** [1000hz/bootstrap-validator#215]
Hi,

I've problems with a select2 (http://select2.github.io/) multiple validation. When I use a single select2 (only one option), validator works, but seem not to be working when multiple.

![screenshot](https://cloud.githubusercontent.com/assets/15002035/10412738/b3fcb81a-6f8f-11e5-8ece-832b73fcc3cc.PNG)

All in the picture are required fields. "Clientes" and "Contrarios" are mutiple.

Has anybody the same problem?

**Comment by daftt** [comment]
Same here

**Comment by 1000hz** [comment]
This issue tracker is not meant to be a support forum. Since this isn't detailing a bug with the plugin, this sounds like a question best suited for StackOverflow.

**Comment by moebaca** [comment]
Anyone ever determine a fix for this? Select2 single works, whereas multiple shows briefly before being removed. Going to ditch this otherwise excellent plugin if I can't figure out a solution.

**Comment by array81** [comment]
Has anyone managed to solve the problem?

**Comment by jerza90** [comment]
I have this problem too.
