### ISSUE TITLE
match not working on non-required fields when one field is empty + fix

### ISSUE THREAD

**Issue by VinzzB** [1000hz/bootstrap-validator#218]
Hi,

I just discovered a little bug in your script when using the data-match attribute without the 'required' attribute.
The validator will successfully validate both fields when the field being validated is kept empty, while the field being matched is filled in.

I solved this by changing the validator expression on line 87:

FROM:
```javascript
return !$el.val() || $el.val() === $(target).val()
```

TO:
```javascript
return  (!$(target).val() && !$el.val()) ||  $el.val() === $(target).val()  
```

**Comment by 1000hz** [comment]
Thanks for the report. I'm planning on fixing this generically for all validators soon, so the validators won't need to check for empty states themselves / you won't need to handle it in custom validators.

**Comment by 1000hz** [comment]
This was done in ab026120

**Comment by Dannyson** [comment]
Again in version 0.11.8 data-match validate only if marked as required.

**Comment by 1000hz** [comment]
@Dannyson if the field isn't required, then it will only validate if the field has a value.

It's working as expected in this JSBin example. If the second field has a value, it will show an error unless it matches the first input.
http://jsbin.com/dusozafiqi/edit?html,css,js,output

**Comment by Dannyson** [comment]
@1000hz Sorry I misunderstood the logic. I tought that if I have an optional field but want it to be confirmed, I could use data-match without required so when the first value is empty it wont require me to fill the confirm value and when the first value is filled, the confirm input will be required for confirmation. For this case I assume that I have to write my own validator.
