### ISSUE TITLE
disabled class removed when form is contained in a Bootstrap modal

### ISSUE THREAD

**Issue by tphbtd** [1000hz/bootstrap-validator#220]
This happens with a fresh form, not filled out. Even if you explicitly add `.disabled` to the submit button, it gets removed (by Bootstrap?) when you have a form contained in a modal. If you simply remove `.modal` and `.fade` (to make it no longer recognized as a modal component) the behavior is as expected. That is, the submit button is disabled when you load the page.

Tested with Bootstrap 3.3.5 and 0.9.0 Validator.

The contents of the modal:

    <div class="modal fade" id="test-modal">
      <div class="modal-dialog">
        <div class="modal-content">
          <form method="post" action="SERVICE_URL" data-toggle="validator">
            <div class="modal-header">
              <button class="close" data-dismiss="modal" type="button">&times;</button>
              <h4 class="modal-title">The title here</h4>
            </div>
            <div class="modal-body">
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro aliquid necessitatibus quam nihil iure itaque a.</p>
              <div class="form-group">
                <label for="contact-email">Email</label>
                <input class="form-control" name="contact-email" type="email" required>
              </div>
              <div class="form-group">
                <label for="contact-name">Name</label>
                <input class="form-control" name="contact-name" type="text" data-minlength="2" required>
              </div>
              <div class="form-group">
                <label for="contact-message">Message</label>
                <textarea class="form-control" name="contact-message" rows="2" data-minlength="4" required></textarea>
              </div>
            </div>
            <div class="modal-footer">
              <button class="btn btn-link" data-dismiss="modal" type="button">Cancel</button>
              <button class="btn btn-primary " type="submit">Send</button>
            </div>
          </form>
        </div>
      </div>
    </div>

**Comment by 1000hz** [comment]
The validator ignores invisible fields when it runs the validation functions, and when you instantiate the validator on your form, all of the fields are hidden because the modal is closed.

You need to instantiate the validator on modal shown/hidden

```js
$('#test-modal')
  .on('shown.bs.validator', function (e) {
    $('#myForm').validator()
  })
  .on('hidden.bs.validator', function (e) {
    $('#myForm').validator('destroy')
  })
  ```

http://jsbin.com/qibifukeqi/1/edit?html,js,output
