### ISSUE TITLE
Custom error message for required fields

### ISSUE THREAD

**Issue by liamwooding** [1000hz/bootstrap-validator#222]
Hi, is there a way to define a custom error message for when a required field is empty?  The default "Please fill out this field" is fine in Chrome & Firefox, but in Safari it just says "value missing", which I'd like to change to something more customer-friendly. Is there a way to do this without defining a custom validator?

**Comment by 1000hz** [comment]
At the moment, your only option is to set `data-native-error` on your field to the message, but keep in mind that if you have other built-in validators (like `type="email"` or `pattern`) their error messages will be overtaken as well.

This is something I'll address in the next version with the approach in #218.

**Comment by liamwooding** [comment]
Great to hear, thanks!

**Comment by rosesonfire** [comment]
Please do that !
