### ISSUE TITLE
How should you deal with nested input within a single form-group?

### ISSUE THREAD

**Issue by larkspurcottage** [1000hz/bootstrap-validator#224]
The help-block gets incorrectly updated with multiple inputs within a form-group

for example

      <div class="form-group has-feedback">
        <label for="resourcefile-1" class="col-sm-2 col-xs-2 control-label">File</label>
        <div class="col-sm-6 col-xs-6">
           <input class="form-control" id="resourcefile-1" type="file" name="resourcefile-1" required>
       	   <span class="glyphicon form-control-feedback" aria-hidden="true"></span><div class="help-block with-errors"></div>
        </div>
        <div class="col-sm-3 col-xs-3">
			<select name="resourceactivity-1" class="form-control" required>
            	               <option value="">Some Option</option>
            </select>
        <div class="help-block with-errors"></div>
        </div>
      </div>

**Comment by 1000hz** [comment]
You can put nested `form-group` classes on both of your column divs.
