### ISSUE TITLE
Override defaults

### ISSUE THREAD

**Issue by lcguida** [1000hz/bootstrap-validator#226]
I would like to internationalize my application using this plugin. 

Is there a way to override the defaults so I can internationalize all error messages?

**Comment by 1000hz** [comment]
Yup, use the `errors` option to specify your error messages.

**Comment by lcguida** [comment]
That part I understood. What I'm asking, how to make it default?

For example, I would like to all match error to be "should match". So instead of doing this:

```javascript
$("#myForm").validator({errors: {match: "should match}});
```
for each validator, how do I make default to all?

**Comment by 1000hz** [comment]
Oh, I see.

You can override `$.fn.validator.Constructor.DEFAULTS.errors`

**Comment by lcguida** [comment]
Ah, ok. Thanks. =)

**Comment by yogeshsaroya** [comment]
Hi @lcguida  can you please tell me how to override "$.fn.validator.Constructor.DEFAULTS.errors" ?

**Comment by lcguida** [comment]
Just pass the Hash: 

```javascript
$.fn.validator.Constructor.DEFAULTS.errors = {
  match: "My match message", 
  minlength: "My minlength message"
}
```
