### ISSUE TITLE
Character "D" is not allowed

### ISSUE THREAD

**Issue by Nadareh** [1000hz/bootstrap-validator#227]
Hi am wondering why letter "D" is not accepting as character? I only want an alphabet letters. This is the pattern:
```html
<input type="text" class="form-control" id="Nationality" placeholder="Nationality" data-error="Special charecter/number is not allowed" pattern="^[A-z]{1,}$" name="nationality" required>
```
Thanks :)

**Comment by 1000hz** [comment]
you can't use `^` and `$` with the `pattern` attribute since they are automatically applied.

use `pattern="[A-z]+"`
