### ISSUE TITLE
Validator is not autoloaded when you lazy load the plugin

### ISSUE THREAD

**Issue by wachri** [1000hz/bootstrap-validator#228]
When you use the validator in an AMD (e.g. requirejs) environment and you are loading the script after the window fired the 'load" event the validator doesn't get autoloaded.

I changed ```$(window).on('load', function () {``` to 
```$(window).load(function () ``` and fixed the issue.

**Comment by 1000hz** [comment]
I think you might have just been getting lucky that the change you made fixed the issue. `$.fn.load()` is a shortcut for `$.fn.on('load')`. See http://api.jquery.com/load-event

In AMD environments, I'd recommend initializing your validators manually via JS.
