### ISSUE TITLE
Validator conflicts with datepicker

### ISSUE THREAD

**Issue by mmguide2003** [1000hz/bootstrap-validator#231]
Validator won't accept the value of a datepicker field as input.

**Comment by 1000hz** [comment]
Please give more details.

**Comment by mmguide2003** [comment]
Hi,
I'm using http://www.eyecon.ro/bootstrap-datepicker/  for a date to and form field:
    <div class="form-inline">
 <input class="form-control" id="dpd1" placeholder="Course Start date" name="start_date" type="text" value=""> to 
<input class="form-control" id="dpd2" placeholder="Course End date" name="end_date" type="text" value="">
</div>

The parameters are as follows:
    $(function() {
    var nowTemp = new Date();
    var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);
    var checkin = $('#dpd1').datepicker({
    onRender: function(date) {
    return date.valueOf() < now.valueOf() ? 'disabled' : '';
    }
    }).on('changeDate', function(ev) {
    if (ev.date.valueOf() > checkout.date.valueOf()) {
    var newDate = new Date(ev.date)
    newDate.setDate(newDate.getDate() + 1);
    checkout.setValue(newDate);
    }
    checkin.hide();
    $('#dpd2')[0].focus();
    }).data('datepicker');
    var checkout = $('#dpd2').datepicker({
        onRender: function(date) {
            return date.valueOf() <= checkin.date.valueOf() ? 'disabled' : '';
        }
    }).on('changeDate', function(ev) {
        checkout.hide();
        $('input[type="submit"]').removeAttr('disabled'); 
    }).data('datepicker');
});  

However, I cannot proceed with submission because the validate.js is not accepting the dates as completed.  Any ideas?

**Comment by 1000hz** [comment]
The validator shouldn't be complaining about anything because those inputs don't have any validation attributes on them. Are you sure this example matches what you have in your code?

**Comment by mmguide2003** [comment]
Sorry I removed the validation off them because they weren't working. Assume they have required written on them.

**Comment by 1000hz** [comment]
Can you put your whole form markup here? I've already included the validator and datepicker scripts.

http://jsbin.com/girizecucu/edit?html,css,js,output

**Comment by mmguide2003** [comment]
Ok, I have tried this link but for some reason the calendar doesn't work, in this bin. Try using this as one page (I don't think you can use www.eyecon.ro as a cdn)
<!DOCTYPE html>
<html>
<head>

<link href="http://getbootstrap.com/dist/css/bootstrap.css" rel="stylesheet" type="text/css" />
<link href="http://www.eyecon.ro/bootstrap-datepicker/css/datepicker.css" rel="stylesheet">
//REPLACE ABOVE LOCALLY
  <meta charset="utf-8">
  <title>JS Bin</title>
</head>
<body>
<form method="POST" action="" accept-charset="UTF-8" data-toggle="validator" enctype="multipart/form-data">

<div class="form-group">
<label for="title">Title</label>
<input class="form-control" placeholder="Please insert title here..." required="required" name="title" type="text" value="" id="title">
</div>
 <div class="form-group">
<label for="start_date">Dates</label>
 <div class="form-inline">
 <input class="form-control" id="dpd1" placeholder="Course Start date" required="required" name="start_date" type="text" value=""> to 
<input class="form-control" id="dpd2" placeholder="Course End date" required="required" name="end_date" type="text" value="">
</div>

</div> 
<div class="form-group">
 <input class="btn btn-lg btn-primary btn-block" type="submit" value="Create Course">
  </div>
 </form>
</body>
<script src="http://code.jquery.com/jquery.min.js"></script>
<script src="http://getbootstrap.com/dist/js/bootstrap.js"></script>
<script src="http://1000hz.github.io/bootstrap-validator/dist/validator.min.js"></script>
<script src="http://www.eyecon.ro/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
//REPLACE ABOVE LOCALLY 
<script>
 $(function() {
    var nowTemp = new Date();
    var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);
    var checkin = $('#dpd1').datepicker({
      onRender: function(date) {
       return date.valueOf() < now.valueOf() ? 'disabled' : '';
      }
    })
    .on('changeDate', function(ev){
      if (ev.date.valueOf() > checkout.date.valueOf()) {
        var newDate = new Date(ev.date);
        newDate.setDate(newDate.getDate() + 1);
        checkout.setValue(newDate);
      }checkin.hide();
      $('#dpd2')[0].focus();
    })
    .data('datepicker');
    var checkout = $('#dpd2').datepicker({
        onRender: function(date) {
            return date.valueOf() <= checkin.date.valueOf() ? 'disabled' : '';
        }
    }).on('changeDate', function(ev) {
        checkout.hide();
        //$('input[type="submit"]').removeAttr('disabled'); 
    }).data('datepicker');
});  
  </script>
</html>

You may need to download the datepicker.

**Comment by rya88cla** [comment]
the date picker I am using triggers after the validator has already detected the field is empty and I get an error even though the field is valid. Anyway to fix?

**Comment by 1000hz** [comment]
At this point, I'd say your best bet is to ask this question StackOverflow. I'd like to get away from the habit of using the issue tracker as a support forum for integrating with other third-party libraries as it makes it hard to focus on bugs in the plugin itself.
