### ISSUE TITLE
Changing Textarea Contents Using jQuery Breaks After Field is Invalid

### ISSUE THREAD

**Issue by mkoch227** [1000hz/bootstrap-validator#232]
When the page is first loaded, contents in a textfield can be modified with jQuery such as `$('#myTextarea').html(htmlContents)`.  However, if the field ever becomes invalid, I am unable to modify the message box contents with jQuery until the page is reloaded. See http://jsbin.com/kovuqujegi/edit?html,css,js,output for a JSBin (I noticed I had to select the frame in Chrome Dev tools to execute JavaScript in the output frame).  Steps to reproduce:

1. Load the JSBin, and execute some JavaScript.  The contents of the textarea should be modifiable.
2. Clear out the textarea so the validator properly validates the textfield
3. Try to change the textarea contents using JavaScript. The actual contents won't be updated on-screen, however the console appears to have the updated contents.

**Comment by 1000hz** [comment]
With jQuery, you have to use `$el.val()` instead of `$el.html`. And then if you want to alert the validator that something has changed and it needs to revalidate, `$el.trigger('input')`.
