### ISSUE TITLE
How to override Default error message 

### ISSUE THREAD

**Issue by yogeshsaroya** [1000hz/bootstrap-validator#233]
Hi 
I want to override Default error message (in diffrent language) for text,select,email,tel etc fields. 

eg "    Please select an item in the list."  to something else, or with other language.  

data-error : its for custome error message, but i want to override default message. 

Thanks

**Comment by 1000hz** [comment]
See #226

**Comment by yogeshsaroya** [comment]
@1000hz  No, actully i want to make some changes based on some conditions.

eg if user has selected "chinese" language then i want to show all default error message in "chinese" language. so i wan to override error message run time  (using .PO file )  .

**Comment by 1000hz** [comment]
You can do that at runtime. Just write a function that sets the default error messages accordingly.

**Comment by yogeshsaroya** [comment]
Yes, but i have no idea where default message are defined.

**Comment by 1000hz** [comment]
From #226:

>You can override `$.fn.validator.Constructor.DEFAULTS.errors`
