### ISSUE TITLE
Running slowly when the form is large?

### ISSUE THREAD

**Issue by littlee** [1000hz/bootstrap-validator#234]
The form in my webpage has at least 100 `<input>`, they have different validate rules, when submit the form, the page will be frozen for a while.

**Comment by ubifWebNinja** [comment]
Mine has 7 and it takes 2 minutes to process. No rules, no options just the core initialization

**Comment by kevinweaver** [comment]
Same issue, using all defaults.  I have one form with about 40 inputs.  Every input now has delay between key presses and upon submission, the page freezes for about 25 seconds. 

I have another form though with about 10 inputs and it performs just fine with no lag.

**Comment by polycomxix** [comment]
Same issue!!! How can I show loading while waiting?

**Comment by ubifWebNinja** [comment]
I added a pre-loader, you can do something like the following.

`<div class="modal fade" tabindex="-1" role="dialog" data-keyboard="false"  data-backdrop="static" id="pleaseWaitDialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Processing...</h4>
            </div>
            <div class="modal-body">
                <div class="progress">
                    <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="application/javascript">
    var distroLoading;
    distroLoading = distroLoading || (function () {
        var pleaseWaitDiv = $('#pleaseWaitDialog');
        return {
            showPleaseWait: function() {
                pleaseWaitDiv.modal();
            },
            hidePleaseWait: function () {
                pleaseWaitDiv.modal('hide');
            }
        };
    })();
    $purchase.validator().on('submit', function (e) {
        if (e.isDefaultPrevented()) {
            // handle the invalid form...
        } else {
            distroLoading.showPleaseWait();
            // everything looks good!
        }
    });
</script>
`

**Comment by ubifWebNinja** [comment]
You can create a pre-loader, I did something like this.

 <div class="modal fade" tabindex="-1" role="dialog" data-keyboard="false"  data-backdrop="static" id="pleaseWaitDialog">-->





































<!-- </script>

**Comment by ubifWebNinja** [comment]
You can create a pre-loader, I did something like this.

 ```
<div class="modal fade" tabindex="-1" role="dialog" data-keyboard="false"  data-backdrop="static" id="pleaseWaitDialog">
     <div class="modal-dialog">
         <div class="modal-content">
             <div class="modal-header">
                 <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                 <h4 class="modal-title">Processing...</h4>
             </div>
             <div class="modal-body">
                 <div class="progress">
                     <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                     </div>
                 </div>
             </div>
         </div>
     </div>
 </div>

 <script type="application/javascript">
     var distroLoading;
     distroLoading = distroLoading || (function () {
             var pleaseWaitDiv = $('#pleaseWaitDialog');
             return {
                 showPleaseWait: function() {
                     pleaseWaitDiv.modal();
                 },
                 hidePleaseWait: function () {
                     pleaseWaitDiv.modal('hide');
                 }
             };
         })();
     $purchase.validator().on('submit', function (e) {
         if (e.isDefaultPrevented()) {
             // handle the invalid form...
         } else {
             distroLoading.showPleaseWait();
             // everything looks good!
         }
     });
 </script>
```

**Comment by 1000hz** [comment]
I'm trying to investigate this issue, but it seems to be running ok.
http://jsbin.com/kayifimefi/edit?html,css,js,output

Is this slow for any of you?

**Comment by tcrisafulli** [comment]
Just installed this library and it look promising but also seeing the delay.  My form is only 7 text fields.

I see default HTML 5 behavior then the expected behavior seems to transition to the field.
Also on click only the first required field is highlighted, if the others are empty they get styles applied only after setting focus.

**Comment by 1000hz** [comment]
Does the example on the docs page run slowly for anybody?

**Comment by msiewert** [comment]
The example that you posted is not slow for me.  I am however, experiencing slowness in an application I am working on.  The form has over 100 fields and the validation takes 10 seconds to finish.

**Comment by 1000hz** [comment]
Would you mind putting an example up on JSBin? I've started working on some performance increases but I can't ever get it to be slower than about a second so I can't get a good sense of how much it's improved.

**Comment by msiewert** [comment]
I have a working example, not sure how to get it working on JSBin.  Can I email it to you?

**Comment by msiewert** [comment]
https://jsbin.com/tocigo/edit?html,console,output

**Comment by msiewert** [comment]
Just some notes.  It is slowest in Chrome.  IE is better, but still not great.  Edge browser on Windows 10 seems to be fast and Firefox seems to be a bit better than IE.

I also have a modified version of the validation library where I added my own validation logic.  That version takes twice as long as this.

**Comment by 1000hz** [comment]
Cool, thanks for that. Good news:

Running with the current version of the validator, submitting the form takes about 8 seconds.
![image](https://cloud.githubusercontent.com/assets/1395018/13437328/48c33fe4-dfa9-11e5-9bd6-a51830d92b18.png)

Running with the upcoming version takes less than 500ms.
![image](https://cloud.githubusercontent.com/assets/1395018/13437364/7d9a9d16-dfa9-11e5-9f43-f9379e8cc739.png)

**Comment by msiewert** [comment]
Great, any idea when the new version will be available?

**Comment by 1000hz** [comment]
Hopefully sometime this week. I'll probably push up the branch soon so you can use it before I've officially released it.

**Comment by msiewert** [comment]
Thanks, as I mentioned I had made some customization's so I will have to tie those back in and see how things go then.  My custom validation seemed to double the time.

**Comment by 1000hz** [comment]
Wait, I spoke too soon. I just realized I had a part of the code commented out from my last debugging session, so the profile I posted above is skipping a big part of the code path. :disappointed:

I'll keep trying to get to the root of the issue.

**Comment by 1000hz** [comment]
(Got it back down to 600ms for real this time. I'll see if there's any more optimizations I can do to get it even faster)

**Comment by msiewert** [comment]
Fabulous news.

**Comment by msiewert** [comment]
When can I get the fixed version?
