### ISSUE TITLE
Can't override default glyphicon 

### ISSUE THREAD

**Issue by rarny** [1000hz/bootstrap-validator#235]
$('#input').validator({
	'feedback':{
		success: 'glyphicon-search',
  		error: 'glyphicon-remove'
	}
});
when pass validation,this input still has glyphicon-ok icon,why?

**Comment by 1000hz** [comment]
http://jsbin.com/pivagudina/edit?html,css,js,output

It works. Not sure what `#input` is in your example, but it needs to be the form element.

**Comment by fergardi** [comment]
Hello! I'm experiencing the same issue. I'm not able to override the default icons with, say, other glyphicon icons or even font-awesome icons, via the data-feedback attribute. What should I write? According to http://1000hz.github.io/bootstrap-validator/#validator-options, I'm currently using:

````
<form [...] data-toggle="validator" data-feedback="feedback: {success: 'glyphicon-firsticon', error: 'glyphicon-secondicon'}">
````

Thank you, nice plugin!

**Comment by 1000hz** [comment]
You need to initialize the plugin via js to use the `feedback` option. It won't work via the data API.

**Comment by fergardi** [comment]
Thank you for such a fast response!

I've ended modifying directly the javascript code to switch glyphicon-ok and glyphicon-error to fa-check and fa-times. Although I'ts a bad practice, seems easier and faster than switching all my forms from data-toggle to javascript initialization. Would be nice to add data-success and data-error attributes. See ya!
