### ISSUE TITLE
No installation documentation

### ISSUE THREAD

**Issue by necmettin** [1000hz/bootstrap-validator#236]
There is not documentation on GitHub README or the documentation website. Although it is very easy, it would be nice for beginners to have that documentation.

**Comment by naneri** [comment]
+

**Comment by surfer190** [comment]
@necmettin Have you added the documentation for your suggestion in a pull request?

**Comment by necmettin** [comment]
@surfer190 there are 13 pull requests not cared for, no use creating another one..

**Comment by andrea-86** [comment]
+
