### ISSUE TITLE
HTML inside data-error

### ISSUE THREAD

**Issue by therayess** [1000hz/bootstrap-validator#237]
Hi,

I'm trying to insert html inside the error messages, i insert it and i add data-html="true", but still doesn't work...any idea?

Thanks

**Comment by 1000hz** [comment]
You have to put that data attribute on the form element.

**Comment by therayess** [comment]
Yup thats what i'm doing, this is how it looks:

<input type="email" name="email" class="form-control" placeholder="Email" required data-checkemail="email"  data-error="Invalid email" data-checkemail-error="Email already registered, <a href='#'>login</a>" data-valid="Looks great" data-html="true" />

**Comment by therayess** [comment]
Yeah i did that, this is the form element:

`<input type="email" name="email" class="form-control" placeholder="Email" required data-checkemail="email"  data-error="Invalid email" data-checkemail-error="Email already registered, <a href='#'>login</a>" data-valid="Looks great" data-html="true" />`

**Comment by therayess** [comment]
ah nvm, gotcha, thanks alot :)

**Comment by sahibvirk** [comment]
Wait a minute> i have the same problem. And by reading this thread I get no idea how you solved it.

My code is:-

`<input type="password" class="form-control" id="create_admin_password" name="create_admin_password" style="padding: 6px 12px;" autocomplete="off" 
											required pattern="/^[a-zA-Z0-9!@#\$%\^\&*_=+-]{8,12}$/g"
                      data-html="true"
                      data-error="<h1>qqqqq</h1>" 
                    />
                    <div class="help-block with-errors"></div>`

What am I doing wrong?????
