### ISSUE TITLE
Is there a way to add valid field message?

### ISSUE THREAD

**Issue by therayess** [1000hz/bootstrap-validator#238]
there is data-error messages, but i couldn't find a built-in way to add a message for valid fields, is there a way?

Thanks

**Comment by 1000hz** [comment]
Not a feature supported by the plugin itself, but you might be able to do it yourself by listening for the `valid.bs.validator` event. Something like:

```js
$('#myForm').on('valid.bs.validator', function (e) {
  var $field = $(e.relatedTarget)
  var validMessage = $field.data('valid')

  if (validMessage) {
    $field.siblings('.help-block').text(validMessage)
  }
})
```

I haven't tested that, so no guarantees that it works. I probably won't be adding this as a feature though, so I'm gonna go ahead and close this ticket.
