### ISSUE TITLE
Disable Validator (temporarily)

### ISSUE THREAD

**Issue by jamesng** [1000hz/bootstrap-validator#246]
We have a multi-step web form with forward and back buttons (to page through the sections of the form)

Form submission is triggered by both buttons, however we we need to disable the validator when the back button is clicked.  Is this possible?

**Comment by 1000hz** [comment]
I'm not really sure. The only way to disable the validator is to destroy it, and then you'll need to reinitialize it.

If your back button was just a `type="button"` instead of a `type="submit"` it wouldn't trigger the validation, but there are probably reasons you have it set up that way.
