### ISSUE TITLE
Indicate required fields

### ISSUE THREAD

**Issue by mittal-sam** [1000hz/bootstrap-validator#249]
Hello,

Can there be an option to indicate "required" fields by having asterisk " * " after the associated labels of input fields. The color of this asterisk can also be configurable.

Right now the required field is indicated to the user only on form submit.

**Comment by 1000hz** [comment]
No, this isn't something the plugin should be concerned with, but you can easily do this with your own code.

```js
$('#myForm').find(':required').closest('.form-group').find('label').addClass('label-required')
```
```css
.label-required::after {
  content: "*";
  color: #f00;
}
```
