### ISSUE TITLE
strange behaviour between showErrors & clearErrors on non-native select

### ISSUE THREAD

**Issue by maximelebreton** [1000hz/bootstrap-validator#251]
Hi @1000hz, and thanks a lot for the work!

I use [Bootstrap select](http://silviomoreto.github.io/bootstrap-select/), and have a little problem.
First, i have to made this little modification (because bootstrap-select hide the native select):
```
$.fn.validator.Constructor.INPUT_SELECTOR = ':input:not([type="submit"], button):enabled'
```
And it works.

**But**, when i have errors, there is no ```.has-error``` class on the parent ```.form-group``` and no ```.help-block``` messages.
I don't understand because the markup is in the right place:
![image](https://cloud.githubusercontent.com/assets/1072425/11816594/719ee6fa-a351-11e5-9402-5111f557a893.png)

And in the  ```Validator.prototype.showErrors``` function, the variables ```$group, $block``` and ```errors``` are **good**.

So the problem seems to be in ```Validator.prototype.clearErrors``` function, who's called at the same time !?

If i comment the code:
![image](https://cloud.githubusercontent.com/assets/1072425/11816538/1f97b684-a351-11e5-81ac-a2dae54d36cd.png)

it works...
![image](https://cloud.githubusercontent.com/assets/1072425/11816582/5a765698-a351-11e5-85a9-dc596db61f96.png)

Any idea? 

Thanks!

-----------

**EDIT 1:**
-----

i've made a JSBin, and it's working with one element.
http://jsbin.com/qorinewoyi/edit?html,output

--------
**EDIT 2:**
====

Ok, i have reproduced the problem, it's when you have more than one element, it keep only the last one:
(and if I comment the ```clearErrors``` function, this behaviour disapear)
http://jsbin.com/javihugewa/edit?html,output

any idea of how to fix this?

**Comment by maximelebreton** [comment]
okay, #112 fix that case.
thanks @r0ro for your pull request!
@1000hz can you merge it?

**Comment by 1000hz** [comment]
It looks like the button bootstrap-select added triggers a focusout event which causes a revalidation and clears the error. I'll fix this in the next version so that the event handlers are scoped only to events from `INPUT_SELECTOR` elements.
