### ISSUE TITLE
How to NOT show glyphicon-ok if field is left empty?

### ISSUE THREAD

**Issue by MXTcomunica** [1000hz/bootstrap-validator#252]
Hi,

I have a "tel" input filter that is **NOT mandatory**, but can accept only digit, so:

```
<div class="form-group has-feedback">
      <label for="phone">Phone number</label>
      <input type="tel" pattern="^\d+$" class="form-control" id="phone" maxlength="11" data-error="Only numbers allowed">
      <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
      <span class="help-block with-errors"></span>
</div>
```
The above code works right triggering error if value isn't a digit, and validating it if values are only digits.

The problem is this: if user focus on the field but leaves it empty, field is considered valid and icon "glyphicon-ok" is shown.

The desired behaviour is that "glyphicon-ok" should be shown only if field had focus AND user fill it with digits.

I tried to intercept the event like this:

```
$('form').on('validate.bs.validator', function (event) {
    element = event.relatedTarget;
    if (element.id == 'phone' && element.value == '') {
      // WHAT TO DO HERE TO PREVENT VALIDATION (and so to not show glyphicon-ok)
    }
  })
```

But I don't know how to proceed to reach the goal (read comment in code please)

Thank you very much for any help

**Comment by MXTcomunica** [comment]
Sorry, I've just discovered that return FALSE resolves the issue:
```
$('form').on('validate.bs.validator', function (event) {
    element = event.relatedTarget;
    if (element.id == 'phone' && element.value == '') {
      return FALSE;
    }
  })
```

**Comment by 7rust** [comment]
Use the Validators's data-attribute: **data-minlength="1"**. This forces the user to input at least one char or number. (Maxlength is also available and looks like: data-maxlength="30")

```<input type="tel" data-minlength="1" maxlength="30" .../>```

**Comment by MXTcomunica** [comment]
Thank you 7rust for your suggestion that certainly improves things, but the glyphicon-ok is always exposed also if the field is left empty.

Best workaround I've found to resolve definitively is the following:

```javascript
  $('form').on('validated.bs.validator', function (event) {
    var element = event.relatedTarget;
    if (element.id === 'phone' && element.value === '') {
      $(element).next('.glyphicon').removeClass('glyphicon-ok glyphicon-remove');
      $(element).nextAll('.help-block').html('');
      $(element).parent('.form-group').removeClass('has-success has-error');
    }
  });
```

**Comment by 1000hz** [comment]
I think it makes sense to add a check to only show the success icon if the field has a value.
