### ISSUE TITLE
Forbid Select-options that contain the disabled class

### ISSUE THREAD

**Issue by 7rust** [1000hz/bootstrap-validator#256]
A lot *Select* elements contain an item that has the *disabled* and *selected* attributes set by default. Most of the time this item behaves like a placeholder for the select form. The validation should return false if an item is selected that contains the *disabled* attribute because it can't be selected anyway. See:

```
<select data-error="Please chose at least on option">
    <option value="abc" disabled selected>Placeholder (this is the default value and can not be selected)</option>
    <option value="xyz">First option</option>
</select>
```

**Comment by 1000hz** [comment]
You probably shouldn't be giving the placeholder option a `value` attribute.
