### ISSUE TITLE
Custom validator called multiple times

### ISSUE THREAD

**Issue by socalengineer2** [1000hz/bootstrap-validator#258]
The custom validator is called multiple times, see this jsfiddle:
https://jsfiddle.net/a5ocn93c/11/

When I use firefox, and I type in "fff"-- the validator alert is called three times on the input instead of just once. Why is that? I am going to debug it.

**Comment by socalengineer2** [comment]
Hmmmm, I see now from another issue this is by design:
https://github.com/1000hz/bootstrap-validator/issues/205

**Comment by 1000hz** [comment]
In the next version it's gonna check to see if the value of the input has changed since the last time the validator was run and bail early if not.
