### ISSUE TITLE
How to trigger a error message for a particular field?

### ISSUE THREAD

**Issue by rsmmukesh** [1000hz/bootstrap-validator#259]
suppose a form have 5 fields... i want to trigger a validation error with custom message for a particular field. is it possible? please give me the code

**Comment by 1000hz** [comment]
http://jsbin.com/wavodepuni/edit?html,js,output

**Comment by rsmmukesh** [comment]
Sorry... i will explain clearly.
                               I have a sign up form and it has a field txtSignUpUsername, in the blur of txtSignUpUsername im checking whether the username is already exist or not. if exist i need to trigger a error only for the field txtSignUpUsername, "user name already exist please choose another user name".

My script is


<script>
	
		var $txtUserName="";
	
	// prepare the form when the DOM is ready 
$(document).ready(function() { 

$txtUserName=$("#txtSignUpUsername");
	
	$txtUserName.on("blur",function()
	{
		
		CheckUserName();
	});
	
});



function CheckUserName()
{
	
	var userNameEntered=$txtUserName.val();
	if($.trim(userNameEntered)!="")
	{
		
				$.ajax({
							  type: "POST",
							  url: "actions/checkusername.php",
							  dataType: "json",
							  data: { username:userNameEntered },
							  success: function(data) {
								if(data.result=="no")
{
//raise error for username field only
}
							  },
							  error:function(data)
							  {
								  alert("error");
							  }
		});
	}
}

</script>

My form is

                            <form id="frmSignUp" class="form-horizontal mw-form" data-toggle="validator" data-disable="false">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="mw-sideHead">
                                            Sign Up
                      
                                        </div>
                                    </div>
                                </div>


                                
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="textinput">Full Name</label>

                                        <input id="txtSignUpName" name="textinput" placeholder="Full Name" class="form-control" type="text" required="" data-error="Full name required" maxlength="50">
                                        <p class="help-block with-errors"></p>

                                    </div>
                                </div>

                                


                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="textinput">Username</label>

                                        <input id="txtSignUpUsername" name="textinput" placeholder="Username" class=" form-control" type="text" required="" data-error="Username required" maxlength="30">
                                        <p class="help-block with-errors">
                                        </p>

                                    </div>
                                </div>
                                

                                <div class="form-group">

                                    <div class="col-md-12">
                                        <label class="control-label" for="textinput">Email ID</label>

                                        <input id="txtSignUpEmailID" name="textinput" placeholder="Email ID" class=" form-control" type="text" required="" data-error="Email id required" maxlength="100" >
                                        <p class="help-block with-errors"></p>

                                    </div>
                                </div>
                                

                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="textinput">Password</label>

                                        <input id="txtSignUpPassword" name="" placeholder="Password" class="form-control" type="password" required="" data-error="Password required" maxlength="20">
                                        <p class="help-block with-errors"></p>

                                    </div>
                                </div>
                                

                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="textinput">Confirm Password</label>

                                        <input id="txtSignUpConfirmPassword" name="textinput" placeholder="Confirm Password" class=" form-control" type="password" data-match="#txtSignUpPassword" data-match-error="Password does not match !" required="" data-error="Confirm password required" maxlength="20">
                                        <p class="help-block with-errors"></p>

                                    </div>
                                </div>

                                <br />


                                
                                <div class="form-group">

                                    <div class="col-md-12">
                                        <button id="btnSubmitSignUp" type="submit" name="singlebutton" class="btn btn-info pull-right">Sign Up</button>
                                    </div>
                                </div>
                            </form>
                        


I hope you understood my requirement? and tell me the solution

**Comment by TheDagger** [comment]
I have this same issue how is this done? Showing example here, https://stackoverflow.com/questions/44359891/trigger-error-manually-on-a-field-with-1000hz-bootstrap-validator
