### ISSUE TITLE
Receive form validation status, true or false

### ISSUE THREAD

**Issue by daybaryour** [1000hz/bootstrap-validator#260]
Hi Great job with the validator plugin, i want to get the value of a form, see if it validated successfully or not, was trying to use the errorList but it only works in certain scenarios

**Comment by 1000hz** [comment]
You can check if any of your form groups have the `has-error` class.
```js
var isValid = !$('#yourForm .has-error').length
```

I'm thinking about adding a `has-error` class to the form element if any of its fields have an error in a future version.
