### ISSUE TITLE
Resetting form doesn't clear validation Messages [success and Failure]

### ISSUE THREAD

**Issue by KarthikTv** [1000hz/bootstrap-validator#262]
Hi ,
I'm using this v-0.9.0 version of Validator.js,

I used below code, 
`$('#frmNew').data('formValidation').resetForm();`

_When i use resetForm getting below error,_

Please correct me if i used wrongly

> Uncaught TypeError: Cannot read property 'resetForm()' of undefined.

**Comment by 1000hz** [comment]
I think you're confusing two different validator plugins. `.data('formValidation')` isn't part of this API.

**Comment by KarthikTv** [comment]
Sorry for the Confusion, May i know How to reset the form?

**Comment by 1000hz** [comment]
With this one, you'll want to destroy and reinitialize the plugin after you reset the form using the native DOM `.reset()` method.
```js
$('#frmNew')[0].reset()
$('#frmNew').validator('destroy').validator()
```
