### ISSUE TITLE
'invalid.bs.validator' event : know which custom validator failed

### ISSUE THREAD

**Issue by nosp4mSnippets** [1000hz/bootstrap-validator#264]
Hi, 

It's not a bug but a question... 

I'm trying to show dynamic error messages based on what content is currently in an input field.
By listening to the event : 'invalid.bs.validator' and looking in the event.relatedTarget.validity object  it is possible to find which field is wrong and the kind of error, as long as it doesn't come from a custom validator. 

For example if you have on the same input field, a pattern validator (Only lowercase letters) as well as a required attribute, then validity.valueMissing = true will tell me that the field is empty and so I can override the pattern message or data-error message to show something more appropriate like "This field is required" istead of "only lower case chars are allowed here !"

How could I do the same for custom validators ?

Example : <input type="file" accept=".zip" data-validfile="only zip" data-filesize="1000000" data-ext="accept">
 - If you send a file larger than 10Mb "filesize" validator will return false 
 - and if you send something else than a zip "validfile" will fire.
I'd like to dynamically customise the preset error messages for instance : 
"Sorry but 'flowers.png' doesn't seem to be a zip file" rather than "Only zip file !"

I couldn't find a correct way to determine which custom validator triggered an error except from checking the array that contains these messages in event.detail and doing a comparison on the strings... but that is quite a bad way to do it, isn't it ?

Would someone suggest a better idea or a workaround ?
Many thanks !

**Comment by devanshuGit** [comment]
Did you got the solution, how to determine which custom validator failed? Also, how to catch invalid.bs.validator for custom validator? Could you please post an example, it would be helpful?
