### ISSUE TITLE
Issue extra closed div

### ISSUE THREAD

**Issue by smgjreinieren** [1000hz/bootstrap-validator#265]
Iam working on a project which needs your awesome validator:) But there is a problem it is not working properly when i dont include the extra closed div. But this extra closed div conflicts with my code so, is there an other way to do this? So short summary when i click submit it shows me no errors, but when i include this extra closed div it will but my page is completely distorted. So thats not what i want.... 
Maybe there is an other solution?

Kind regards,

**Comment by 1000hz** [comment]
I don't know, I can't really help you. It sounds like there's a problem somewhere else on your page.
