### ISSUE TITLE
Validation in modal form

### ISSUE THREAD

**Issue by slamarca** [1000hz/bootstrap-validator#266]
Hi I have the following situation:

I have a form (bound to the validator) and one of the form's field is a calculated field linked to a modal form that asks for additiondal data to calculate the field. The modal form is bound to the validator too, and I have no issue having two forms to validate on the same page. I'd just like to trigger the first form's validation when I submit (and validate correctly) the modal form (but don't want to submit the first form). This would help to avoid having the user puzzled by having calculated the filed but seeing the file still 'red' on the original form. If I try to trigger the form validation by something like $('#formId').validator('validate') I got an error 'validator is not a function'.

Regards,
Sergio

**Comment by 1000hz** [comment]
I think this question is better suited for StackOverflow. Also, ` 'validator is not a function'` means the plugin hasn't been loaded on your page when you are making that call.
