### ISSUE TITLE
How do I use this with a multi-page form?

### ISSUE THREAD

**Issue by marvoh** [1000hz/bootstrap-validator#267]
It's fairly common to break down long forms into multiple steps. How would I use this plugin to validate each step individually?

**Comment by 1000hz** [comment]
The validator will only validate visible fields, so you can just validate the whole form at each step if you're only displaying one page at a time.

You can also set the selector used to determine which fields should be validated at
`$.fn.validator.Constructor.INPUT_SELECTOR`
