### ISSUE TITLE
Safari doesn't render the error messages

### ISSUE THREAD

**Issue by brunoDegaspare** [1000hz/bootstrap-validator#268]
If you test http://1000hz.github.io/bootstrap-validator on Safari you will notice that it doesn't render the error message for the email input. It shows a default message 'value missing'. How can I override that? The issue is on iOS only.

**Comment by 1000hz** [comment]
Works for me on iOS 9.2.1
![img_3394](https://cloud.githubusercontent.com/assets/1395018/12984921/bd0a6c54-d0b5-11e5-97bb-4bcc9f6039c7.PNG)

**Comment by brunoDegaspare** [comment]
Sorry I should have mentioned it shows the error message however it doesn't show the default error message for the email input. Is there a fix for that?

**Comment by xpuc7o** [comment]
I had the same problem on iOS 8.0.2. You can fix it by adding validation message as data attribute:

`data-required-error="This field is required."`
