### ISSUE TITLE
Question: How does disabled work?

### ISSUE THREAD

**Issue by taylorbrooks** [1000hz/bootstrap-validator#269]
If the form is invalid, does it add a `disabled` css class?

Or does it actually add a `disabled` html attribute to the button?

Reason I ask... I don't think adding the css class actually disables for the form.

**Comment by 1000hz** [comment]
The button isn't `disabled` so that the user can still _attempt_ to submit (which would reveal all of the form's errors).

**Comment by 1000hz** [comment]
Also, the css `disabled` class doesn't actually disable the form, but calling `preventDefault()` on the `submit` event effectively does.

**Comment by taylorbrooks** [comment]
Gotcha. I assumed validator was listening to `on:click` events vs. `on:submit` to validate.

This was helpful:
````javascript
$('#form').validator().on('submit', function (e) {
  if (e.isDefaultPrevented()) {
    // handle the invalid form...
  } else {
    // everything looks good!
  }
})
````
