### ISSUE TITLE
Bootstrap 4 support?

### ISSUE THREAD

**Issue by benjamij** [1000hz/bootstrap-validator#271]
Hey guys - are there any plans to support Bootstrap 4?

**Comment by 1000hz** [comment]
I think all of the form class names are the same in Bootstrap 4 so the validator should still work.

**Comment by benjamij** [comment]
They aren't - `has-error` has been dropped. Also, Bootstrap 4 no longer ships with Glyphicons. Therefore the feedback icons won't show unless the user installs Glyphicons:

```
feedback: {
      success: 'glyphicon-ok',
      error: 'glyphicon-remove'
    }
```

It would be nice if there would be a parameter for specifying success and error icons, for example.

**Comment by 1000hz** [comment]
Aw man. I guess I could also add `.has-danger` along with `.has-error` to keep both versions compatible.

I'm not sure what you're suggesting about the icons though. There already is an option to specify the icon classes that are applied.

**Comment by benjamij** [comment]
Ah, that would be cool :+1: 

Sorry about the icons - I hadn't spotted this before. Nice!!!

**Comment by yanickrochon** [comment]
This should perhaps go into a separate branch? As BS4 is still in alpha. Then set a tag for the current BS3. There is no need to have universal support to complicate source code. IMO

**Comment by 1000hz** [comment]
It's a tiny change, just adding `.has-danger` along with `.has-error`. It'd be more complicated to have to manage two versions.

**Comment by niftylettuce** [comment]
Bootstrap V4 is incompatible with `bootstrap-validator` due to <https://github.com/twbs/bootstrap/pull/19141#issuecomment-233172275>.  Please re-open until then.

**Comment by nelson6e65** [comment]
I think is no a good idea make further changes to support an alpha package... At least not yet, until v4 get stable.

**Comment by joevandyk** [comment]
Any update on this?

**Comment by 1000hz** [comment]
Bootstrap 4 is still in alpha. I'm not gonna start officially supporting it until it it's at least in beta.

**Comment by douglaspinheiro-dev** [comment]
Has the Bootstrap 4 Beta been released, any updates?

**Comment by hassanbouaakab** [comment]
Bootstrap is Currently v4.0.0-beta, any updates?

**Comment by sarfraznawaz2005** [comment]
Looking forward to this now that BS4 stable is out. Thanks

**Comment by chenjienan** [comment]
v4 is out. Waiting for the updates. :)

**Comment by vivipoit** [comment]
I'm looking forward to this as well!!

**Comment by silvinhamorais** [comment]
me too

**Comment by ghost** [comment]
So is it compatible now?

**Comment by vivipoit** [comment]
I made changes locally to get it working on my app. I'm not confident it's good enough for a PR, but it's working. Maybe someone else can tackle it?
