### ISSUE TITLE
Email validation passes invalid emails

### ISSUE THREAD

**Issue by BondITSolutions** [1000hz/bootstrap-validator#272]
Currently it is not validated whether the TLD is already typed in, for example on:
http://1000hz.github.io/bootstrap-validator/

The following e-mailadres would work:
test@test (without TLD).

**Comment by 1000hz** [comment]
The spec says that's valid. See #31

**Comment by BondITSolutions** [comment]
The spec says:
The value must follow the ABNF production: 1*( atext / "." ) "@" ldh-str 1*( "." ldh-str )

So 1 or more `atext` followed by a single `@` followed by a `ldh-str` and 1 or more `.ldh-str`. 

How would `test@test` fit that definition? The first `test` would conform to the `atext`, the `@` is obviously there, and then follows the `ldh-str`, but it lacks the 1 or more `.ldh-str` afterwards.

**Comment by 1000hz** [comment]
Yeah, I think you're right according to that spec. However, Wikipedia states that it's valid
https://en.wikipedia.org/wiki/Email_address#Valid_email_addresses

Regardless, this plugin defers to the browser's HTML5 validation API, so this is up to the browser vendors to decide.

**Comment by BondITSolutions** [comment]
Wikipedia is often enough wrong, would rather stick to a spec tbh. Regardless, I just tested the 'native' validation of Firefox, and it also accepts `test@test` as a valid e-mailaddress. So the current implementation of the validator indeed is correct (or atleast in line with how Firefox validates).

Maybe an idea to be able to configure this? Like a strict and non-strict setting which defaults to strict? I assume most developers were/are under the impression that `test@test`, for example, is invalid. Or at the very least, the majority of end-users is.

Notably, PHP also asserts it as not being a valid email address using `filter_var('test@test', FILTER_VALIDATE_EMAIL)`.

**Comment by dsikes** [comment]
How can this be? We all can reasonably agree that test@test is not a valid email address. Why do browsers allow this to pass? This makes no sense to me...

**Comment by 1000hz** [comment]
Again, it's in the spec. 

For clarification, It looks like the bit quoted above copied from MDN (via #31) is incorrect or from an old copy of the spec. It includes an erroneous `1*` instead of just `*`. Here's the section straight from final W3C spec: 
http://w3c.github.io/html/sec-forms.html#valid-e-mail-address
