### ISSUE TITLE
Running slowly when the form has many input controls

### ISSUE THREAD

**Issue by alex-training** [1000hz/bootstrap-validator#273]
When the form has many controls, for instance 10 which should be validated and 150 controls which
shouldn't  be validated then the validation engine will check every of ( 10 + 150) = 160 controls.
It takes about 5 seconds.

Could you please add a way in which we will be able to override default "INPUT_SELECTOR".
Validator.INPUT_SELECTOR = ':input:not([type="submit"], button):enabled:visible'

For the large form we will be able to mark useful controls with some css-class or etc.
Validator.INPUT_SELECTOR = ':input.useful_flag_css:not([type="submit"], button):enabled:visible'

**Comment by 1000hz** [comment]
Yup, you already can by overriding `$.fn.validator.Constructor.INPUT_SELECTOR`

**Comment by alex-training** [comment]
@1000hz Thanks!
It would be great to see such features in the manual
