### ISSUE TITLE
Doesn't work on iPhone

### ISSUE THREAD

**Issue by d3vit** [1000hz/bootstrap-validator#274]
Using the submit button won't submit the form. It's disabled even though all form items are valid.

**Comment by d3vit** [comment]
Code to reproduce:

`<form role="form" name="customer-form" id="customer-form">
                        <div class="modal-body black-font">
                            <div class="modal-body-form form-div form-signin">
                                <div class="form-group has-feedback">     
                                    <div class="input-group">         
                                        <input type="text" data-minlength="1" class="form-control top-buffer-sm" placeholder="Your name" name="cust_name" data-error="We'll need your name so we know who we're contacting" required autofocus></input>
                                    </div>
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                </div>
                                <div class="form-group has-feedback">     
                                    <div class="input-group">         
                                        <input type="email" data-minlength="1" class="form-control top-buffer-sm" placeholder="Your email address" name="cust_email" data-error="" required autofocus></input>
                                    </div>
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                </div>
                                <div class="form-group has-feedback">     
                                    <div class="input-group">         
                                        <input type="tel" data-minlength="1" class="form-control top-buffer-sm" placeholder="Your phone number" name="cust_phone" data-error="" required autofocus></input>
                                    </div>
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                </div>
                                <div class="form-group has-feedback">     
                                    <div class="input-group">         
                                        <input type="text" data-minlength="1" class="form-control top-buffer-sm" placeholder="Your company name" name="cust_company_name" data-error="" required autofocus></input>
                                    </div>
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                </div>
                                
                                <div class="form-group has-feedback hide">     
                                    <div class="input-group">         
                                        <input type="text" data-minlength="1" class="form-control top-buffer-sm" placeholder="Your email" name="email" data-error=""></input>
                                    </div>
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                </div>
                                    
                                    
                            </div>
                            
                            <input id="sendForm" type="submit" value="Send"></input>
                            
                    	</div>   
                    </form>`

**Comment by d3vit** [comment]
`form role="form" name="customer-form" method="post" id="customer-form" data-toggle="validator">
                        <div class="modal-body black-font">
                            <div class="modal-body-form form-div form-signin">
                                <div class="form-group has-feedback">     
                                    <div class="input-group">         
                                        <input type="text" data-minlength="1" class="form-control top-buffer-sm" placeholder="Your name" name="cust_name" data-error="We'll need your name so we know who we're contacting" required autofocus></input>
                                    </div>
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                </div>
                                <div class="form-group has-feedback">     
                                    <div class="input-group">         
                                        <input type="email" data-minlength="1" class="form-control top-buffer-sm" placeholder="Your email address" name="cust_email" data-error="" required autofocus></input>
                                    </div>
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                </div>
                                <div class="form-group has-feedback">     
                                    <div class="input-group">         
                                        <input type="tel" data-minlength="1" class="form-control top-buffer-sm" placeholder="Your phone number" name="cust_phone" data-error="" required autofocus></input>
                                    </div>
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                </div>
                                <div class="form-group has-feedback">     
                                    <div class="input-group">         
                                        <input type="text" data-minlength="1" class="form-control top-buffer-sm" placeholder="Your company name" name="cust_company_name" data-error="" required autofocus></input>
                                    </div>
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                </div>
                                
                                <div class="form-group hide">     
                                    <div class="input-group">         
                                        <input type="text" data-minlength="1" class="form-control top-buffer-sm" placeholder="Your email" name="email"></input>
                                    </div>
                                </div>
                                    
                                    
                            </div>
                            
                            <input id="sendForm" type="submit" value="Send"></input>
                            
                    	</div>   
                    </form>`

**Comment by 1000hz** [comment]
Worked for me when I just tested it on my phone here:
http://jsbin.com/wilucokova

My guess is you might be running into a problem because your form is within a modal. You might want to try initializing the validator via JS whenever the modal is shown instead of using `data-toggle="validator"`, like so:
```js
$('#myModal').on('shown.bs.modal', function (e) { $('#customer-form').validator() })
```
just to be sure the form is in the DOM at init.

**Comment by d3vit** [comment]
Appreciate the reply!

Was just picking through the code and comparing it to what you had and had an idea..

Turns out it was the damn z-index of the button. Changed it to _z-index: 9999_ and it worked.
