### ISSUE TITLE
Save button doesn't work on Firefox

### ISSUE THREAD

**Issue by mherb63** [1000hz/bootstrap-validator#277]
Hi, first thanks for this very nice tool.

I'm having a weird issue in that I can save my form on Chrome but on Firefox the Save button is not working even though it is active (ie, not greyed out).

Any clues on how to debug this (nothing shows now in the console)

Thanks,

Mike

**Comment by 1000hz** [comment]
I need to be able to reproduce it, so if you can get it happening in an example on JSBin that would help. 
Here's a template to get you started:
http://jsbin.com/?html,css,js,output

**Comment by mherb63** [comment]
Thank You, the problem was actually in my code of course :)   My submit button callback function onclick was not on the <button> tag but on a <span> tag.  Don't know how it worked in Safari and Chrome.  But once I fixed that it works in Firefox.

Thanks for such a great plugin.

Mike
