### ISSUE TITLE
Display two message after checking validation condition

### ISSUE THREAD

**Issue by niketthapa** [1000hz/bootstrap-validator#281]
Hi
I am going to validate email with data-minlength="15" and I need two message here. If user input invalid email then "Invalid your email" message needs to display and in another condition if user input valid email but if length is less then 15 then "Need at least 15 character" message needs to show.

Is there any solution for me.

**Comment by 1000hz** [comment]
That's already how the plugin works.
http://jsbin.com/lofovedape/edit?html,output

**Comment by niketthapa** [comment]
I think you din't understand my problem here http://prntscr.com/ab1cdb in your code two messages are displayed at same time but I want only one message at first invalid email and if email are valid then only need to check length of email, also error message need to display my own for different two error state.
