### ISSUE TITLE
doc: 'focus' option is not scrolling properly in demo page (Firefox)

### ISSUE THREAD

**Issue by nelson6e65** [1000hz/bootstrap-validator#282]
http://1000hz.github.io/bootstrap-validator/

When you left 'email' (for example) with errors and click Submit button while field is not visible, focus works but do not scrolls to field to make it visible in the page.

This occurs in **Firefox**; in **Chrome** works fine.

**Comment by 1000hz** [comment]
Looks like I need to select `$('html, body')` for scrolling instead of just `$(document.body)` for better cross-browser support.

**Comment by nelson6e65** [comment]
Actually, in my project I had to use `$("#page-wrapper")` due to my layout, because I had the same issue if I use ` $('html, body')`. :pensive:

After I update to v0.10.1, it works the focus **_in my layout_** without include #128.
