### ISSUE TITLE
Custom error message for pattern

### ISSUE THREAD

**Issue by javansoft** [1000hz/bootstrap-validator#285]
Hi, is there a way to define a custom error message for when a pattern is invalid?
for example :
`<div class="form-group">
        <label for="title">news title</label>
        <input data-pattern-error="invalid character, edit this" name="title" pattern="^[\u0600-\u06FF]+$" type="text" class="form-control" placeholder="news title" required>
        <div class="help-block with-errors"></div>
    </div>
`

Thanks.

**Comment by 1000hz** [comment]
Currently you can do `data-native-error` or `data-error` but it has the
potential to show for other kinds of errors.

In probably the next release I'll add more specific error messages so
`data-pattern-error` would work.

**Comment by sornbarang** [comment]
when do you release specific error messages?

**Comment by criticalenzo** [comment]
I had a similar issue. I'm trying to use bootstrap tooltips and popovers on the same element and I don't want to use the 'title' attribute as it overrides the tooltip/popover titles. However, the pattern error message uses the title. This was the solution I came to below. Not the best but it seems to work. To use it you have to update the getErrorMessage function with the line below and put data-patt="my format error" as your attribute. You can change the name of the attribute in the function.

    function getErrorMessage(key) {
            return $el.data(key + '-error')
              || $el.data('error')
              ||key == 'native' && $el[0].validity.patternMismatch && $el.attr("data-patt") //Add this line
              || key == 'native' && $el[0].validationMessage
              || options.errors[key]          
    }

                 <div class="form-group">
                    <label for="txtName">Name</label>
                   <input type="text" class="form-control" id="txtName" runat="server"
                       title=""  
                       popover-title="Popover" 
                       popover-content="This is a popover"
                       tooltip-title="ToolTitle"  
                       pattern="[a-zA-Z]*"
                       data-patt="Only letters"
                       required="required" 
                       data-minlength="2" 
                       maxlength="20" />
                    <div class="help-block with-errors"></div>
                </div>

**Comment by criticalenzo** [comment]
Nevermind, I found a better way that works with the plugin.

    $('#form1').validator({
        custom: {
            'patt': function ($el) {
                var regex = new RegExp($el.data('patt'),'g');
                return regex.test($el.val());
            }
        },
        errors: {
            patt: "incorrect format"
        }
    });

                <div class="form-group">
                    <label for="txtName">Name</label>
                   <input type="text" class="form-control" id="txtName" runat="server"                        
                       data-patt="^[a-zA-Z]*$"
                       data-patt-error="Only the letters"
                       popover-title="Password popover" 
                       popover-content="This is a popover" 
                       tooltip-title="ToolTitle"  
                       required="required" 
                       data-minlength="2" 
                       maxlength="20" />
                    <div class="help-block with-errors"></div>
                </div>

**Comment by 1000hz** [comment]
This is fixed in the v0.11.0. You can use `data-pattern-error`.
