### ISSUE TITLE
Remove autofill on hover/focus

### ISSUE THREAD

**Issue by gubi** [1000hz/bootstrap-validator#286]
Is it possible to remove the _underscore_ pattern (eg. "____") during the filling field?

**Comment by 1000hz** [comment]
Not sure what you're referring to... This plugin doesn't do anything like that.

**Comment by gubi** [comment]
I'm using the [Bootstrap Material Design](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html) and I have this "effect" only in validating fields.
Following a screenshot

![screenshot](https://cloud.githubusercontent.com/assets/746559/13591635/d47bd802-e4ea-11e5-84d8-9a8003d3be7c.png)

**Comment by 1000hz** [comment]
Sorry, I don't think this behavior is being caused by this validator plugin. Are you sure you're using this one and not another plugin with a similar name?

**Comment by gubi** [comment]
You're right!
Sorry for the mismatching
