### ISSUE TITLE
Enter key is not working

### ISSUE THREAD

**Issue by enayet-repo** [1000hz/bootstrap-validator#287]
Normally by default if we press enter on any input field focusing and if there is no validation error then the form should be submitted. I think its an important feature for ease of use.
But here it is not working.

Thank you.

**Comment by 1000hz** [comment]
Should be working. Check out the example on the docs page. Works for me in Chrome.

**Comment by enayet-repo** [comment]
Ah! My mistake. Sorry. Now working.

Thank you.
