### ISSUE TITLE
Question:Server side validation error showing

### ISSUE THREAD

**Issue by enayet-repo** [1000hz/bootstrap-validator#288]
After the form is submitted, server is sending the errors for each from-control if any server side data validation error occured. The response data is an JSON containing the keys which are any form-control's name and values are as the error messages.

How can I show/indicate them as like we are showing while validating by JS?

Thank you.

**Comment by 1000hz** [comment]
The plugin won't handle that for you. It only does handles server-side validation if you use the `data-remote` validator to validate individual fields as they are being filled.

You'll need to write code to put the errors in their corresponding `.help-block.with-errors` and add the `.has-error` class to the `.form-group` element. Something like:

```js
for (var key in errors) {
  $('input[name="' + key + '"]').closest('.form-group')
    .addClass('has-error')
    .find('.help-block.with-errors')
      .text(errors[key])
}
```

**Comment by enayet-repo** [comment]
Thanks you for quick answer.

**Comment by senseluo** [comment]
@1000hz your solution works but when user corrected the failed field then the error message previously added is still there (with gray color). Looks it recognized it as hint text. Is there a way to handle it? 
Thanks!

**Comment by MaxKostenko** [comment]
@1000hz Strange... Why so popular lib don't have this basic functionality?
