### ISSUE TITLE
Has it a Validated = true feature?

### ISSUE THREAD

**Issue by efkan** [1000hz/bootstrap-validator#29]
I want to use with jquery ajax. And I need a flag that indicates to current situation of validating form.
For instance;
if($('#myForm').Validate()) {
    $.get(function() {
          .............
    }
}

**Comment by hitchcott** [comment]
+1, and I saw the workaround - but this seems like a bit quick n dirty.

Perhaps you could add a callback to the `validate` method which returns an error?

**Comment by 1000hz** [comment]
I won't be adding any arguments to the API, but I was planning on adding some classes or something to form like `is-valid` and `is-invalid` that you can query like `$('#myForm').is('.is-invalid')`.
