### ISSUE TITLE
How can I change validation rules dynamically

### ISSUE THREAD

**Issue by jhsalves** [1000hz/bootstrap-validator#297]
Dear

I want to change the validation rules based on User's actions. Ex .: click a checkbox or button disable specific validations in a text field etc...
I tried that removing field validation attributes and revalidating the entire form again - $(form).validator('destroy').validator(); form.reset(); -, but it did not work.
Obs .: The form is contained in a modal box

**Comment by joostschepel** [comment]
`$(form).validator('destroy');`
	`$(form).validator();`

Did the trick for me (after inserting some dynamic fields through ajax)

**Comment by yanickrochon** [comment]
Actually, you more or less only need to clear some data on the target field. I actually do this myself inside modal dialogs and it works. For example :

```js
$('#conditionalInput', form).prop('required', condition)
   .removeData(['bs.validator.errors', 'bs.validator.previous'])
   .closest('form').validator('validate');
```

**Comment by 1000hz** [comment]
You can just change the attributes and trigger `input` events as needed
http://jsbin.com/nezucetelo/edit?html,js,output
