### ISSUE TITLE
How to use with meteor

### ISSUE THREAD

**Issue by mherb63** [1000hz/bootstrap-validator#301]
Are there any examples showing how to use this with meteor?  I'm not sure how to show the errors on the form in a "meteor" way.

`<div class="help-block with-errors">{{don't I need something here}}</div>`

Thanks,

Mike

**Comment by 1000hz** [comment]
The plugin manages error state for you, so Meteor shouldn't need to get involved. I've never used Meteor so I can't tell you anything more than that. Maybe someone on stackoverflow could help you out.

**Comment by mherb63** [comment]
Actually it is working.  I pulled the trigger too early on opening an issue.  You're correct, you don't need and handlebar stuff inside that div.

Thanks,

Mike
