### ISSUE TITLE
How to validate Google recaptcha?

### ISSUE THREAD

**Issue by adrianrz** [1000hz/bootstrap-validator#303]
Hello, 
Is there some way to validate Google recaptcha?
Thanks!

**Comment by 1000hz** [comment]
You can probably do it with a custom validator function unless the validation is asynchronous. Async custom validator support will be coming in the next version when I have some time.

**Comment by 1000hz** [comment]
Here's a complete example of reCAPTCHA working with this plugin.
http://jsbin.com/kirevujexa/edit?html,js,output
