### ISSUE TITLE
No way to update cached inputs for forms with dynamic fields

### ISSUE THREAD

**Issue by methakon** [1000hz/bootstrap-validator#306]
Hi it is not working with dynamically generated field's 
i have used ajax coll to add more button that use to add additional fields

by then when i press validate  

```
function set_validator()
{
    console.log('----------');
     $('#v_form').validator();
}

```
it is ignoring the dynamically added folds is their is any solution 

background i have done minimal alteration  validator.js at $(window).on('load', function () but hope that will not effecting in this case

```
  $(window).on('load', function () {
    $('form[data-toggle="validator"]').each(function () {
      var $form = $(this)
      Plugin.call($form, $form.data())
    });
    $( ".form-group" ).each(function( index ) {
        if($(this).find('.help-block').length== 0)
        {
            var hb= document.createElement('div');
            hb.className ='help-block with-errors';
            this.appendChild(hb);
           // console.log(this);
        }
             
        });
  });
```

**Comment by 1000hz** [comment]
The validator is caching the fields at initialization for performance. I'll need to add a `refresh` method to the plugin you can call to update the cached inputs.

**Comment by methakon** [comment]
how to do it

**Comment by corganhejijun** [comment]
by comments one line in validator.js，i solve this problem temporary.


```
 function Plugin(option) {
    ……
      if (!data && option == 'destroy') return
      //if (!data)  **-------------comments this line at 331**
      $this.data('bs.validator', (data = new Validator(this, options)))
      if (typeof option == 'string') data[option]()
    })
  }
```

**Comment by DHorchler** [comment]
@corganhejijun , sorry, your temporary solution did not work in my case.

@1000hz , any chance to see that refresh-method any time soon?
Or is there another solution for dynamically added form fields?
Thanks.

**Comment by 1000hz** [comment]
I don't know when I'll have time to be able to work on the next version of the plugin, but you can use v0.9 in the meantime.

**Comment by GarethFox** [comment]
That's exactly the issue I am experiencing.
I need to .attr('required') on showing up input depending on checkboxes or radio groups selections...
Did you say that v0.9 is the one that can temporary allow reloadind input for forms if using .validator('destroy'); then .validator(); again ?
Thanks!

**Comment by 1000hz** [comment]
`.validator('update')` has been added to v0.11.0

**Comment by dmsaciklum** [comment]
how it can be used?

**Comment by Maransatto** [comment]
1000hz, it's been a greak work you've done here. But I'm really facing difficult to find an example of .validator('update'), or any other example that changes the attribute data-validate dynamically.
Can someone here help me?
Thank you!
