### ISSUE TITLE
validation not working on non required input type number

### ISSUE THREAD

**Issue by makelued21** [1000hz/bootstrap-validator#307]
validation not working on non required input type number

`<input type="number" name="item-uw" id="item-uw" class="form-control" placeholder="Unit Weight"  step="0.05" min="0" max="99999999999999"/>`

**Comment by 1000hz** [comment]
It's working as intended.
http://jsbin.com/zimaciwita/edit?html,output

Try to enter 5 and it shows an error even though the input is not required.

**Comment by milogrunge** [comment]
but we expected if min or max is not defined, it only validate numeric

**Comment by df-git** [comment]
I confirm some problems with the input type number and without the "required" tag. I've tested it with Firefox.
Basically the form is not validating.
