### ISSUE TITLE
should help-block not be hidden by validator

### ISSUE THREAD

**Issue by yene** [1000hz/bootstrap-validator#308]
Should the validator not hide the help-block if it is not used. Because it adds invisible margin, mostly noticeable in horizontal forms.

![](http://i.imgur.com/O5rPH5K.png)

**Comment by 1000hz** [comment]
There shouldn't be any need to hide it since the margins collapse and don't affect layout.
http://jsbin.com/zimaciwita/edit?html,css,js,output

You can hide it yourself if you really need to by hooking into the `valid.bs.validator` and `invalid.bs.validator` methods.

**Comment by yene** [comment]
You can see it in form-horizontal, http://jsbin.com/gagameloku/1/edit?html,js,output

**Comment by yene** [comment]
It does not collapse in from-horizontal. http://jsbin.com/jizahevate/1/edit?html,output
Im just gonna hack a fix onto .with-errors

**Comment by 1000hz** [comment]
Ah, I see. Yeah, you can work around it with this

```css
.help-block.with-errors:empty {
  display: none;
}
```
