### ISSUE TITLE
cant we have a button functionality to validate without submiting

### ISSUE THREAD

**Issue by methakon** [1000hz/bootstrap-validator#309]
Is their a way to validate without submitting the form or a way to check the validation status

**Comment by lerzenit** [comment]
+1

**Comment by ddspringle** [comment]
http://1000hz.github.io/bootstrap-validator/#validator-events - listen for the events you're interested in intercepting - no form submission required.

To have a button validate without submitting, use preventDefault();

**Comment by 1000hz** [comment]
You can easily hook up a button to call `$('#form').validator('validate')` on click
