### ISSUE TITLE
Email Validation Issue

### ISSUE THREAD

**Issue by Tabishtabby** [1000hz/bootstrap-validator#31]
I found a few faults in Email Validation. When i type ' asa@asda.com ' it a valid email address but when i type ' asa@asda ' bootstrap-validator considers this as a valid email address. 
Examples of invalid email addresses considered as valid by ' bootstrap-validator '
1)  asd@asda
2)  asda@asda.12
3)  asd@asda.ads123

I'm not good with javascript but i hope this regex will help.
RegExp(/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,4}$/)

**Comment by adaniello** [comment]
Hi, i think that also following the spec, at least the first case "asd@asda" is NOT valid, because (from spec RFC 1034) `ldh-str` should be "grouped in words separated by a dot (.)" and the case "asda" ins't.
The block `ldh-str 1*( "." ldh-str )` so is at least one group of two words.
Regards

**Comment by 1000hz** [comment]
Yeah, I think you're right according to that spec. However, Wikipedia states that it's valid
https://en.wikipedia.org/wiki/Email_address#Valid_email_addresses

Regardless, this plugin defers to the browser's HTML5 validation API, so this is up to the browser vendors to decide.
