### ISSUE TITLE
Can't find typescript definition file anywhere

### ISSUE THREAD

**Issue by BWeesy** [1000hz/bootstrap-validator#312]
I find it hard to believe that with 1,046 stars and 494 forks that there isn't a .d.ts file for this somewhere on the web. However, I can't find it. Would it be worth adding one to the DefinatelyTyped repository?

If one doesn't exist, we best get to work on writing one, even if it's just as simple as extending the $('#testForm').validator(); method to jQuery to stop typescript having a hissyfit. This especially the case for when Angular2 comes out and makes everything typescript.

Cheers

**Comment by 1000hz** [comment]
I've never used TypeScript and nobody's asked about it yet, so I'm guessing one doesn't exist. I might accept a pull request to include a .d.ts file, but I don't know the first thing about TypeScript so it might be best to just submit it to DefinitelyTyped instead, because I won't be able to support it.

**Comment by BWeesy** [comment]
Huh. I'm surprised. I'll see if I can't create one when I get back to the validation part of the project later next week.

Peace

**Comment by meijdenmedia** [comment]
@BWeesy have you found or created a .d.ts file? Would be nice if you want to share it with me / the rest of the world :)

**Comment by katrina-engelbrecht** [comment]
I have the same question.

**Comment by BradyLiles** [comment]
Just added one with Pull Request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13626

**Comment by 1000hz** [comment]
Thanks @BradyLiles! Closing this issue.

**Comment by cfischer31** [comment]
Way to go Brady!

**Comment by katrina-engelbrecht** [comment]
It's great! Thanks  bradyliles!

**Comment by meijdenmedia** [comment]
Thanks! \o/
