### ISSUE TITLE
not valid a selectbox

### ISSUE THREAD

**Issue by Esty12** [1000hz/bootstrap-validator#313]
Hi,
I have a form' all the elements in divs with class "form-group"
but the selecbox not validation,
how I valid it?
Thanks you

**Comment by rhedman** [comment]
I have this issue too, the <select> is supposed to be required but I get no validation and the submit-button is always enabled. I have no problem with any other form-element.

`<div class="form-group">
                                <div class="input-group">
                                    <label for="chooseAccount" class="required">Välj konto</label>
                                    <select class="form-control"
                                        id="chooseAccount"
                                        aria-describedby="selectValidationMessage"
                                        data-error="Välj ett konto"
                                        required>
                                        <option>Välj</option>
                                        <option value="konto #1">Konto #2</option>
                                        <option value="konto #2">Konto #3</option>
                                        <option value="konto #3">Konto #4</option>
                                        <option value="konto #4">Konto #5</option>
                                    </select>
                                </div>
                                <div class="help-block with-errors form-control-feedback" id="selectValidationMessage"></div>
                            </div>`

**Comment by 1000hz** [comment]
Glad you got it worked out! Closing this ticket now.

**Comment by tbohr** [comment]
I have the same problem. I have this option as prompt and and 

```
<select class="form-control" required="required" name="user[gender]" id="user_gender">
<option value="">Gender*</option>
<option value="Male">Male</option>
<option value="Female">Female</option>
</select>
```
It does work with chrome, firefox ... ONLY iphone eg. has problems.

**Comment by edgarjaviertec** [comment]
Any solution on this already? I have the same problem.

I have to choose the <select> element 2 times (only iPhone)

<select class="form-control input-sm" data-error="Rellena este campo con la edad del menor" required>
    <option value="">Edad</option>
    <option value="0">< 1 año</option>
    <option value="1">1 año</option>
    <option value="2">2 años</option>
    <option value="3">3 años</option>
    <option value="4">4 años</option>
    <option value="5">5 años</option>
</select>

**Comment by 1000hz** [comment]
Works fine for me when I test it using iOS 9.3.2

http://output.jsbin.com/kebuqagewu [[source](http://jsbin.com/kebuqagewu/edit?html,output)]

**Comment by edgarjaviertec** [comment]
I updated from version 0.10.2 to 0.11.5 version and now it works fine on iPhone. @1000hz Thank you very much!
