### ISSUE TITLE
Positive feedback

### ISSUE THREAD

**Issue by torchristensen** [1000hz/bootstrap-validator#318]
I would like an option where an input field either turns green and/or adds a checkmark to the inputfield id the user correctly has entered data

**Comment by 1000hz** [comment]
You just need to put a `has-feedback` class on your `form-group`

Look at the "Twitter" field in the docs example
http://1000hz.github.io/bootstrap-validator/

**Comment by torchristensen** [comment]
Thanks alot.
Wonderful code :-)

- Tor
