### ISSUE TITLE
Field being marked as required when they are not

### ISSUE THREAD

**Issue by yanickrochon** [1000hz/bootstrap-validator#321]
I have a form in a modal that I use multiple times when editing models. Some fields are optional, and some may even conditionally be inside `<div class="form-group hidden">` elements; all conditional fields are **not** required. For example : `<input type="number" class="form-control text-right" placeholder="Qty." step="0.0001" name="qty">`.

However, when making the modal visible, these conditionally "hidden" fields are considered invalid, for some reason, until I make them "visible", given them focus, and changing their values. After that, they act as expected, even when hidden.

When in error, they are marked as required, as their error message is `"Please fill in this field."`. I tried invalidating the form via JavaScript, re-running the validation, triggering events on the faulty fields, etc. Nothing will cut. Why are these fields in error in the first place, they have no validation whatsoever attached to them?

**Comment by vatsalpande** [comment]
Can you please provide an example in jsbin?

**Comment by yanickrochon** [comment]
Right, I got caught up and forgot to update this issue :smile: 

Initially, the field is marked as `required` from the HTML template, and once the client is loaded, `$(form).validator(...);` is called. Upon viewing a model, `$(optionalFields).prop('disabled', condition);` is called to make fields optional or required, depending on a checkbox or some other conditions. The problem is that since the field's value is not modified, it is not invalidated and any errors are not reset. I end up having to `$(optionalFields).removeData('bs.validator.previous');` to fix this.

**Comment by 1000hz** [comment]
The comparisons with the previous value have been removed in v0.11.0
