### ISSUE TITLE
Forcefully trigger validation on an input field via Javascript

### ISSUE THREAD

**Issue by gvsrini** [1000hz/bootstrap-validator#326]
I have an input field which can sometimes be set via Javascript. In that case, the default validation is not getting triggered on that field. 

However, when I submit the form, the validation is taking place. I would like to get the validation (only on the field) to be done immediately after the value is set (via Javscript).

**Comment by 1000hz** [comment]
trigger an `input` event after you change the value programatically.

```js
$('#myField').val(newValue).trigger('input')
```
