### ISSUE TITLE
separate submit button

### ISSUE THREAD

**Issue by jpnayak** [1000hz/bootstrap-validator#331]
suppose i have a form A with no submit button in it. i have another div B which has a submit button. if form A doesn't validate then it is disabling all the submit buttons (along with form B submit button) on the html. so how to bound form A validation to itself and not interfering the submit buttons outside A?

**Comment by 1000hz** [comment]
Can't reproduce.

http://jsbin.com/gahelafuta/edit?html,output

**Comment by jpnayak** [comment]
Okay, B is not a form, it is only a div which have a button type submit. Try to reproduce.

**Comment by 1000hz** [comment]
Still can't reproduce:
http://jsbin.com/quhiqebopi/edit?html,output

**Comment by jpnayak** [comment]
I said there is no form in B. B is simply a div having a button of type submit. Remove any kind of form elements from B like input, check box, radio or anything else except a submit button.

**Comment by 1000hz** [comment]
It's just a div.

**Comment by 1000hz** [comment]
Please feel free to make a JSBin to reproduce the issue

**Comment by jpnayak** [comment]
OK I shall do a fiddle and share it with you. Okay.

**Comment by jpnayak** [comment]
okay my fault, i have put disabled in B submit button as i have done that according to inspect elements when input fields are not valid. my apology. sorry for wasting your time.
