### ISSUE TITLE
wrecks in bootstrap modal

### ISSUE THREAD

**Issue by jpnayak** [1000hz/bootstrap-validator#332]
i created a form on the modal body. the submit button of that form is clickable irrespective of the validation of that form in the modal body.

**Comment by demogorgon** [comment]
try activating validation via js, also see https://github.com/1000hz/bootstrap-validator/issues/261

**Comment by utego** [comment]
Problem solved for me - see this issue https://github.com/1000hz/bootstrap-validator/issues/336

**Comment by solugebefola** [comment]
I had a comment on this in #345. It seems to be in the Validator DOM element selection for inputs
