### ISSUE TITLE
submit on bootstrap modal

### ISSUE THREAD

**Issue by utego** [1000hz/bootstrap-validator#336]
Hi! First of all sorry for my bad english.

I try to put validator on form in bootstrap modal. When I focus on input (which is requiered) and than focus on other element - everything fine! But if I Click to the submit button -  form is submitted and page is refreshed.

here is code:
<pre style="word-wrap: break-word; white-space: pre-wrap;">
&lt;div class="modal fade modal-asphalt" id="OrderModal" tabindex="-1"&gt;
	&lt;div class="modal-dialog"&gt;
		&lt;div class="modal-content"&gt;
			&lt;div class="container-fluid"&gt;
				&lt;form data-toggle="validator" role="form"&gt;
          &lt;div class="form-group"&gt;
            &lt;label for="inputName" class="control-label"&gt;Name&lt;/label&gt;
            &lt;input type="text" class="form-control" id="inputName" placeholder="Cina Saffary" required&gt;
          &lt;/div&gt;
          &lt;div class="form-group has-feedback"&gt;
            &lt;label for="inputTwitter" class="control-label"&gt;Twitter&lt;/label&gt;
            &lt;div class="input-group"&gt;
              &lt;span class="input-group-addon"&gt;@&lt;/span&gt;
              &lt;input type="text" pattern="^[_A-z0-9]{1,}$" maxlength="15" class="form-control" id="inputTwitter" placeholder="1000hz" required&gt;
            &lt;/div&gt;
            &lt;span class="glyphicon form-control-feedback" aria-hidden="true"&gt;&lt;/span&gt;
            &lt;div class="help-block with-errors"&gt;Hey look, this one has feedback icons!&lt;/div&gt;
          &lt;/div&gt;
          &lt;div class="form-group"&gt;
            &lt;label for="inputEmail" class="control-label"&gt;Email&lt;/label&gt;
            &lt;input type="email" class="form-control" id="inputEmail" placeholder="Email" data-error="Bruh, that email address is invalid" required&gt;
            &lt;div class="help-block with-errors"&gt;&lt;/div&gt;
          &lt;/div&gt;
          &lt;div class="form-group"&gt;
            &lt;label for="inputPassword" class="control-label"&gt;Password&lt;/label&gt;
            &lt;div class="form-group col-sm-6"&gt;
              &lt;input type="password" data-minlength="6" class="form-control" id="inputPassword" placeholder="Password" required&gt;
              &lt;div class="help-block"&gt;Minimum of 6 characters&lt;/div&gt;
            &lt;/div&gt;
            &lt;div class="form-group col-sm-6"&gt;
              &lt;input type="password" class="form-control" id="inputPasswordConfirm" data-match="#inputPassword" data-match-error="Whoops, these don't match" placeholder="Confirm" required&gt;
              &lt;div class="help-block with-errors"&gt;&lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class="form-group"&gt;
            &lt;div class="radio"&gt;
              &lt;label&gt;
                &lt;input type="radio" name="underwear" required&gt;
                Boxers
              &lt;/label&gt;
            &lt;/div&gt;
            &lt;div class="radio"&gt;
              &lt;label&gt;
                &lt;input type="radio" name="underwear" required&gt;
                Briefs
              &lt;/label&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class="form-group"&gt;
            &lt;div class="checkbox"&gt;
              &lt;label&gt;
                &lt;input type="checkbox" id="terms" data-error="Before you wreck yourself" required&gt;
                Check yourself
              &lt;/label&gt;
              &lt;div class="help-block with-errors"&gt;&lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class="form-group"&gt;
            &lt;button type="submit" class="btn btn-primary"&gt;Submit&lt;/button&gt;
          &lt;/div&gt;
        &lt;/form&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;</pre>

so how can I validate form on modal and after validate, if success, submit the form?

**Comment by utego** [comment]
[modal.txt](https://github.com/1000hz/bootstrap-validator/files/273534/modal.txt)

**Comment by utego** [comment]
<pre style="word-wrap: break-word; white-space: pre-wrap;">
&lt;div class="modal fade modal-asphalt" id="OrderModal" tabindex="-1"&gt;
	&lt;div class="modal-dialog"&gt;
		&lt;div class="modal-content"&gt;
			&lt;div class="container-fluid"&gt;
				&lt;form data-toggle="validator" role="form"&gt;
          &lt;div class="form-group"&gt;
            &lt;label for="inputName" class="control-label"&gt;Name&lt;/label&gt;
            &lt;input type="text" class="form-control" id="inputName" placeholder="Cina Saffary" required&gt;
          &lt;/div&gt;
          &lt;div class="form-group has-feedback"&gt;
            &lt;label for="inputTwitter" class="control-label"&gt;Twitter&lt;/label&gt;
            &lt;div class="input-group"&gt;
              &lt;span class="input-group-addon"&gt;@&lt;/span&gt;
              &lt;input type="text" pattern="^[_A-z0-9]{1,}$" maxlength="15" class="form-control" id="inputTwitter" placeholder="1000hz" required&gt;
            &lt;/div&gt;
            &lt;span class="glyphicon form-control-feedback" aria-hidden="true"&gt;&lt;/span&gt;
            &lt;div class="help-block with-errors"&gt;Hey look, this one has feedback icons!&lt;/div&gt;
          &lt;/div&gt;
          &lt;div class="form-group"&gt;
            &lt;label for="inputEmail" class="control-label"&gt;Email&lt;/label&gt;
            &lt;input type="email" class="form-control" id="inputEmail" placeholder="Email" data-error="Bruh, that email address is invalid" required&gt;
            &lt;div class="help-block with-errors"&gt;&lt;/div&gt;
          &lt;/div&gt;
          &lt;div class="form-group"&gt;
            &lt;label for="inputPassword" class="control-label"&gt;Password&lt;/label&gt;
            &lt;div class="form-group col-sm-6"&gt;
              &lt;input type="password" data-minlength="6" class="form-control" id="inputPassword" placeholder="Password" required&gt;
              &lt;div class="help-block"&gt;Minimum of 6 characters&lt;/div&gt;
            &lt;/div&gt;
            &lt;div class="form-group col-sm-6"&gt;
              &lt;input type="password" class="form-control" id="inputPasswordConfirm" data-match="#inputPassword" data-match-error="Whoops, these don't match" placeholder="Confirm" required&gt;
              &lt;div class="help-block with-errors"&gt;&lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class="form-group"&gt;
            &lt;div class="radio"&gt;
              &lt;label&gt;
                &lt;input type="radio" name="underwear" required&gt;
                Boxers
              &lt;/label&gt;
            &lt;/div&gt;
            &lt;div class="radio"&gt;
              &lt;label&gt;
                &lt;input type="radio" name="underwear" required&gt;
                Briefs
              &lt;/label&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class="form-group"&gt;
            &lt;div class="checkbox"&gt;
              &lt;label&gt;
                &lt;input type="checkbox" id="terms" data-error="Before you wreck yourself" required&gt;
                Check yourself
              &lt;/label&gt;
              &lt;div class="help-block with-errors"&gt;&lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
          &lt;div class="form-group"&gt;
            &lt;button type="submit" class="btn btn-primary"&gt;Submit&lt;/button&gt;
          &lt;/div&gt;
        &lt;/form&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;</pre>

**Comment by utego** [comment]
problem solved! Dear devolopers - something was wrong after 2015 year:

I found the same problem in this issue https://github.com/1000hz/bootstrap-validator/issues/332

in this ticket you recommended to see this unsolved problem https://github.com/1000hz/bootstrap-validator/issues/26

so, i find that there is no same problem before first post by AJRames commented on 2015 Jan 27.

And i thought: possible something was wrong before this date?!

OK. I downloaded previous version of plugin [v0.9.0](https://github.com/1000hz/bootstrap-validator/releases/tag/v0.9.0) And everything will OK !

Dear 1000hz - i found your plugin very COOL! Please find the mistakes in your newest version and correct it!

**Comment by danw76** [comment]
Thanks!!!.. I have been trying to figure out why my submit buttons which were disabled before no longer were disabled.  Reverting to .9 fixed the problem.

To recreate, you don't need a modal.  Any nested div will cause the problem.

**Comment by bozzit** [comment]
For the record had the same issue and reverting to 0.9 fixed it for me as well

**Comment by quadrogod** [comment]
If not working this solution: $('.modal').on('shown.bs.modal', function (e) { $(this).find('form[data-toggle=validator]').validator() });

Try first detroy validator $('.modal').on('shown.bs.modal', function (e) { $(this).find('form[data-toggle=validator]').validator('destroy'); $(this).find('form[data-toggle=validator]').validator() });

It's work for me.

**Comment by gabrielseco** [comment]
@quadrogod thanks a lot.

**Comment by emilie-jin** [comment]
@quadrogod  thanks a lot for saving me, I have worked on it for the whole morning

**Comment by QuadeHale** [comment]
@t4n017's answer works properly. However, you'll notice the validator doesn't prevent submits if the modal is closed and re-opened. Here's what I have to do to get properly functional performance from it:

```
$('#some-modal').on('shown.bs.modal', function (e) {
  $(this).find('form').validator()

  $('#some-modal-form').on('submit', function (e) {
    if (e.isDefaultPrevented()) {
    } else {
      e.preventDefault() // if you're using AJAX
      // do the submission thing
    }
  })
  $('#some-modal').on('hidden.bs.modal', function (e) {
    $(this).find('form').off('submit').validator('destroy')
  })
})
```
I am _not_ using the `data-toggle='validator'` attribute to initialize the modal validators, only JS. I would strongly recommend operating this way, since data-toggle finds common use elsewhere in Bootstrap. 
This function can be genericized pretty easily if you change from ID's to classes, then just tack the class on the modal.

**Comment by nelson6e65** [comment]
Validator works, but is not preventing to be submitted! :persevere:

**Comment by 1000hz** [comment]
Seems to be working ok.
http://jsbin.com/rumobowixu/1/edit?html,output

It doesn't submit if there are errors, and then if you fill out the form correctly you can see the POST being sent in the Network tab of the developer tools.

**Comment by nelson6e65** [comment]
Not working in my local... I've v2.2.4 installed.

Its still sending ajax request.

I simplified in here:
http://jsbin.com/facokewuma/1/edit?html,js,output

**Comment by 1000hz** [comment]
@nelson6e65 The validator needs to be initialized before the submit handlers are bound. Additionally, you need to check if `!e.isDefaultPrevented()` before you make your ajax call.

```js
  // ...

  $formulario.validator().submit(function (event) {
    LoginDialog.toggleButtons(false);
    // Si tienen data-ajax, se le agrega un listener al darle al botón 'Eliminar'
    if ($formulario.data('ajax') && !event.isDefaultPrevented()) {

  // ...
```

**Comment by nelson6e65** [comment]
@1000hz Thanks. In [jsbin seems to be working](http://jsbin.com/futapahoca/1/edit?html,js,output), but in my local is still sending ajax request regardless the value of `event.isDefaultPrevented()`. :disappointed: Maybe some kind of weird logic in my javascrip. I'll check this later (I'm sleepy now).

**Comment by nelson6e65** [comment]
> "Not working in my local... I've v2.2.4 installed."

> "[...]my local is still sending ajax request regardless the value of [...]"
>@nelson6e65

Sorry, . My bad: I was using an old version (`0.10.2`) here. :sweat_smile:

Updating to `0.11.5` solved that problem. 

Thank you, @1000hz. I solved other issues by following your advises. :smiley:

**Comment by liquidvisual** [comment]
Thank you so much! I was tearing my hair out trying to find what was bugging this. @tanoabeleyra's solution worked for me.

**Comment by lcsqlpete** [comment]
Just started to try validator and I think I have a similar issue but slightly different.  I already capture the submit button click with:

$(":submit").on("click", function (e) {
    //Submit the form data and display the result
    e.preventDefault();
   //Submit the form with ajax here

I'm only using the html5 validators right now but none of them are reported when I click the Submit button. I tried adding a check for isDefaultPrevented but that didn't make any difference. 

I have validation in my server script which catches the errors but want them to happen before I submit the form.

Is my Submit handler getting in the way?

**Comment by coros-sanborn** [comment]
I'm having the same issue with validator allowing a modal form to submit even with errors.
I'm using bootstrap validator v0.11.9 with Rails 5. 
I have a bootstrap modal that has a form with "remote: true" (AJAX).
I'm initialized validator with javascript and am not using the data-toggle attributes.

If I open the form and immediately click "submit" I can see the validation errors, but the form continues to submit.

I tried the recommended solution above - but can not figure out to to prevent the form from submitting. 

This is the code I'm using (rails 5 - new.js.erb) - everything works except the form submits with errors.
```
var modal = $("#userFormModal");
modal.find(".modal-content").html("<%= j (render partial: 'form', locals: {user: @user}) %>");
modal.modal();
modal.on("shown.bs.modal", function(){
  enableFormBehaviors();
  $("#new_user").validator("destroy").validator();
});
```
This is an example of the html mark up:
```
<%= form_for(@user, remote: true) do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>

    <h1 class="modal-title tiny_title">New User Record</h1>
  </div>

  <div class="modal-body margin_top_10">
    <% if @user.errors.any? %>
      <%= render partial: "shared/form_errors", locals: {errors: @user.errors.full_messages } %>
    <% end %>

    <div class="form-group">
      <div class="row">
        <div class="col-md-5">
          <label for="first_name_input">First Name <span class="required">*</span></label>
        </div>
        <div class="col-md-7">
          <%= f.text_field :first_name, id: "first_name_input", class: "form-control",
                           data: {error: "First Name required"}, required: true %>
          <div class="help-block with-errors"></div>
        </div>
      </div>
    </div>

    ....... removed for example
  </div>

  <div class="modal-footer">
    <%= f.submit @ftot.new_record? ? "Create Project" : "Edit Project", class: "btn save_btn focus_btn" %>
    <button class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
<% end %>
```

Any help would be appreciated. I've spend days trying to figure this out.
