### ISSUE TITLE
Ignore protocol on URL validation

### ISSUE THREAD

**Issue by drewf** [1000hz/bootstrap-validator#337]
Would be nice to have a data- property that causes validation of inputs with type "url" to not require a protocol as a part of the input (e.g. "http://" and "https://").

**Comment by 1000hz** [comment]
Seems like browsers don't consider protocol-relative URLs as valid either. This plugin just defers to the built-in HTML5 Constraint Validation API for most of its validations. Sorry, but I'm not gonna add a workaround to the plugin. However, you can write a custom validator or use the `pattern` validator to do what you need.

**Comment by drewf** [comment]
I appreciate the quick reply. I'll look into my options. I appreciate the work you've done on your validator plugin. Thanks!
