### ISSUE TITLE
Trailing space doesn't trigger invalidation for regex excluding spaces

### ISSUE THREAD

**Issue by johnhorner** [1000hz/bootstrap-validator#338]
I don't know if this is related to [issue 98](https://github.com/1000hz/bootstrap-validator/issues/98) but although my regular expression only allows `^[A-z0-9]{3,30}$` putting a trailing space doesn't cause the field to become invalidated, i.e. 'foo bar' causes a match error, but not 'foobar '.

**Comment by 1000hz** [comment]
Thanks for the report. You found a bug. The plugin calls `$.trim()` on field values before it validates them. This was originally added to prevent whitespace-filled fields from being considered valid by the `required` validator, but now it's being applied too broadly. Additionally, there was a recent addition to the plugin to prevent fields from re-running their validators if their value hasn't changed. In this case, the field values are being compared after the trim so the plugin thinks the field has not changed.

Either the trim needs to be more deliberately placed or I need to get rid of the problematic optimization altogether.

**Comment by johnhorner** [comment]
Thanks for the response, glad I could help.
