### ISSUE TITLE
support bootstrap dropdown

### ISSUE THREAD

**Issue by sdboer78** [1000hz/bootstrap-validator#339]
please add support for bootsrap dropdown's (buttons) and https://silviomoreto.github.io/bootstrap-select/examples/

**Comment by donnes** [comment]
Works fine.
You need set a option with blank value, if not, your select will always be valid.

Example: https://jsfiddle.net/gLxsqgqd/

**Comment by sdboer78** [comment]
Great!
But styling issn't correct and has-succes and has-error doesn't work 

https://jsfiddle.net/sdboer/txg03Luv/
See the glyphicon-piggy-bank for correct (instant) validation feedback

**Comment by donnes** [comment]
I solved some problems with HTML structure and CSS

Now is working fine, see fiddle:
https://jsfiddle.net/txg03Luv/3/

**Comment by sdboer78** [comment]
wow cool! do you have also a fix for the green has-success border around the dropdown?

**Comment by donnes** [comment]
Yeah, just add this in your CSS

```
.has-success .bootstrap-select .dropdown-toggle {
  border-color: #3c763d;
}
```

**Comment by sdboer78** [comment]
great! last issue:
on a mobile chrome the dropdown height is not correct, it is only 1px.... see screenshot

![image](https://cloud.githubusercontent.com/assets/2686377/15782800/ea955518-29ab-11e6-9c05-b7e0083351fa.png)
