### ISSUE TITLE
Password match not working

### ISSUE THREAD

**Issue by alexhobday** [1000hz/bootstrap-validator#340]
I keeping getting the "No match" error even though the passwords do match:

`<fieldset class="m-b-2">
      <legend class="chevron">Login Details</legend>
      <div class="form-group">
        <label class="sr-only" for="email">Email address &#42;</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" required>
        <div class="help-block with-errors"></div>
      </div>
      <div class="form-group">
        <label class="sr-only" for="password">Password &#42;</label>
        <input 
          class="form-control"
          type="password"
          id="password" 
          name="password" 
          placeholder="Enter password" 
          required>
        <div class="help-block with-errors"></div>
      </div>
      <div class="form-group">
        <label class="sr-only" for="password_confirm">Confirm Password &#42;</label>
        <input 
          data-match="#password" 
          data-match-error="Whoops, these don't match" 
          data-minlength="8" 
          type="password" 
          class="form-control" 
          id="password_confirm" 
          name="password_confirm" 
          placeholder="Confirm Password"
          required>
         <div class="help-block with-errors"></div>
      </div>
    </fieldset>`

You can check it out here: http://dev.tunnelflight.com/account/register

**Comment by Shiuyin** [comment]
I have the same problem, i am using version 0.11.5. Code:

`<div class="row">
        <div class="form-group has-feedback">
            <label for="userPw">
                    some label
                </label>
            <input class="form-control" id="userPw" type="password"
                       name="userPw" data-minLength="5"
                       data-error="some error"
                       required/>
                <span class="glyphicon form-control-feedback"></span>
                <span class="help-block with-errors"></span>
        </div>
    </div>
    <div class="row">
        <div class="form-group has-feedback">
            <label for="userPw2">
                   some label 2
                </label>
            <input class="form-control {$borderColor}" id="userPw2" type="password"
                       name="userPw2" data-match="#userPw" data-minLength="5"
                       data-match-error="some error 2"
                       required/>
                <span class="glyphicon form-control-feedback"></span>
                <span class="help-block with-errors"></span>
        </div>
    </div>`

No matter what i type in, even if the passwords do match, it will throw me an "does not match" error. Any ideas?

**Comment by 1000hz** [comment]
@Shiuyin: Works fine...
http://jsbin.com/ruzavuwefi/edit?html,output

**Comment by Shiuyin** [comment]
@1000hz : then i don't know whats happening. Fun thing is, i am using quite a bit of data-match over the project and this is the one thing it breaks. ****. Thank you anyway. :)
