### ISSUE TITLE
Custom validation is return true || false but dont showing error styles and message

### ISSUE THREAD

**Issue by donnes** [1000hz/bootstrap-validator#342]
Hello, appreciate any helps!

1- When submit form doesn't validate, but the custom validation is returning correctly (open the console to see happening)
2- When checked some options is validating ok, but is redundant (2 errors messages)

Fiddle example:
https://jsfiddle.net/9ts4nvhw/4/

Thanks

**Comment by dario86** [comment]
Same here...

**Comment by bhavyanarula** [comment]
I tried to set the custom error message by` $(el).setAttribute('data-error', 'whatever') ` or setting it to 
`$(el).setAttribute('data-error', 'Required Field!') ` when empty.
It is setting the attribute correctly but still the error message shown is wrong. 
the div `<div class="help-block with-errors"></div>` does not update itself dynamicly on change of data-error of the field.

**Comment by bhavyanarula** [comment]
here is a temporary fix: 

```
Validator.prototype.showErrors = function ($el) {
    var method = this.options.html ? 'html' : 'text'

    this.defer($el, function () {
      var $group = $el.closest('.form-group')
      var $block = $group.find('.help-block.with-errors')
      var $feedback = $group.find('.form-control-feedback')

       //----edit start----
      //var errors = $el.data('bs.validator.errors')
      var errors=[]
      errors[0] = $el[0].dataset.error
      errors[1] =''
      //----edit end ----

      if (!errors.length) return

      errors = $('<ul/>')
        .addClass('list-unstyled')
        .append($.map(errors, function (error) { return $('<li/>')[method](error) }))

      $block.data('bs.validator.originalContent') === undefined && $block.data('bs.validator.originalContent', $block.html())
      $block.empty().append(errors)
      $group.addClass('has-error')

      $feedback.length
        && $feedback.removeClass(this.options.feedback.success)
        && $feedback.addClass(this.options.feedback.error)
        && $group.removeClass('has-success')
    })
  }
```


Note- the above fix will only work when you have set the data-error attribute manually through your custom validator function using $(el).setAttribute('data-error', 'Required Field!')

**Comment by donnes** [comment]
@bhavyanarula I will try use this fix, thanks to share.

**Comment by bhavyanarula** [comment]
@donnes 
The fix I wrote above was for some older version.. Today I downloaded the latest one and tried to work on your issue:
There is no fix required for Validator.js but you can check the edit to your code https://jsfiddle.net/9ts4nvhw/8/ 

Its working.

**Comment by 1000hz** [comment]
Yup. Also, you don't need the `errors` option any more, since errors messages are returned by the custom validator function now.

**Comment by donnes** [comment]
Thanks @1000hz and @bhavyanarula for helping :dancers:
