### ISSUE TITLE
 Error: Uncaught TypeError: $(...).validator is not a function

### ISSUE THREAD

**Issue by kevinmachstudio** [1000hz/bootstrap-validator#343]
I keep getting the "validator is not a function" error in my javascript file. I have attached these scripts in my html file, not sure why still getting that error

```
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.0/jquery.validate.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.3/js/bootstrapValidator.min.js"></script>
```

**Comment by 1000hz** [comment]
This plugin is different from the one you are including in your code.

**Comment by ddspringle** [comment]
@kevinmachstudio Here is the proper link for this library:

https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.10.2/validator.min.js

**Comment by MaheshTalaviya** [comment]
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>

**Comment by renbooo** [comment]
@ddspringle thanks bro, this work for me
