### ISSUE TITLE
Hidden forms do not respond correctly

### ISSUE THREAD

**Issue by svillanueva** [1000hz/bootstrap-validator#347]
I am providing a wizard to the user, using forms and tabs. I do not want the user to move from one tab to the next until they correctly complete the first tab. So each tab has its own form. The first form, because it is not hidden works correctly. All of the hidden forms behave in a very weird way.

1. The submit button is not disabled.
2. The fields seem to respond correctly. If I blank out a required field it will correct display as an error.
3. If I click on the submit button no validation occurs even though I explicit call the .validator('validate') method..

I have attached a simple example
[newhtml.zip](https://github.com/1000hz/bootstrap-validator/files/309576/newhtml.zip)

**Comment by svillanueva** [comment]
Actually, this is probably the same issue as the it not working in a bootstrap Modal window. Hopefully what you do to fix that will also fix this.

I will just have to initialize form2 as part of showing it. If I give the user the ability to move back and forth between the 2 forms. Should I be doing anything special or will re-initializing use the existing instance? I don't want to consume too much browser memory.

**Comment by discsox** [comment]
I noticed the same issues and i solved it by simply moving the forms to be hidden off the canvas.
This way all the forms are available to the script but not visible to the user.
CSS is along the ways shown below:
`#FormContainerToBeHidden {
	left:0;
	position:relative;
}
.moveAway {
	left:-9999px !important;
	position: absolute !important;
}`

Hope this helps...

**Comment by 1000hz** [comment]
Hidden form fields are no longer excluded in v0.11.0
