### ISSUE TITLE
Submit Button not getting disabled

### ISSUE THREAD

**Issue by jdhakai1994** [1000hz/bootstrap-validator#348]
Hi there,

I have two forms in a single jsp page. 
If i place them vertically one after another **the submit button in both forms are grayed out** (which is expected and desired).
Whereas, when I set one form property as style="display:block;" and the other style="display:none;" so as to get a desired tabbed effect **the submit button on the second form is not graying out** and remaining active and is posting the data with wrong invalid input.
Please find the jsfiddle links below to get a better understanding
First:- https://jsfiddle.net/jdhakai/36kb3ysg/ (getting disabled)
Second:- https://jsfiddle.net/jdhakai/m805Lgq0/ (not getting disabled)

Any help is appreciated

**Comment by sahibvirk** [comment]
I am having the same issue. Can someone please help in resolving this.
I am using Bootstrap Tabs. And the button of second tab does not get disabled.

**Comment by 1000hz** [comment]
v0.11.0 of the plugin has been released. It seems like it fixes your jsfiddle examples.

**Comment by sahibvirk** [comment]
Thanks buddy! Great work!
But I had shifted to [jQueryValidation](https://jqueryvalidation.org/) plugin by then.
Had to write lots of JS code. But its working quite well.

Will definitely try your plugin again on my next project.
