### ISSUE TITLE
Did not work with <textarea>

### ISSUE THREAD

**Issue by Newcomer1989** [1000hz/bootstrap-validator#349]
It seems not working with textarea.

I tried it with pattern tag, but did not react! Changing the textarea to input all will work correctly. For my case it would be much user friendlier to use a textarea!

Is there any way to change the js library that it also works with textarea?

**Comment by 1000hz** [comment]
`pattern` isn't a valid attribute for textareas, so it's not checked by the HTML5 Constraint Validation API.  You can add this yourself with a custom validator though.

http://jsbin.com/vofihiteqa/edit?html,js,output

**Comment by Newcomer1989** [comment]
Can you please have a look at this?

https://codeshare.io/qYee8

I tried your example, but still did not work. The message about required-field works well and also if I change the textarea to input. But do not react in case of textarea and pattern is not "foo".

Thx a lot for everthing in advance!

**Comment by 1000hz** [comment]
You need to put `data-pattern="YOUR REGULAR EXPRESSION` on the textarea

**Comment by Newcomer1989** [comment]
Yes, I know.. But this did not conside in my script.

On your example it only accept "foo" as value. All other will be refused with an error message.

If I type "foo" in my script, it does not do anything.

**Comment by 1000hz** [comment]
Oh, I see the problem. You're initializing the plugin in the `<head>`, but at that point the form isn't on the page so nothing is happening. Move your initialization code to the end of the `<body>`.

**Comment by Newcomer1989** [comment]
That was the problem. It is no working.
Thx man!

**Comment by TyLy83** [comment]
Hi there, 
does anyone has an example of using this plug in with summernote?

**Comment by abirlal** [comment]
I am new in javascript.
data-pattern in textarea is not working. 
<textarea id="txtarea" class ="" data-pattern="[A-z0-9 ,-]{1,}" maxlength="255"> </textarea>
