### ISSUE TITLE
$('#myForm').submit() called even when form is not validated

### ISSUE THREAD

**Issue by tschaffter** [1000hz/bootstrap-validator#35]
Hello!

First of all thank you for validator.js which is a very useful project.

I have a form to validate and for which I have implemented the method $('#myForm').submit() for processing the form. My issue is that this function is called, and so the data processing is performed, when I click on the Submit button even though the form has not been validated (e.g. a required field is left blank).

Which method can I call inside submit() to know whether the form has been validated (and then process the data) or not (and then leave without doing anything)?

Best,
Thomas

**Comment by liamnnvi** [comment]
as below

$('#form').validator().on('submit', function (e) {
  if (e.isDefaultPrevented()) {
    // handle the invalid form...
  } else {
    // how to send the form , AJAX post to email address... ????
  }
})

**Comment by vclteam** [comment]
for some reason isDefaultPrevented always return true

**Comment by cosmointeractive** [comment]
This does not seem to be working for me. The form still submits when I use this

```
$('#myForm').submit(function (e) {
  if (e.isDefaultPrevented()) return
  //  PROCESS DATA ...
})
```
I have to enter `e.preventDefault();` so that it doesn't. But I don't know how to submit it after errors are fixed.

**Comment by 1000hz** [comment]
Since jQuery executes event handlers in the order they were bound, you need to be sure you bind your submit handler *after* the plugin is initialized. Otherwise, the `e.isDefaultPrevented()` check will happen before the validator has validated the form.

The same goes for if you call `.validator('destroy')`, you'll need to rebind your submit handler after you reinitialize the validator.

**Comment by cosmointeractive** [comment]
I'm not sure what that means as I am fairly new to jquery but I will research it. Thanks for the reply. 

P.S. It might be a good idea to add an example to the docs.

**Comment by 1000hz** [comment]
When the plugin is initialized, it binds a submit handler to your form that calls `.preventDefault()` on the submit event if there's an error. If you bind your submit handler before initializing the plugin on your form, then the `.isDefaultPrevented()` check will execute before the plugin's submit handler has had a chance to call `.preventDefault()`, so it will always be false.

**Comment by yogeshfgiet** [comment]
I have same problem, when i click on submit button bootstrapValidator trow error but AJAX are   sumit the form . 
My code is :- 

$('#frm_creditCardEdit').unbind('submit').bind('submit',function(e) {
 e.preventDefault();
    var url = "edit-payment-profile"; // the script where you handle the form input.
     $('body').loader('show');
       $.ajax({
           type: "POST",
           url: url,
           data: $("#frm_creditCardEdit").serialize(), // serializes the form's elements.
           success: function(data)
           {
           }
please help me
