### ISSUE TITLE
Submit button not disabled with input type number, value=0 and min="10"

### ISSUE THREAD

**Issue by goog62** [1000hz/bootstrap-validator#350]
I expected the validator to catch that 0 is less than the minimum value of 10 and disable the submit button when the form first displays:

`<form id="PledgeForm" method="post" data-toggle="validator">
  <div class="form-group">
    <label for="Amount">Amount</label>
    <input type="number" step=".01" name="Amount" value="0" class="form-control" required="required" min="10" />
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>`

Here's the Fiddle https://jsfiddle.net/goog62/cgeLj1ty/

I'm getting around the problem now on the server side by replacing "0" with "". Any suggestions?

Steve

**Comment by 1000hz** [comment]
Weird... Calling `HTMLElement..prototype.checkValidity()` on the field returns false, but the validator isn't seeing the error for some reason. Seems like a strange bug.
