### ISSUE TITLE
anchors (question)

### ISSUE THREAD

**Issue by stvowi** [1000hz/bootstrap-validator#352]
If I cklick to a link than the validator prevent to leave the website.
I need 2 clicks for a jump to another site if the link ( e.g. back link) is inside of the form tag.
This sucks my users.

Well, how I can prevent the form validation if I click on an anchor? (a tag)

**Comment by 1000hz** [comment]
Are you sure this is an issue caused by the validator? Can you reproduce a simplified example on JSBin?

http://jsbin.com/quxopayovu/edit?html,console,output
