### ISSUE TITLE
How to validate dynamic fields?

### ISSUE THREAD

**Issue by 3zero2** [1000hz/bootstrap-validator#354]
I have a form to which I am adding text boxes dynamically. All of these text boxes are set as required but the form still submits with the text boxes empty. Providing focus to the text boxes does not help either. They do appear with error but the form still submits.

The screenshot below shows the second text box which has been generated dynamically as empty, but the Submit button is still enabled.

Any ideas?

<img width="963" alt="screen shot 2016-06-17 at 22 03 06" src="https://cloud.githubusercontent.com/assets/6965396/16163026/4e15a404-34d7-11e6-940c-29080888da74.png">

**Comment by 1000hz** [comment]
v0.11.0 of the plugin (which is being released tomorrow) has a new method to update the set of fields that will be validated. Call it whenever you add or remove a field on your form.

```js
$('#form')
  .append(newInput)
  .validator('update')
```

**Comment by 3zero2** [comment]
Thanks for the update

**Comment by 3zero2** [comment]
I tried the new method and it works perfectly. Thanks.

**Comment by minosgaea** [comment]
it doesn't work with me !
i first load another html file in a div on the form by
 $('#dividInForm1').load('anotherHtmlFile.html"');
after this :
 $("#form1").validator("update")
and he doesn't validate any of the fields that were added in the div ...
Any suggestions what i do wrong?
