### ISSUE TITLE
Not disabling the submit button in a bootstrap modal

### ISSUE THREAD

**Issue by chwebo** [1000hz/bootstrap-validator#356]
Hey folks,

I added a form to a bootstrap modal and wanted to have it checked by bootstrap-validator, but unfortunately the submit button is not being disabled whereas the same code works well outside the modal.
To check for coding errors I also included the example form from http://1000hz.github.io/bootstrap-validator/ in my modal and there the button wasn't disabled too.

Is this a known issue? If yes, what workaround should I try?

**Comment by 1000hz** [comment]
Yes, it's a known issue. See #345. Use v0.9 in the meantime.
