### ISSUE TITLE
Custom validation not working for me

### ISSUE THREAD

**Issue by zikidevelop** [1000hz/bootstrap-validator#357]
Hi,

I have tried withouth success:

`<form class="form-inline" id='form_nodo_crear' data-toggle='validator' role="form"> `
`                                <div class="form-group has-feedback">`
`                                    <label for="clientes" class="control-label">Clientes</label>`
`                                    <div class="input-group">`
`                                        <span class="input-group-addon"><i class="fa fa-user" aria-hidden="true"></i> <i class="fa fa-users" aria-hidden="true"></i></span>`

`                                        <div class="btn-group" style='width: 100% !important'>                            `
`                                            <input type="text" id='clientes' class="form-control" placeholder="Clientes y grupos de clientes destinatarios" data-tienespan="clientes" data-tienespan-error="No valida" required>`
`                                        </div>`
`                                    </div>`
`                                    <span class="glyphicon form-control-feedback" aria-hidden="true" style="top: 20px !important; z-index: 2 !important"></span>`
`                                    <div class="help-block with-errors">Clientes y grupos de clientes destinatarios, escribir nombre o CIF y cuando aparece click para aceptar</div>`
`                                </div>  `

And the script:

`var validatorOptions = {`
`        disable: true,`
`        delay: 100,`
`        custom: {`
`            tienespan: function ($el) {`
`                return false;`
 `           }`
`        },`
`        errors: {`
`            tienespan: "Debe tener al menos un elemento"`
`        }`
`    };`
    
`    $("#form_nodo_crear").validator(validatorOptions);`

I have looked to the examples and documentation and everything looks right, but custom validators functions are not being executed and always validates as OK the field if you enter any text.

Any idea?

Thanks in advance.

Yours,

ziki

**Comment by danielarakaki** [comment]
Try to take the attribute data-toggle='validator' because if you initialized the validator in the javascript, you don't needd declare it again in tag form.
