### ISSUE TITLE
Laravel 5 redirect() -> back() -> withInput() -> withErrors()

### ISSUE THREAD

**Issue by thepenguin1** [1000hz/bootstrap-validator#361]
Discovered an issue...

When using Laravel 5's function to send a user back to a previous page following server side validation failure, Bootstrap Validator is removing post back data and errors.

Here is an example of the Laravel code which BS Validator corrupts:

    $result = Validator::make(request() -> all(), ["user_name" => "required|email|min:5|max:50"]);

    if ($result -> fails()) 
    { 
        return back() -> withInput() -> withErrors($result); 
    }

and the HTML (which I'm guessing BS Validator modifies)

    
    <div class='col-sm-6 form-group has-feedback {{ $errors -> has("user_name") ? " has-error" : "" }}'>
                                
        <label for="user_name" class="col-sm-3 control-label">{{ trans("messages.page_register_label_username") }}</label>
        <div class="col-sm-9 form-group-sub">
            <input tabindex="3" class="form-control input-sm" required="required" data-minlength="5" data-maxlength="50" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" name="user_name" type="text" id="user_name" value="{{ old('user_name') }}">
            <span class="fa fa-info-circle form-control-feedback" data-toggle="tooltip" data-placement="right" title='{{ trans("validation.username", ["min" => "5", "max" => "30"]) }}'></span>
            @if ($errors -> has("user_name"))<span class="help-block"><strong>{{ $errors -> first("user_name") }}</strong></span>@endif
        </div>
        
    </div>

**Comment by thepenguin1** [comment]
Does the Validator reset form values / errors when it starts for the first time? be it via a $("form").validator() method call or using data-toggle="validator"?

**Comment by 1000hz** [comment]
It doesn't touch any values, but I think the errors would be uninitialized. A potential fix for this would be to run the validators on any fields with values in them upon initialization.

**Comment by thepenguin1** [comment]
Could you explain a bit more? Simply removing the data toggle attribute (not initialzing the validator object) fixes it

**Comment by thepenguin1** [comment]
Ah wait I think I get it. What would be the best way to do that. As just using the data toggle on the form isn't getting it done.

**Comment by thepenguin1** [comment]
Problem is though that the old data doesn't seem to be retained. Eg inputs are cleared.

**Comment by 1000hz** [comment]
When you say data are you referring to the input values or errors?

**Comment by thepenguin1** [comment]
Both. Using the Laravel old helper method (see first post) and accessing $errors

**Comment by 1000hz** [comment]
`$errors` are server-side, so they won't be available to the validator plugin. My suggesstion above was to run field validators on any field that has a value when the plugin is initialized (with `.validator()` or `data-toggle="validator"` but that will only work if the input values are preserved)

**Comment by thepenguin1** [comment]
I'll have to test it tomorrow. But a var dump reveals the data is there (as does not initialising the validator). I'll see what I can discover and report back.

**Comment by thepenguin1** [comment]
I fixed the issue. I started again with an unminifed version and made a few minor changes (not related to the issues I was having) and it is working fine. No need to modify any code :)
