### ISSUE TITLE
Invalid select field doesn't revalidate until I choose two new options

### ISSUE THREAD

**Issue by Gillettlw** [1000hz/bootstrap-validator#363]
The problem I am having is that when a select on my form validates as invalid for whatever reason (submit button, user clicks away from the select etc.) it will then not validate as correct when a valid option is chosen for the first time.

If the user chooses a different option it will then validate just fine for some reason. It seems like the Value of the field is not updating from the initial blank option but I have no idea why. Can you help?

No JSBin, but this is the page I am having problems with:
http://www.swgs.wilts.sch.uk/forms/OptionChoices/

**Comment by 1000hz** [comment]
I think you're running into #293. Closing this ticket as a duplicate. I'm going to try to work on the plugin a bit this weekend and will hopefully push a fix for this soon.

**Comment by Gillettlw** [comment]
Same sort of problem yeah, except I'm having it on IE rather than Safari. Chrome works fine though.
