### ISSUE TITLE
Submit button disabling not working with Telerik Kendo UI observables

### ISSUE THREAD

**Issue by rwb196884** [1000hz/bootstrap-validator#364]
https://jsfiddle.net/eq1gyks7/

Enter something invalid such as <code>!!!</code> and it fails validation and disables the submit button as expected.

However, when you then enter something valid into the form such as <code>name</code> the form does not then validate.

(In my actual work I also have the problem that validation is not run following changes in the value bound to the form element, and the submit button is not disabling when validation fails.)

**Comment by 1000hz** [comment]
Your `oninvalid="setCustomValidity('...')"` call is interfering with the validator's state. You should use `data-error="..."` to specify your error message.
