### ISSUE TITLE
submit button not being disabled in bootstrap 4

### ISSUE THREAD

**Issue by JamesBLewis** [1000hz/bootstrap-validator#367]
it seems in bootstrap it won't disable the forms submit button even when it isn't valid. i can only assume this is because they have changed the way disabling of buttons works in bootstrap 4

**Comment by QuadeHale** [comment]
I don't see why this is an issue when the docs show Validator is for Bootstrap 3, and Bootstrap 4 is still in alpha.

**Comment by 1000hz** [comment]
Closing this for now. Will revisit when Bootstrap 4 gets closer to release.
