### ISSUE TITLE
Submit button disabling and form valdiation not working for bootstrap modal

### ISSUE THREAD

**Issue by suryaprakashdps** [1000hz/bootstrap-validator#369]
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog"
			tabindex="-1" id="myModal" class="modal fade">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title">Add Learning</h4>
					</div>
					<div class="modal-body">

						<form:form id="adminlearnform" role="form" data-toggle="validator"
							action="insertlearning.do" method="POST" commandName="learnvo">
							<div class="form-group">
								<label>Course/Certfication Name</label>
								<form:input type="text" class="form-control" id="coursename"
									placeholder="Enter course name" path="coursename"
									maxlength="30" data-minlength="5" required="required"
									pattern="[a-zA-Z0-9.]+" />
								<form:errors path="coursename" cssClass="error" />
								<div class="help-block with-errors"></div>
							</div>
							<div class="form-group">
								<label>Status</label>
								<form:select type="text" class="form-control" id="status"
									path="status" data-dropcheck="status" required="required">
									<form:option value="N">----</form:option>
									<form:option id="completed" value="Completed">Completed</form:option>
									<form:option id="future" value="Future">Future</form:option>
								</form:select>
								<form:errors path="status" cssClass="error" />
								<div class="help-block with-errors"></div>
							</div>
							<div class="form-group" style="display: none" id="doc">
								<label>Acquired date(MM/dd/YYYY)</label>

								<div data-date-format="mm/dd/yyyy" data-date-viewmode="years">
									<form:input type="text" placeholder="mm/dd/yyyy"
										class="form-control" path="doc" data-provide="datepicker"
										required="true" data-date-end-date="0d"
										data-date-start-date="-10y" data-date-today-Highlight="true" />
									<form:errors path="doc" cssClass="error" />
									<div class="help-block with-errors"></div>
								</div>

							</div>
							<%-- 	<div id="plandate" style="display: none">
								<div class="form-group">
									<label>Planned date(MM/dd/YYYY)</label>

									<div data-date-format="mm/dd/yyyy" data-date-viewmode="years">
										<form:input type="text" placeholder="mm/dd/yyyy"
											class="form-control" path="plan_date"
											data-provide="datepicker" required="true" data-date-end-date="0d" data-date-start-date="-10y"  data-date-today-Highlight="true" />
										<form:errors path="plan_date" cssClass="error" />
										<div class="help-block with-errors"></div>
									</div>

								</div>
							</div> --%>
							<div id="plandate" style="display: none" class="form-group">

								<label>Planned date(MM/dd/YYYY)</label>

								<div data-date-format="mm/dd/yyyy" data-date-viewmode="months">
									<form:input type="text" placeholder="mm/dd/yyyy"
										class="form-control" path="plan_date"
										data-provide="datepicker" data-date-start-date="2d" />
									<form:errors path="plan_date" cssClass="error" />
									<div class="help-block with-errors"></div>
								</div>

							</div>
							<div class="form-group">
								<label>Icalms Enrolled</label>
								<form:select type="text" class="form-control" path="icalms"
									data-dropcheck="quarter">
									<form:option value="N">----</form:option>
									<form:option value="Yes">Yes</form:option>
									<form:option value="No">No</form:option>
								</form:select>
								<form:errors path="icalms" cssClass="error" />
								<div class="help-block with-errors"></div>
							</div>
							<div class="form-group">
								<label>Quarter</label>
								<form:select type="text" class="form-control" path="quarter"
									data-dropcheck="quarter">
									<form:option value="N">----</form:option>
									<form:option value="Quarter 1">Q1</form:option>
									<form:option value="Quarter 2">Q2</form:option>
									<form:option value="Quarter 3">Q3</form:option>
									<form:option value="Quarter 4">Q4</form:option>
								</form:select>
								<form:errors path="quarter" cssClass="error" />
								<div class="help-block with-errors"></div>
							</div>

							
								<button type="submit" value="Save" class="btn btn-primary">Submit</button>
								<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>

						
						</form:form>

					</div>
				</div>
			</div>

		</div>

**Comment by 1000hz** [comment]
You need to initialize the validator once the form is visible in the DOM. This means you need to remove `data-toggle="validator"` and instead initialize it via JS once your modal has been shown.

```js
$('#yourModal')
  .on('shown.bs.validator', function (e) {
    $('#adminlearnform').validator()
  })
  .on('hidden.bs.validator', function (e) {
    $('#adminlearnform').validator('destroy')
  })
```
