### ISSUE TITLE
How to check one element has error or not?

### ISSUE THREAD

**Issue by justin-john** [1000hz/bootstrap-validator#370]
We can force validation for one element in form by using `$(element).trigger('input')`. But here we cannot know whether the corresponding field has error or not? Any option to get the status of field.
```javascript
$(inputElement).isValid();  // OR
$(inputElement).hasError()
```

**Edit:**

I think, we can make force validation and then checking the container element has "has-error" class will give you any inputs that have errors.
```javascript
$(inputElement).trigger('input');
var $input = $(".has-error :input"); // OR input with corresponding identifier $(".has-error :input#firstname");
if ($input.length) { 
  // Errors found. 
};
```

Any suggestions on above solutions?

**Comment by 1000hz** [comment]
Checking if any form-groups have the `.has-error` class is the approach I recommend. You could also check `$input.data('bs.validator.errors')` which is an array.
