### ISSUE TITLE
Validator accepts whitespace in URL

### ISSUE THREAD

**Issue by MotherCake** [1000hz/bootstrap-validator#371]
Hi

I'm using an input field with "type=url". The URL "http://wel come.com" is accepted (With a space between l and c). This should be recognized by the validator.

**Comment by 1000hz** [comment]
Since this plugin offloads its native validators to the built-in browser validation API, and because the nuances of what constitutes a valid url vary so widely, I'm opting not to fix this in the plugin.

You can limit it to what you consider valid using the `pattern` attribute.
