### ISSUE TITLE
It does't disable submit button

### ISSUE THREAD

**Issue by mrdaghestani** [1000hz/bootstrap-validator#373]
Hello,
I'm using bootstrap-validator but I saw a problem.
When it initialized on a form that is not currently displayed, it doesn't disable submit button.
I'm calling initialization function on $(document).ready, but my form is "display:none;" until user  click a button.
Thank you.

**Comment by 1000hz** [comment]
Try using the new version v0.11.0 (it was released a few hours ago). It no longer ignores invisible form fields.

**Comment by davidholiday** [comment]
I'm running into a similar issue. Validator doesn't seem to actually disable the button, it just sets the :disable css property, which makes it look disabled. The button will still respond to click events. ended up having to put a bit of a hack: 

`       var cursor_state = $('#register_submit_button').css('cursor');
        if (cursor_state == 'not-allowed') { return; }`

at the top of the function behind the submit button to prevent unwanted method activation until the form was validated.

**Comment by 1000hz** [comment]
@davidholiday see https://github.com/1000hz/bootstrap-validator/issues/499#issuecomment-279806670
