### ISSUE TITLE
select2.github.io  problem with select2

### ISSUE THREAD

**Issue by Sandbird** [1000hz/bootstrap-validator#374]
I've been trying to solve this problem for 2 days now with no result.
select2.github.io is somehow changing the required tag to   required="", thus making the validator blind to it.
I've tried talking to the select2 guys....they sent me to stackoverflow....tried my luck there, noone responded....
Can someone please tell me what can i do when there is a select box with this format ?

`<select id="client_id" class="form-control select2-hidden-accessible" required="" tabindex="-1" aria-hidden="true">`

How can i make validator 'grab' required="" as well as simple **required**

Thanks

**Comment by 1000hz** [comment]
Try using the newly released v0.11.0

The problem isn't the `required` attribute, but that the actual select element is being hidden by select2 and replaced with a more visually appealing element. The old version of the validator ignored hidden fields by default whereas this new version doesn't.

**Comment by Sandbird** [comment]
http://jsfiddle.net/01nskzxk/1/
I've set up an example, using the latest validator and select2 to demonstrate the problem.
Even with the latest validator, its not working. The submit button shouldn't get activated since nothing was selected from the dropbox.

-Thanks

**Comment by 1000hz** [comment]
The plugin isn't actually being loaded in your fiddle. You can't use raw.githubusercontent.com as a CDN. Try loading the plugin from `http://1000hz.github.io/bootstrap-validator/dist/validator.min.js` instead.

http://jsfiddle.net/xm9qq7za/

**Comment by Sandbird** [comment]
Ok sorry, didnt know that :/ 
Ok the plugin is loaded now but still you see what i mean ? The button gets enabled once you input the username...Shouldnt it stay disabled till you select something from the dropdown first? (http://jsfiddle.net/xm9qq7za/3/   just updated with the link provided)

**Comment by 1000hz** [comment]
Just noticed a few more problems:
* You need to put your select and your username input in separate `.form-group` containers
* The value of your first placeholder option needs to be `value=""`

http://jsfiddle.net/xm9qq7za/5/

**Comment by Sandbird** [comment]
omg........yes that was a stupid example i gave....my actual code is too complex to use that...too many custom php functions making the placeholders....But i am surprised to see it work now ! It actually works! I must have a conflict somewhere because its not working on my end with my files.

Thanks, at least now i know that it works :)

**Comment by saidbakr** [comment]
It works with version 0.11.9, but the problem is that error styling and messages does not appear for select2
