### ISSUE TITLE
v0.11.0 breaks submit button validation error feedback when form-group contains both input/text and input/hidden

### ISSUE THREAD

**Issue by goog62** [1000hz/bootstrap-validator#376]
Cina,

Thanks for the new version! No good deed goes unpunished, though. Here's a fiddle that demonstrates a problem introduced in the update: https://jsfiddle.net/goog62/xr4qccn9/10/

My applications pair <input type="text"> elements with <input type="hidden"> within a single form-group. As you can see from the fiddle, when you click the submit button on an empty form, the form-groups with no hidden inputs get the has-error class attribute, the the one that includes the hidden input doesn't.

This used to work correctly in the prior version. Please advise.

Thanks!

Steve Kramer

**Comment by 1000hz** [comment]
I just realized I accidentally committed an earlier build of the plugin to the /dist directory. I'll need to cut another release. Thanks for bringing this to my attention!

**Comment by 1000hz** [comment]
False alarm, I only screwed up the version hosted in the docs.

**Comment by 1000hz** [comment]
Pushed an update to the docs and your fiddle is fixed!
