### ISSUE TITLE
NPM Package does not export the `Validator` variable

### ISSUE THREAD

**Issue by niftylettuce** [1000hz/bootstrap-validator#378]
We cannot use this with NPM as it does not export the variable/constructor.

**Comment by 1000hz** [comment]
Yes, I was following the Bootstrap npm package's lead which also doesn't export its plugins as CommonJS modules. You're expected to `require('bootstrap')` / `require('bootstrap-validator')`, which will attach them to `jQuery.fn` as a side-effect. That means that `jQuery` is expected to be on `window`, which won't happen if you're also loading it via CommonJS.

To get it working, you'd need this in your app's entrypoint:

```js
var jQuery = window.jQuery = require('jquery')
require('bootstrap')
require('bootstrap-validator')
```

I agree that it's not ideal and kinda weird now that npm is widely being used for client-side packages, but one of the goals of this plugin is to keep it as congruous with Bootstrap's core plugins as I can. Unfortunately, they aren't planning UMD builds for v3 (twbs/bootstrap#14755). When this plugin eventually gets rewritten for v4 parity, I'll include a UMD build.
