### ISSUE TITLE
no matching scrollTop

### ISSUE THREAD

**Issue by GarethFox** [1000hz/bootstrap-validator#379]
Hi,

when using the plugin within a long scrolling form, we have the issue that on validating it, when error is occuring, the scrollTop is alway three scrolls bellow the first unmatching field...
Is there a way to calibrate it by our own ?
We try to adjust it within the following line without success...
`0!==b.length&&(a(document.body).animate({scrollTop:b.offset().top-d.FOCUS_OFFSET},250),b.focus())}}`

Thx

**Comment by 1000hz** [comment]
You can set `$.fn.validator.Constructor.FOCUS_OFFSET` to what you need. That value needs to be the number of pixels you want from the top of the viewport to the top edge of your input.

Take a look at the example of how the fixed navbar in the docs page is accounted for.
https://github.com/1000hz/bootstrap-validator/blob/master/docs/assets/js/application.js#L20-L22
