### ISSUE TITLE
problem with select2 plugin

### ISSUE THREAD

**Issue by AviFix** [1000hz/bootstrap-validator#38]
hi

when validating a form with the jquery-ui (combobox) plugin.

http://jqueryui.com/autocomplete/#combobox

while validating... all select lists pop open.
example:
http://jsfiddle.net/tLcqs0ak/1/
thanks allot
Avi

**Comment by 1000hz** [comment]
Finally got around to tracking the cause of this down. It's because the plugin is triggering an `input` event on all fields to trigger validation.  I need to namespace these event triggers to avoid calling any other third-party input event handlers by accident. It will be fixed in the next release.

**Comment by AviFix** [comment]
Thanks alot

Avi
