### ISSUE TITLE
Custom selector option and Error message shows up on another's .help-block .with-errors element

### ISSUE THREAD

**Issue by xxRockOnxx** [1000hz/bootstrap-validator#381]
How can I use custom selector for errors programatically if possible ?

I am restricted on putting .help-block and .with-errors. I would like to use different classes or even IDs.

~~I know there's data-error and data-*-error attributes that I can use, but I think it'll be better with the JS way.~~

data-error and data-*error are for messages.

Having an option to where you can manually specify a class/id helps a lot.

I even have this another problem where an error message shows up on another's .help-block .with-errors paragraph/div.

![error](https://cloud.githubusercontent.com/assets/11251134/17014962/09b74252-4f5a-11e6-986c-aae648a1fc1f.png)

**Comment by 1000hz** [comment]
If errors are showing up for the wrong fields, you probably have multiple fields inside of the same `.form-group`. You can only have one field per group.

As far as supporting other classes goes, you'll have to fork the plugin. Alternatively, you might be able to rig something up by listening for `valid.bs.validator` and `invalid.bs.validator` and getting the error messages off `event.detail` and copying them to your target container.

**Comment by xxRockOnxx** [comment]
> If errors are showing up for the wrong fields, you probably have multiple fields inside of the same .form-group. You can only have one field per group.

Well cause 2 radio button? And I think they are grouped so... it should be in the same form-group.

But anyway, for some reason it suddenly fixed itself. Did you make a new commit? I am using your library that is on cdnjs. When I came back to continue my project it without having modifying anything yet... it's all good.
