### ISSUE TITLE
data-validate not working

### ISSUE THREAD

**Issue by xxRockOnxx** [1000hz/bootstrap-validator#387]
I have a select that is being selectize (selectize.js) and I know that it will make the original select display:none so I added data-validate="true" on the original select element.

Calling validator('validate') does not include that select. I thought adding data-validate includes it in the validation??

**Comment by 1000hz** [comment]
Can you post an example on JS Bin?
http://jsbin.com/mirekiforo/1/edit?html,js,output

**Comment by xxRockOnxx** [comment]
http://jsbin.com/xokiguxemu/1/edit?html,js,output

**Comment by 1000hz** [comment]
Your example was throwing a ReferenceError because you were accessing the variable `form` without it being defined.

I changed it to `$('form')` and it's working now.
http://jsbin.com/gubeyaheco/1/edit?html,js,output

**Comment by xxRockOnxx** [comment]
Don't see any errors http://jsbin.com/kabavadepi/2/edit?html,js,output

No more reference issue. The one you gave has one.

**Comment by 1000hz** [comment]
Your first example:
![image](https://cloud.githubusercontent.com/assets/1395018/17350268/c905f22c-58ea-11e6-8338-2967f21f8499.png)

My example:
![image](https://cloud.githubusercontent.com/assets/1395018/17350297/054a7b04-58eb-11e6-9ca6-2f6adbe5e3e9.png)


Your new example:
![image](https://cloud.githubusercontent.com/assets/1395018/17350312/2d090da4-58eb-11e6-88f2-3fb93092afbb.png)

As you can see, your new example and my example behave the same way, with error messages being shown if the field is interacted with and a value is not chosen..

**Comment by xxRockOnxx** [comment]
Ok, I think now know how to make the error come out. We had a bit of misunderstanding I guess? How did you make the errors come out? Cause when invoking the validate upon pressing the submit button, the error would not come out. I can only make it come out if I click on the select and then click outside to make it "blur" then that's when the error would come out.

Is this the expected behavior sir?

**Comment by xxRockOnxx** [comment]
We had a misunderstanding here.

calling form.validator('validate') upon clicking of the button does not show the error. Please reconsider this issue.

**Comment by 1000hz** [comment]
Looks like the issue is that selectize is creating the replacement dropdown inside of the same form-group. The selectize dropdown has an input inside of it that's clobbering the form-group's errors, so the validator thinks the field is ok.

You can tell the validator to ignore the selectize input by adding this line to your code:
```js
$.fn.validator.Constructor.INPUT_SELECTOR += ':not(.selectize-input input)'
```

http://jsbin.com/pusagasisu/edit?html,js,output

**Comment by xxRockOnxx** [comment]
Thanks! This is really helpful

**Comment by xxRockOnxx** [comment]
So, again, data-validate has some issue if being changed dynamically, even if update is called.
Look at the jsbin I made:

http://jsbin.com/zeqaqizege/edit?js,console,output

Is the update meant for new input elements being inserted or any changes on the form? Cause for sure it does not work. Look at the console.log also. I make it sure that the values are changed.

Thanks again for considering this issue.

**Comment by xxRockOnxx** [comment]
Ok, tried experimenting. Using .attr() works, but .prop() and .data() doesn't.

Seems like it's the plugin that has problem now and not me or jQuery bug or anything. Tried on Chrome and Firefox. Are you reading the data-validate using .attr() instead of .data() ? Seems like it is

**Comment by 1000hz** [comment]
Yeah, you need to use `.attr()`. Here's a slightly updated example
http://jsbin.com/zeqaqizege/edit?html,js,console,output

I should probably clear out the errors from fields with `data-validate="false"` and also update the Submit button status after `.validator('update')`

**Comment by xxRockOnxx** [comment]
Saw that you were doing: https://github.com/1000hz/bootstrap-validator/blob/master/dist/validator.js#L91
that. Is it possible if you'll be filtering what you have found using .data() instead? Would like to make a pull request but I don't know how to do it hahaha

**Comment by xxRockOnxx** [comment]
**Solution for errors not being removed after update / Still being validated after data-validate="false"**

Instead of setting data-validate="false" via .attr(), just remove that property/attribute instead using .removeProp()

Then do .validator('update') afterwards.

Hope the author @1000hz will fix these issues.

Hopes these updates will become possible:

- Set the data-validate using .data() (Some users on #jQuery channel at freenode recommends it that way because of performance stuffs).

- data-validate="false" on .validator('update') still being validated. Maybe because it is still included in the "SELECTOR" variable/property and not being removed. Hope this will be fixed too.
