### ISSUE TITLE
Error message not clearing up on Firefox

### ISSUE THREAD

**Issue by xxRockOnxx** [1000hz/bootstrap-validator#390]
The issue:

1st step = open up the modal with a form inside.
2nd step = press tab on a required input to skip to the next one.
3rd step = supposedly, it'll show up the error that it is required.
4th step = close the modal
5th step = open it up again.

Results:

Chrome = no issues. No red border inputs. No error message.
Firefox = the last input where you landed has the red border and message. Close and open it up again... that's when the input will be cleared... on the 2nd close/open of modal.

So since it is working on chrome, thought I can just post up just the code to tidy things a bit:

```
            // Reset everything inside modal every time it closes
            modal.on('hidden.bs.modal', function(event) {
                addMode();
                resetForm();
                resetData();
            });

            function resetForm(){
                form.validator('destroy');
                form.trigger('reset');
                form.validator();
            }`
```

Not sure if browser issue or code. Thought of posting this to make you aware of it.

**Comment by 1000hz** [comment]
Can't reproduce in Firefox 48.0 on Mac
http://jsbin.com/pevovowapu/edit?html,js,console,output

**Comment by xxRockOnxx** [comment]
Hmm, I can't seem to open the modal in your example.
Firefox 48.0 on Fedora 24 Gnome 3.

**Comment by 1000hz** [comment]
Weird. Does it open up if you remove `data-toggle="validator"` from the form element? If not, then there's probably some other issue unrelated to this plugin.
