### ISSUE TITLE
Set form as invalid until Google ReCaptcha is not filled in

### ISSUE THREAD

**Issue by micheledallatorre** [1000hz/bootstrap-validator#392]
Is it possible using your validator to make somehow a form, that cointains a captcha such as https://www.google.com/recaptcha/intro/index.html, invalid until the captcha is filled in?

E.g. by adding a custom validator to the captcha or something similar.

I have been trying with no luck so far.

Thanks a lot!

**Comment by micheledallatorre** [comment]
Found this solution. :+1: 
http://stackoverflow.com/questions/30018213/recaptcha-2-0-enable-submit-button-on-callback-if-recaptcha-successful

**Comment by 1000hz** [comment]
Here's a complete example of reCAPTCHA working with this plugin.
http://jsbin.com/kirevujexa/edit?html,js,output
