### ISSUE TITLE
Select with multiple attribute initially has error validation on page load

### ISSUE THREAD

**Issue by ArcadeRenegade** [1000hz/bootstrap-validator#393]
Steps to reproduce:
- Create a form with the [data-toggle="validator"] attribute.
- Add to the form a select element as a .form-control with the [multiple] and [required] attributes.
- Load web page
- Select element has error initially on load

![image](https://cloud.githubusercontent.com/assets/13874898/17540298/d8396ace-5e69-11e6-8ca7-f85f158bb3a7.png)

**Comment by pgs-pliulia** [comment]
Hi, i have the same errors and i find why. **As of jQuery 3.0, if no options are selected, it returns an empty array; prior to jQuery 3.0, it returns null.** So, if you have < jQuery 3.0 the validation will fail. I will try to fix that in the weekend

**Comment by desfero** [comment]
JSBin for this issue: JSBin: http://jsbin.com/foyogogogo/edit?html,output
Can any one add **Bug** label?

**Comment by 1000hz** [comment]
Seems like maybe it wasn't the best idea to automatically validate fields on plugin init. This is also causing problems for people in #401.

I think I'll revert the changes from #350 and leave it up to people who want that behavior to trigger validation themselves.

**Comment by desfero** [comment]
If we revert changes, it will not help. Current issue is because of logic which check if values is empty is incorrect due to changes in jQuery >= 3.0 where .val() function return empty array for <select> with multiple attribute prior to jQuery 3.0 it returns null,

**Comment by desfero** [comment]
@1000hz i submit a pull request to fix this issue
