### ISSUE TITLE
Validator is not a function.

### ISSUE THREAD

**Issue by sreekanth009** [1000hz/bootstrap-validator#398]
Uncaught TypeError: (0 , _jquery2.default)(...).validator is not a function

I am getting this error, when I import through react.js.

**Comment by 1000hz** [comment]
You need to be sure jQuery is imported before the validator. 

You only need to import this plugin once, by the way. I'd suggest requiring jQuery followed by all of your plugins in your entrypoint file. Then you just require jQuery wherever you need it and it should have all the plugins available already.

**Comment by sreekanth009** [comment]
Hey Thanks, actually the problem was jQuery was loading two 2 times.. before and after the bootstrap-validator initialising.

I have removed the duplication of jQuery then it worked for me.
