### ISSUE TITLE
Auto append help-block?!

### ISSUE THREAD

**Issue by TheVaan** [1000hz/bootstrap-validator#4]
It would be nice if help-block would be appended to parent element automatically so you don't have to put that many empty elements to the form.
Do you think it's possible?

**Comment by niftylettuce** [comment]
Bootstrap V4 is incompatible with `bootstrap-validator` due to <https://github.com/twbs/bootstrap/pull/19141#issuecomment-233172275>

**Comment by niftylettuce** [comment]
Please re-open until they uncomment the absolute positioning for icons and such.
