### ISSUE TITLE
Prevent immediate validation of fields with values?

### ISSUE THREAD

**Issue by yuloh** [1000hz/bootstrap-validator#401]
Hello,

I just updated and the changes from #350 are causing some problems for me.  Here is what is happening:
- I return the old input from the server for every input field, so the field is initialized with the old value.
- I set the class 'has-error' on the form group if there is a server error and render a message.
- When the validator initializes, it validates the field because of the changes that resolved #350
- Since the field can only be validated server side, the validation passes.
- After validation passes the 'has-error' class is removed, even though I have a server error.
- Since this happens on initialization, the client doesn't have a chance to see the error state.

[Here is a fiddle](https://jsfiddle.net/ea5vkywL/2/) that might help explain what I'm talking about.

What do you think about making this behavior something that can be disabled?

**Comment by Dortamur** [comment]
I have a similar issue.
I perform server-side validation, which is more thorough than the client-side validation, so in some instances, the client-side validator will think a field is valid, yet after submitting to the server, the server has determined it to be invalid, and has re-rendered the form with a form-group with 'has-error', and pre-populated error message.

Ideally, I'd like it to _not_ run validation when the page first loads, until the field value is changed. And when it _does_ run, to remove the server-side generated error text.

**Comment by chrisribe** [comment]
+1

**Comment by 1000hz** [comment]
I think I'll revert the changes from #350 and leave it up to people who want that behavior to trigger validation themselves. See also #393.

**Comment by MrLexLewis** [comment]
+1
