### ISSUE TITLE
Submit button still fires submit even when disabled

### ISSUE THREAD

**Issue by dunkmann00** [1000hz/bootstrap-validator#403]
I have a form where I catch the pressing of the submit button using jQuery submit(). Even when the form is not valid and the submit button looks disabled, when it is pressed, the event fires and the javascript is executed.

I tested this without listening for the event and it worked as expected, not doing anything on the button press when it was disabled. I think the problem lies in that bootstrap-validator will prevent the button from performing its default action by catching the event and first checking if the form is complete. If it isn't it calls preventDefault(), otherwise it lets the event continue. So any other function attached to the submit() event still will receive it regardless of whether bootstrap-validator blocks the default action or not.

In my case I changed bootstrap-validator to add the disabled tag rather than the disabled class and that seems to do the trick, as no submit event happens.

Line 283
```javascript
Validator.prototype.toggleSubmit = function () {
    if (!this.options.disable) return
    this.$btn.prop('disabled', this.isIncomplete() || this.hasErrors())
  }
```

Line 318
```javascript
this.$btn.prop('disabled', false)
```

Perhaps you should consider making this change?

**Comment by 1000hz** [comment]
This behavior is intentional. Not setting the `disabled` prop allows the form submit to be attempted which reveals the form's errors to the user so they can fix them. If the form was actually disabled, that would be possible and the user would be stuck trying to figure out why they can't submit the form.

**Comment by 1000hz** [comment]
You should check `if (e.isDefaultPrevented())` before you take any actions in your submit handler.

**Comment by dunkmann00** [comment]
Thanks 1000hz, that seems sensible I'll check out that method you suggested. Just curious, doesn't the form reveal errors as you click into different fields and after not changing the current field for a second or two?

**Comment by 1000hz** [comment]
Yes, but if the user accidentally skipped over a not-so-obviously required field, it could be frustrating.

**Comment by dunkmann00** [comment]
Oooh okay, I completely understand now. I just tried it and see what you mean. Awesome.

**Comment by dunkmann00** [comment]
Only thing I would have to say, which is now happening with what I'm trying to do, is if bootstrap-validator's event handler is not called first, checking `e.isDefaultPrevented()` won't work because `preventDefault()` hasn't been called yet.

**Comment by 1000hz** [comment]
Yeah, you have to be sure to attach your submit handler after the plugin is initialized (and also detach/reattach it if you destroy and reinitialize the plugin). Kinda sucks, but that's just the way it's gotta be.

**Comment by dunkmann00** [comment]
Overall its a great tool though, really nice work. I've used it several times actually. And I actually just saw on your site where you mention about using `isDefaultPrevented()` and to add the handler after its initialized....sorry for not noticing that sooner, should've read to the bottom of the docs lol.

**Comment by bhavyanarula** [comment]
Hi @1000hz, I am using form on bootstrap modal, following all steps of initializing only after modal shows, and then even destroying validator on hiding modal.

Everything works fine (e.isDefaultPrevented() returns me true when the form is invalid), but in my use case, I am using different submit actions of the same form. On modal show I switch the submit handler depending upon a condition.
Simply changing the submit handler was not working correctly as sometimes the other action gets submitted. The submit started to respond correctly only when I unbind submit before setting the correct submit action. But this has again made the isDefaultPrevented() respond wrongly inside the submit event. (false even when the form is invalid) 

Please help me out here. I am getting sleepy right now so let me know if you need code snippets, I will add them if required.
