### ISSUE TITLE
Dynamically adding/removing data-remote does not work

### ISSUE THREAD

**Issue by manju16832003** [1000hz/bootstrap-validator#404]
Hi,
I'm using v0.11.0.
I have a field at times I need to use data-remote to validate and remove it dynamically when I don't need to validate.

`element.removeAttr("data-remote");`
It does remove `data-remote` from the input element, but it will still send request to remote. Is plugin is caching the elements?
I did try to update the validator right after removing attribute
`element.removeAttr("data-remote");
                $(this).validator('update');`

Is data-remote is been cached even after removing?

**Comment by 1000hz** [comment]
You'll also need to call `element.removeData('remote')`.

**Comment by manju16832003** [comment]
@1000hz Thanks for reply, appreciate that.
However I choose to solve this issue at the server side. I would send extra parameter to server to return 200 OK when I don't need to do the validation.

Example:
When I don't need to validate
`http://host/exists?validate=false return 200 OK`

When I need to validate
`http://host/exists [Return 200 OK if not exists, 400 Record Exists]`
