### ISSUE TITLE
Improvement: `instance` function to get form `Validation` object

### ISSUE THREAD

**Issue by maitscha** [1000hz/bootstrap-validator#405]
Hi!

Your validation plug-in works really great, i highly appreciate the flexibility, how to define custom validators, and implement custom validation behaviour.

I would like to point out how this validation jQuery plug-in can be customized, by getting the `Validation` instance, holding the state of the form validation. Perhaps you can add this to the documentation:

```javascript
    let validator = $("form").data('bs.validator');
    // triggers the validation
    validator.validate();
    // check if we have any errors
    validator.hasErrors();
    // true
    validator.isIncomplete();
    // false
```

It is also possible to attach custom validators to the `Validator` instance of the form:

```javascript
    validator.validators["valid-false"] = ($elem) => false;
```
Which can now be used by input elements.

An `instance()` function, one like in the jQuery UI widgets, would be useful:

```javascript
    let validator = $("form").validator("instance");
    ... do something with the Validator instance
```

The validator plug-in supports to call the 3 functions `update`, `validate` and `destroy`, but the result value of these functions is not returned to the caller, because the functions are called within the for-each function body:
```javascript
  function Plugin(option) {
    return this.each(function () {
      var $this   = $(this)
      ...
      if (typeof option == 'string') data[option]()
    })
  }
```
Perhaps this behaviour could be changed to actually return the result value of the function call.

**Comment by 1000hz** [comment]
These are good suggestions, but this plugin is designed to have the same conventions as Bootstrap core jQuery plugins, so I won't be introducing an `instance` method. The overview of the docs link to Bootstrap's plugin overview sections, which mention you can call `.data('pluginName')` to get an instance. (See http://getbootstrap.com/javascript/#js-programmatic-api). It might be worthwhile to call special attention to easily-overlooked details in that section.
