### ISSUE TITLE
Multiple error messages

### ISSUE THREAD

**Issue by Rahool88** [1000hz/bootstrap-validator#406]
How do I show multiple error messages. For example before email is validated, it should say this field is required and then should check for its pattern validation.

**Comment by 1000hz** [comment]
http://jsbin.com/haxitopija/edit?html,css,js,output

**Comment by caneta** [comment]
Without introducing a custom pattern like in the fiddle, I used the following:
```
<input
   name="email"
   class="form-control"
   type="email"
   data-required-error="Email field is mandatory!"
   data-type-error="Mail address invalid"
   required
/>
```
