### ISSUE TITLE
Validate don't work after append

### ISSUE THREAD

**Issue by arshie92** [1000hz/bootstrap-validator#408]
Hello.
I want to validate a dynamic form.
So when I use Jquery append() method to edit the form, validate don't work on the news fields.
Even if I use $(...).validator('update').

**Comment by 1000hz** [comment]
It works.

http://jsbin.com/fejesutuza/edit?html,js,output
Here new fields will start being validated after you click the update button.

**Comment by arshie92** [comment]
Oh damn. The validator js file was the problem. I download the one called in that HTML code and it works. Thanks.
