### ISSUE TITLE
Custom validator not working after updating plug in from v0.10.2 to v0.11.5

### ISSUE THREAD

**Issue by piratolo** [1000hz/bootstrap-validator#410]
Hi,
in my web application, I updated your plug-in, from **v0.10.2** to **v0.11.5**, since i needed `.validator('update')`.
After the update, my **custom validators** doesn't work anymore. On my web page, I always get the error message, so I suppose that my custom validators return always **false**.
This is my custom validator

```

$('.formClassName').validator({		
    custom: {
         'validazionedata': function($el) {   
               ...
               // I force the validator to return true     	 
               return true;        	     	
         }
    },
    errors: {
    	'validazionedata': "Formato data errato"
    }}).on('submit', function (e) {...});
```

My custom validators work perfectly if I return to the version **v0.10.2** (I don't even need to change a single code line of my custom validator).

Does anybody understand why and how to solve the problem??

Thank yoi in advance

**Comment by 1000hz** [comment]
Check out the breaking change to custom validators in v 0.11.0:
https://github.com/1000hz/bootstrap-validator/blob/master/CHANGELOG.md#0110

Custom validators should now return an error message string if the field is invalid. As a result, you also no longer need to define an `errors` option.
