### ISSUE TITLE
Translate email errors

### ISSUE THREAD

**Issue by bash88** [1000hz/bootstrap-validator#413]
Hi,

I'd like to translate all the email error messages but I can't find the values or how to alter them anywhere. Is this at all possible and if so, could you point me to where to edit?

Regards,
Bas

**Comment by 1000hz** [comment]
The browser should automatically translate any built-in error messages depending on the locale of the user. Still, you can override type error messages by setting a `data-type-error="Custom Error Here"` attribute on the element. Same goes for any other error, like if the user didn't fill out a required field: `data-required-error="Fill this out!"`
