### ISSUE TITLE
Submit form with file even when input its required 

### ISSUE THREAD

**Issue by danielmogin** [1000hz/bootstrap-validator#414]
I`m using your example here to validate file input but it looks like when a user tries to submit the form with no file the submit button will work just fine.

Can you guide me on how to prevent this kind of behavior? I have also tried to make my if statement verify if the file size its >0 but its working just doing the same.  

http://jsbin.com/gerihevobe/edit?html,js,output

**Comment by 1000hz** [comment]
your custom validator is throwing an error which keeps the rest of the validator from working. You need to check to make sure the file object exists before trying to access its size.

```js
$('form[data-toggle="validator"]').validator({
  custom: {
    filesize: function ($el) {
      var maxKilobytes = $el.data('filesize') * 1024
      if ($el[0].files[0] && $el[0].files[0].size > maxKilobytes) {
        return "File must be smaller than " + $el.data('filesize')/1000 + " MB."
      }
    }
  }
})
```
