### ISSUE TITLE
custom error format and ajax check

### ISSUE THREAD

**Issue by t0n1zz** [1000hz/bootstrap-validator#417]
hi so i have 2 question about how to use this.
1. how to change the format for error message? since i see when there is more than 1 error message it will turn into unordered list... how to change it like just adding comas or so? since it just make my user interface look ugly...

2. i read that this js can do ajax validation, so how to use ajax to check if username that i typed is already exist in my mysql database?

**Comment by 1000hz** [comment]
1. You can kinda do it via css. http://jsbin.com/zibositumu/edit?html,css,output
2. Make a server endpoint that returns a 400 error if the username already exists. See https://github.com/1000hz/validator-remote-example for a reference.
