### ISSUE TITLE
How to implement a 'require if'

### ISSUE THREAD

**Issue by andrews05** [1000hz/bootstrap-validator#418]
I'm currently using v0.9 and have all my validation working correctly but I'm wanting to update the latest version and have gotten stuck with some of my custom functions.

I have a field that I want to be required only if a checkbox is checked, but optional if it isn't checked. I have a custom function which is supposed to be checking for this but the changes in v0.10 mean the function no longer runs when the field is empty. Is there any way to do this now?

**Comment by 1000hz** [comment]
You don't need a custom validator for this. Just toggle the `required` attribute on your input whenever the user checks/unchecks the box.

**Comment by andrews05** [comment]
Yeah I guess that'll work, I was just hoping to have something more reusable. On v0.9 I just define my 'requireif' validator and then put 'data-requireif="#somecheckbox"' wherever I need it.
