### ISSUE TITLE
how to validate decimal value by bootstrap validator

### ISSUE THREAD

**Issue by mammamSou** [1000hz/bootstrap-validator#420]
if my html input type is number. if i have value is 8.90.. its validated please enter correct number.... how to validate decimal value

**Comment by 1000hz** [comment]
You need to specify the right `step` on your input.  In your case, `step="0.1"`.

**Comment by mammamSou** [comment]
i am very new in this.. i cant get your point, my html is
<input type="number" name="a" id="a" value="2222.09" readonly >
my js is:
$('#aform').bootstrapValidator({
  a:{
    validators:{
      notEmpty:{
        message: 'This field is required and cannot be empty'
  }})

But i am geting error in "please enter valied number" but its valied.what to addd like step????please help

**Comment by 1000hz** [comment]
`<input type="number" name="a" id="a" value="2222.09" step="0.1" readonly>`

**Comment by mammamSou** [comment]
thank you sooooo much...
