### ISSUE TITLE
Is the custom validation still working?

### ISSUE THREAD

**Issue by ivanacorovic** [1000hz/bootstrap-validator#421]
Hello,

I need custom validation for making sure at least one of my checkboxes is checked. Now, as I could find from these issues, it has to be done through a custom validation, but I can't get it to work. Not even the validation from your example works for me.

    	$("#forma").validator({
		custom: {
		  equals: function($el) {
		    var matchValue = $el.data("equals") // foo
		    if ($el.val() !== matchValue) {
		      return "Hey, that's not valid! It's gotta be " + matchValue
		    }
		  }
	  }
	})

This is the html part:

		<form id="forma" data-toggle="validator" >
			<div class="form-group">
				<input type="text" class="form-control" data-equals="foo">
				<div class="help-block with-errors"></div>
			</div>
		  <button type="submit" class="btn btn-primary">Submit</button>
		</form>

**Comment by 1000hz** [comment]
It's working. http://jsbin.com/heliqerare/edit?html,js,output

You probably have an error loading the validator js file or something.

**Comment by ivanacorovic** [comment]
Sorry, so it has to be a required field if I am going to use the custom validator? When I leave "required" attribute out, it doesn't work. I was planning to use it to make sure at leat one checkbox is checked, and that kind of destroys the logic there.

**Comment by 1000hz** [comment]
Oh, yeah. That's how it works right now. It seems like this causes problems for some people's use cases, so I'll probably change this eventually when I have time. In the mean time, you can fork and get rid of the two conditions on this line:
https://github.com/1000hz/bootstrap-validator/blob/master/js/validator.js#L198

See also #334

**Comment by ivanacorovic** [comment]
Great, thank you very much!
