### ISSUE TITLE
At least 1 checkbox

### ISSUE THREAD

**Issue by dtomasi** [1000hz/bootstrap-validator#424]
Is it possible to validate (with custom validator) if at least on checkbox is checked?? I tried this, but it does not work ... Am I missing something? 

```
    $form.validator({
        custom: {
            checkboxLeast: function ($el) {

                console.log("Checking count of checked Checkboxes");

                if ($form.find('input[data-checkbox-group]:checked').length < 1) {
                    console.log("Error checkbox-least");
                    return ' - '
                }
            }
        }

    }).on('invalid.bs.validator', function (e) {
        $('#invalid-form-notice').show();
    }).on('valid.bs.validator', function (e) {
        $('#invalid-form-notice').hide();
    });
```

**Comment by dtomasi** [comment]
Ping!!!  Time is running off ... I need a solution till Sunday ... I really like this validator, but if it is not possible what to cover my needs, I need to look vor something else ... And I really don't want!!

**Comment by 1000hz** [comment]
Sorry, I'm on vacation right now. This is hard to do with the way the validator is currently designed and I need to think about firing more events. There are some other issues opened trying to solve this same problem with some suggested custom validators that might work, but that's the best I can offer now.

**Comment by dtomasi** [comment]
@1000hz THX for reply. So I will look for another solution. Have a nice holiday
