### ISSUE TITLE
Remote validation with headers 

### ISSUE THREAD

**Issue by eric7472** [1000hz/bootstrap-validator#425]
Hi,

On an update Account Form, I am trying to validate an email field against DB using remote validation. I need to set headers before sending the Ajax request (JWT) to check that email address is not existing in DB except for the logged user. Is there a way to do this easily ? 
I have tried the custom validation, this works nice but I have to handle both error display and style, and I don't know how to disable the submit button in this case...
Hope you can help.
Thanks

E.

**Comment by 1000hz** [comment]
There's not currently a way to intercept the ajax request to add headers. In the next version, I'll add support for returning promises from custom validators which would let you write your own ajax validator where you can add whatever you need to the request.

**Comment by eric7472** [comment]
Ok, thanks for your answer.

E.
