### ISSUE TITLE
Regex Pattern not working properly

### ISSUE THREAD

**Issue by premcodi** [1000hz/bootstrap-validator#428]
I am not able to make the regex patterns working.. i tested it with regextester.com but not working with input validation with the attribute "pattern".

Here are the few not working ones
```
^(?!.*[~!@#$§%&*()_+\-=?,.\{\}\[\]\\\/]{1,}$)
/[~!@#$§%&*()_+\=?,.\{\}\[\]\\\/]/
/[\:;~!@#$§%&*()_+\-=?,.\{\}\[\]\\\/]/
```

**Comment by 1000hz** [comment]
`^` and `$` are assumed with the `pattern` attribute, and also no `/` characters are used.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-pattern
