### ISSUE TITLE
How to manually trigger valid, invalid errors

### ISSUE THREAD

**Issue by premcodi** [1000hz/bootstrap-validator#429]
I am using a function to validate the input values on change event.
I want to manually call the validation error (valid, invalid) event in order to show/hide the errors.

I am doing like this now

```
$('#customerFirstName').on('input', function() {
  var regex = /[~!@#$§%&*()_+\-=?,.\{\}\[\]\\\/]/;
    var inputField = $(this).val();
    if(inputField.length > 0) {
      if(!regex.test(inputField)) {
        // valid
        $(this).trigger($.Event('valid.bs.validator', {relatedTarget: $(this)}));
      } else {
        // invalid
        $(this).trigger($.Event('invalid.bs.validator', {relatedTarget: $(this)}));
      }
    }
});
```

But the error messages are not displayed.

**Comment by 1000hz** [comment]
Use a custom validator instead.

**Comment by premcodi** [comment]
Can you please tell me how i can use the custom validator?

**Comment by 1000hz** [comment]
There's an example in the docs in the "Options" section.
http://1000hz.github.io/bootstrap-validator/#validator-options

Basically, you add a validator function that returns an error message string if the field is invalid. Then you add a data attribute to an input that matches the validator name. So if you named your validator `foo`, you'd add `data-foo` to your input.
