### ISSUE TITLE
Setting default required error message for all fields

### ISSUE THREAD

**Issue by vavrecan** [1000hz/bootstrap-validator#430]
Hi,
this is just a short tip how to make default message for all required fields without editing all input,select,textareas attributes:

$("input[required],select[required],textarea[required]").attr("data-required-error", "Please fill out this field.");

Or is there better way? :+1:

**Comment by 1000hz** [comment]
There's not currently a way to set default error messages for the browser-supplied validators. Your solution is the best approach.

**Comment by nunoarmando** [comment]
We can use this:

$.fn.validator.Constructor.DEFAULTS.errors = {
      match: 'Does not match - NEW TEXT',
      minlength: 'Not long enough  - NEW TEXT'
};

**Comment by 1000hz** [comment]
@nunoarmando This issue is about default error messages for browser-provided validators, such as `required` or `pattern`.
