### ISSUE TITLE
Trigger another validation of input box

### ISSUE THREAD

**Issue by Liyuchuan** [1000hz/bootstrap-validator#431]
There are two correlated relationship between the drop-down list box, zodiac and year, for example, has chosen the zodiac, how to choose the year triggered when validation of Chinese zodiac

**Comment by 1000hz** [comment]
You can trigger validation of a field by triggering the `focusout` event on it with `$('#myField').trigger('focusout')`. If I understand you question correctly, I think you could add an event listener on `change` of one field to trigger `focusout` on the others.
