### ISSUE TITLE
validator overruling binding errors from spring

### ISSUE THREAD

**Issue by JorisDeRieck** [1000hz/bootstrap-validator#432]
Hi,

We are using the bootstrap validator together with spring:mvc. We recently updated from version 0.10.2 to 0.11.3. But now the binding errors returned by the server-side are directly overruled by the validator on the input field itself (when loading the page you quickly see the message in red, but it becomes directly green afterwards).

This results in the error message shown in green (see attachment) and the input field is validated. In the older version the error messages was shown in red and the input field was not validated.

How can we fix this issue?

Kr,
Joris

![image](https://cloud.githubusercontent.com/assets/2060724/19995661/c1c90bbc-a259-11e6-86dc-2b0b486becc7.png)

**Comment by 1000hz** [comment]
This should be fixed now in v0.11.7
