### ISSUE TITLE
[question] How to manually trigger validation in tabbed form

### ISSUE THREAD

**Issue by beau-gosse** [1000hz/bootstrap-validator#433]
Great job on this very useful plugin!

I have a long form split across three tabs for better UX and I'm able to disable tab navigation buttons when a field in an active tab has an error. Once the error fields become valid, how do I enable my tab navigation buttons again? I need a little help with the logic.

Here's where I'm currently standing:
https://jsbin.com/yudipiquno/edit?html,js,output
```javascript
$(function() {
  // # Form validator
  var myForm = $("#myForm");
  myForm.validator();

  $(".btn-next").on('click', function() {
    var $button = $(this);
    myForm.validator().on('valid.bs.validator', function (e) {
      $button.prop("disabled", false).removeClass("disabled");
    })
    var hasErrors = myForm.validator('validate').has('.has-error').length;
    if(hasErrors) {
      $button.prop("disabled", true).addClass("disabled");
      return false;
    }
  });
})
```

**Comment by desfero** [comment]
This may help: https://jsbin.com/kigetarenu/edit?html,js,console,output

**Comment by beau-gosse** [comment]
@desfero thanks a bunch man! Exactly what I needed.

**Comment by desfero** [comment]
@beau-gosse your are welcome
