### ISSUE TITLE
Add a option to tell what buttons will be disabled

### ISSUE THREAD

**Issue by pmcfernandes** [1000hz/bootstrap-validator#435]
In asp.net webforms all button controls is submit behavior. Can you add an option to choose what controls will be disabled? An example, I have 3 buttons OK, Cancel and Delete and just want disable OK and user can use Cancel and Delete anyway.

**Comment by 1000hz** [comment]
No, this is a problem with asp.net's design. They should be `type="button`.

**Comment by pmcfernandes** [comment]
if I put type="button" not run server side code. Add just a option saying like submitControl: $(jquerycontrol) and all controls there will be disabled. This will not affect your code and if opttion passed use if not use normal validator its just a if
