### ISSUE TITLE
Added support for successful validation

### ISSUE THREAD

**Issue by dmbuchta** [1000hz/bootstrap-validator#437]
There doesn't seem to be any support for adding `has-success`. Basically I'd like my input box to glow green if it's passed validation. Is this currently possible?

**Comment by dmbuchta** [comment]
I just dug a little into the code and found that the clearErrors function actually removes the `has-success` class, so even a manual fix on the `valid.bs.validator` event will not fix this.

**Comment by 1000hz** [comment]
You need `.has-feedback` on your `.form-group`. Check out the twitter field on http://1000hz.github.io/bootstrap-validator/#validator-examples

v4 is not fully supported yet.
