### ISSUE TITLE
Document that the submit event gets default-prevented when form is invalid

### ISSUE THREAD

**Issue by 1000hz** [1000hz/bootstrap-validator#44]
There have been a few issues (#30, #35) asking how to check if the form in invalid in order to prevent some function from running on submit. Since the `submit` event gets `.preventDefault()` called on it if the form isn't valid, the docs should call attention to the fact that you can check `e.isDefaultPrevented()` to return early from a custom submit handler.

**Comment by cplaetzinger** [comment]
@downlite I'm experiencing a similar issue. It works if I enable validation before adding a custom listener on submit. Working example:
```
$('#myForm').validator();
$('#myForm').submit(function (event) {
     // my code
})
```

It does not in following case:
```
$('#myForm').submit(function (event) {
     // my code
})
$('#myForm').validator();
```

**Comment by 1000hz** [comment]
@cplaetzinger is right, the submit handler needs to be bound after the plugin is initialized, because jQuery event handlers are run in the order that they are bound.

There are a few approaches to solving the issue:
* Be sure to manually initialize the plugin on your form before you bind your submit handler:
```javascript
$('#form').validator().on('submit', function (e) { ... })
```
* Attach your submit handler after the window.load event has fired:
```javascript
$(window).on('load', function () {
  $('#form').on('submit', function (e) { ... })
})
```

**Comment by cplaetzinger** [comment]
@1000hz thanks for your reply. In my  case the form is displayed using bootstraps modal dialog. Thus I initialize the validator as well as my own listener once the dialog gets visible and destroy/remove them when the dialog gets hidden. Doing so the user can close and open die dialog several times and always starts with a clean validator.
