### ISSUE TITLE
Angular directives

### ISSUE THREAD

**Issue by JeffB42** [1000hz/bootstrap-validator#440]
My project uses Angular (1.5.8) and I'm looking into using bootstrap-validator.  I'm running into an issue though, with using it along with angular directives.  When a form and its controls are in a view/html page (that gets directly loaded), bootstrap-validator works.  However, if I refactor the form and its contents out of the page and into a directive, bootstrap-validator doesn't work.

To test & verify, I used the sample form that's on https://1000hz.github.io/bootstrap-validator/ and placed it in a directive.  In chrome, when I click submit, instead of bootstrap-validator's validation, I get chrome's default validation (a tool tip appears and says, "Please fill out this field").

If needed I can upload a sample project to demo the issue, but the basic repro steps are, in index.html, add a controller, and then add the form that's on the bootstrap-validator site, ala:

`<div ng-app="sampleModule" class="container">
    <div ng-controller="SampleCtrl as ctrl">
        <form data-toggle="validator" role="form">
			.
			.
			.
`

Verify this works, then refactor the form into a directive:

sampleDirective.js:
`<form data-toggle="validator" role="form">
			.
			.
			.
`

...and update index.html:
`<div ng-app="sampleModule" class="container">
	<div ng-controller="SampleCtrl as ctrl">
		<sample-directive></sample-directive>
		.
		.
		.
`

This might be related to the "On load doesn't work" issue that was recently posted.

**Comment by 1000hz** [comment]
> I get chrome's default validation (a tool tip appears and says, "Please fill out this field").

This means the plugin wasn't initialized on your form (or else `novalidate="true"` would have been set). Since you're rendering client-side, you can't rely on the data-api to initialize the validator for you on page load (since the load event has presumably already fired). You should initialize the plugin manually with `.validator()` inside your directive.

**Comment by JeffB42** [comment]
Thanks!  That was the issue.  If anyone else runs into this problem (using Angular and an Angular directive), here's my solution:

My view/template that's served up by the directive starts off with a <form> and has an id of "test-form":
`<form data-toggle="validator" role="form" id="test-form">
    ...
</form>`


Then in my directive, I added link() and am calling $timeout():
`myModule.directive("myDirective", ["$compile", "$timeout", function($compile, $timeout) {
	function link(scope, element, attrs) {
		$timeout(function() {
			$("#test-form").validator();
		});
	}

	return {
		restrict: "E",
		templateUrl: "myDirective.html",
		scope: true,
		link: link
	};
}]);
`
