### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by postme** [1000hz/bootstrap-validator#442]
Hi thank you very much for this excellent validator, would you happen to have a donation capability so I can substantiate my appreciation :-)
Kind regards
Meint

**Comment by 1000hz** [comment]
Thanks! If you feel compelled to donate, you may do so via PayPal at 
![image](https://cloud.githubusercontent.com/assets/1395018/20365733/a4a6bb16-ac0d-11e6-82b4-ed39fd3f8271.png)
