### ISSUE TITLE
Issue with all fields not validating on submit

### ISSUE THREAD

**Issue by JeffB42** [1000hz/bootstrap-validator#443]
Not sure if the is a "feature" or a bug, but for the site I'm working on, when a form is submitted we want all fields to be validated (as opposed to hitting submit, displaying a single error, fixing the error, hitting submit again, displaying (the next) single error, fixing the error, hitting submit again, etc...)

I've discovered that if a form-group has a help-block, and that if one goes to that field, and then submits the form, that only that field displays the error, and not all fields.  We can see this issue on the bootstrap-validator page itself... to repro:

1. go to https://1000hz.github.io/bootstrap-validator/
2. Click in the email input field
3. Click the submit button

results:
Only the email field error is displayed

expected:
all fields should display errors for invalid fields

Interestingly enough though, if I click the submit button again, all fields are then validated.

A slightly simpler and easier to see example, is a form with three required text fields:
`<form ...>
    <div class="form-group">
        <label for="firstName" class="control-label">First name</label>
        <input type="text" class="form-control" id="firstName" required />
        <div class="help-block with-errors"></div>
    </div>
    <div class="form-group">
        <label for="middleName" class="control-label">Middle name</label>
        <input type="text" class="form-control" id="middleName" required />
        <div class="help-block with-errors"></div>
    </div>
    <div class="form-group">
        <label for="lastName" class="control-label">Last name</label>
        <input type="text" class="form-control" id="lastName" required />
        <div class="help-block with-errors"></div>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>`

(sorry for the formatting - I don't seem to be able to get the markup editor github is using to format the code properly, so just copy-paste this into the text editor of your liking and format the snippet)

Create a page with this form, click in the first name input field, and then submit the form.  Only the first name field displays an error.

If you then refresh the page, and this time click in the middle name field, and then submit the form, only the middle name field displays an error.

In both cases, if you click the submit button a second time, all errors are then displayed, but we'd like to have all errors displayed when submitted.

**Comment by 1000hz** [comment]
It's happening because the error message that appears on the email field is pushing the submit button just out of range of your click. If you click the button on the bottom edge, it doesn't happen.

**Comment by JeffB42** [comment]
I didn't quite follow your explanation.  You are correct, in that when I click the submit button, the error message appears underneath the field, and the submit button (along with all the other controls) is moved down.  That's fine... the submit button isn't getting clipped or going out of the range of the window and is always 100% viewable, and always 100% clickable.

The issue is that, when I click on the submit button, only the input field that has the focus displays an error message, where as all of them should display errors if they don't pass validation.

**Comment by JeffB42** [comment]
UPDATE: OK, I think I understand what you are saying... click on the bottom portion of the submit button and it works, but click on the upper section or middle of the submit button and it doesn't.

It sounds like in order to work, the mouse needs to be OVER the submit button during the entire process, which is just bizarre to me... the mouse location shouldn't have anything to do with this.  Sure, it matters with the initial click, but once the submit event is fired, the location of the mouse shouldn't have anything to do it.

I've been reading through validator.js, as well as taking a stab at debugging the event, but haven't made much progress.  Can you think of a work around?

Thanks,

Jeff

**Comment by 1000hz** [comment]
Make your .help-blocks take up space even when they're empty.

**Comment by JeffB42** [comment]
Ah, thanks!  I was looking at it from a perspective of the JavaScript.

Jeff
