### ISSUE TITLE
Manually invalidate input

### ISSUE THREAD

**Issue by stockstatus** [1000hz/bootstrap-validator#446]
Hello,

could someone give me hint how to use bootstrap validator plugin to manually invalidate input field.
I have my input field like this:
`<div class="form-group">`
 `<input id="myinput'" class="customClass form-control " data-error="'+ validateNumber + '" pattern="-?` `[0-9]+([,.][0-9]+)?" required="required"/>`
`<div class="help-block with-errors"></div>`
`</div>`

everything works when i type bad value in input field - in this case string.
But is possible to manually invalidate this field if input contains some specific number value.
For example in my .js file:
`function invalidateField(somevalue){`
`if (!isCorrect){`
`//something like $("#myinput").invalidate`
`}`
`}`

I will appreciate any help. Thank You.

**Comment by 1000hz** [comment]
Sounds like you want a custom validator

```js
$('#myForm').validator({
  custom: {
    invalidnumber: function ($el) {
      var number = $el.data('invalidnumber')
      if ($el.val() == number) {
        return number + " is not a valid choice"
      }
    }
  }
})
```

```html
<div class="form-group">
  <input type="text" class="form-control" data-invalidnumber="6" required />
  <div class="help-block with-errors">Don't enter 6</div>
</div>
```

**Comment by stockstatus** [comment]
Hi,

thank you for an answer. All works now.
But is possible to manually invoke validation of input if some other input is changed. Lets say a have input **A** an input **B**. Input **A** changed and immediately change input **B** attribute, **not** value, and i need to validate this changed input **B**. I tried `$("#B").validate('update')`, `$("#B").trigger(''input)`, but no luck. Is this possible? Thank you very much for an answer.

**Comment by 1000hz** [comment]
```js
$('#A').on('change', function (e) {
  var $el = $(e.target)
  $('#B').attr('data-invalidnumber', $el.val()).trigger('focusout')
})
```

**Comment by stockstatus** [comment]
Thank you, but not working so far. It only work if i manually type some value into **B** input. Also tried different events like change, keyup, paste.

**Comment by 1000hz** [comment]
I thought I remebered the value returned by `$().data()` reflected any updates to a data-attribute set by `$().attr()` but it doesn't seem to be that way anymore.

Anyway, here's a working example with the the `$().data()` call in the custom validator replaced with `$().attr()`

http://jsbin.com/jalujelumu/edit?html,js,output

**Comment by stockstatus** [comment]
Hi, tried your approach, but still no luck. I tried to update validator plugin to version 11.5 but somehow whole plugin is not working. I have similar config as in your example.
```javascript
$('#myform_form').validator({
                    custom:{
                        "invalidnumber":function(data){
                            var testObj = checkMargin(data.attr("margin"),parseFloat(data.val()),parseFloat(data.attr("data-margin")))
                            console.log(marginObj)
                           if (testObj.inLimit){
                               return warningMessage;
                           }else{
                               return false;
                           }
                        }
                    },
                    //errors:{
                    //    "margin": "wrong margin"
                    //}
                });
````

```javascript
$("#mytable").on('change keyup paste', '.elementprice', function () {
                    calcPrice();
                });
```

```javascript
function calcPrice(){
$('#mytable td').find(".elementprice").each(function () {

var sellPrice = tr.find(".elementsellprice")
                sellPrice.attr("data-margin",this.value).trigger('focusout');

});

}
```

**Comment by stockstatus** [comment]
Everything works like a charm now. Last version of validator plugin and call validator('update') after i dynamically add table row helps. Thanks.
