### ISSUE TITLE
inputPasswordConfirm not match password

### ISSUE THREAD

**Issue by Tauseefzil** [1000hz/bootstrap-validator#448]
Hi.

i am using https://1000hz.github.io/bootstrap-validator/ for validation all is working fine but data-match password not match the password.

<div class="form-group">
                <input type="password" name="password" class="form-control" placeholder="password"  data-minlength="6" id="inputPassword" required>
                <div class="help-block with-errors"></div>
            </div>
            <div class="form-group">
                <input type="password" name="password_confirmation" class="form-control"  id="inputPasswordConfirm" data-match="#inputPassword" data-match-error="Whoops, these don't match" placeholder="Confirm" required>
                <div class="help-block with-errors"></div>
            </div>

**Comment by 1000hz** [comment]
It works correctly on the docs page. Please provide an example on JSBin.
