### ISSUE TITLE
validate select lists doesn't work

### ISSUE THREAD

**Issue by deltamaxx** [1000hz/bootstrap-validator#453]
validation of select lists is not working:  the getValue() function for a properly selected element returns 'null'.

In function getValue the debugger shows:
$el.is('select')  ->  true
$el.val()  ->  'element1'
+$el.val() ? $el.val() : null   ->  null

I'd say that the '+' shouldn't be there.

**Comment by cajobao** [comment]
I have the same problem. How to fix this?

**Comment by deltamaxx** [comment]
I did some testing with the '+' removed. Seems to work.

**Comment by cajobao** [comment]
Can you post your the getValue function?

**Comment by 1000hz** [comment]
This is related to the fix for #393 in #436. What version of jQuery are you using?

**Comment by cajobao** [comment]
My is Jquery 1.9.1

**Comment by 1000hz** [comment]
Sorry about this. I'll push a fix.
