### ISSUE TITLE
bootstrap-validatior automatically removes has-error class from form-group

### ISSUE THREAD

**Issue by zeeshanu** [1000hz/bootstrap-validator#454]
I have a problem whenever after server side form fields validation if there are som errors return back and after that, I put has-error class to those form-group those having errors. When the page is fully loaded bootstrap-validatior automatically removes has-error class. How to prevent that?

**Comment by 1000hz** [comment]
This should now be fixed in v0.11.7. The validator won't automatically re-run validation of fields that already have errors upon plugin init.

**Comment by zeeshanu** [comment]
Thanks it's working now. :smile:
