### ISSUE TITLE
bootstrap 4 support validation

### ISSUE THREAD

**Issue by jony89** [1000hz/bootstrap-validator#456]
bootstrap 4 comes with new classes to the input control in order to add an icon feedback (such as v or x marks along with green/red colors)

the classes are : 

form-control-success and form-control-danger which should be attached to the input element.

currently the module does not add these class which results in no mark feedback only different border colors (green/red)

I will be happy to create a pull request to support this. 
The classes will be added and they will do nothing for those who uses bootstrap 3

@1000hz  is it ok by you ? or you wanna do it ?

see https://v4-alpha.getbootstrap.com/components/forms/#validation

**Comment by 1000hz** [comment]
The plugin won't support Bootstrap v3 and v4 simultaneously. v4 uses class names from v3 in slightly different ways which would cause problems. When v4 leaves alpha I'll work on a version of the plugin for it, but for now it remains unsupported. See https://github.com/1000hz/bootstrap-validator/pull/292#issuecomment-261304888 for more details.
