### ISSUE TITLE
Validation message of hidden fields is buggy

### ISSUE THREAD

**Issue by rhedman** [1000hz/bootstrap-validator#457]
I'm having issues with hidden fields that gets revealed after checking a radio button or checkbox. I dynamically add the required attribute to the field(s) when the radio/checkbox is checked.

The field itself get's validated but the error message is not shown until I click the submit button a second time or the field loses focus. Clicking the submit button several times toggles the error message on and off the field. All other required fields behave like normal (the ones that had the required attribute on page load).

Using .validator('update') makes no difference at all in the behaviour. Even without it, the fields get's validated but the error message is not shown correctly either with or without the .validator('update'); 

Any idea what I might be doing wrong or is this an actual bug? Can anyone reproduce this bug?

My markup and JS looks like this:

```<div class="form-group">
<input type="radio"
                                            id="cause-yes"
                                            name="radio"
                                            value="yes"
                                            class="visuallyhidden"
                                            aria-describedby="causeValidationMessage"
                                            data-error="Fältet är obligatoriskt"
                                            required>
                                        <label for="cause-yes" class="field-option field-option--radio">Ja</label>

                                        <div id="cause-yes-more-info" class="is-hidden reveal-if-active clearfix p-t">
                                            <div class="row">
                                                <div class="col-xs-12 col-sm-12 col-md-8">
                                                    <div class="form-group has-feedback">
                                                        <label for="streetAdress" class="required p-l-0">Ange gatuadress (gata + gatunummer)</label>
                                                        <input type="text"
                                                            class="form-control require-if-active"
                                                            id="streetAdress"
                                                            aria-describedby="streetAdressValidation"
                                                            placeholder="Gatuadress + nr."
                                                            data-require-pair="#cause-yes"
                                                            data-error="Fältet är obligatoriskt">
                                                        <div class="help-block with-errors form-control-feedback" id="streetAdressValidation"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

var FormStuff = {

  init: function() {
    // kick it off once, in case the radio is already checked when the page loads
    this.applyConditionalRequired();
    this.bindUIActions();
  },

  bindUIActions: function() {
    // when a radio or checkbox changes value, click or otherwise
    $("input[type='radio'], input[type='checkbox']").on("change", this.applyConditionalRequired);
  },

  applyConditionalRequired: function() {
    // find each input that may be hidden or not
    $(".require-if-active").each(function() {
      var el = $(this);
      // find the pairing radio or checkbox
      if ($(el.data("require-pair")).is(":checked")) {
        // if its checked, the field should be required
        el.prop("required", true);

      } else {
        // otherwise it should not
        el.prop("required", false);
      }
    });
  }

};

FormStuff.init();

**Comment by rhedman** [comment]
I added a codepen on this matter. After a lot of searching I found out it's because the hidden field ends up in between the two radio buttons. If the hidden field is placed after the radio buttons it works.

But there is no other option for me because depending on the user input I need to display new fields based on the answer.

So this seems to be a bug or more of a logical error in validator.js since the validation works, just not the validation message.

http://codepen.io/anon/pen/BQrXbG

**Comment by 1000hz** [comment]
This happens because you have nested form-groups.

When you click submit, the plugin validates all of the inputs, settings errors for any invalid fields and clearing errors for any valid fields. The form-group that contains the Yes radio button is valid, so it [clears errors out of the help-block inside of it](https://github.com/1000hz/bootstrap-validator/blob/master/js/validator.js#L270-L273). But in your case, that help-block corresponds to the Name field, not the Yes radio button.

You'll need to rework your code to show/hide the inputs using JS instead of CSS sibling selectors so you can un-nest your form-groups.

**Comment by rhedman** [comment]
OK, thanks. I'll refactor my code with new markup structure and JS toggeling. Thanks!
