### ISSUE TITLE
How can I add 2 error messages in one box?

### ISSUE THREAD

**Issue by maketroli** [1000hz/bootstrap-validator#459]
I am trying to do some form validation with this plugin http://1000hz.github.io/bootstrap-validator/

Right now I have it like this:
[![enter image description here][1]][1]

with this code:

		.row
			.form-group
				label(for="firstName") First Name*
				input(required type="text" id="firstName" data-error="We can't verify your name.")

				.help-block.with-errors			

			.form-group
				label(for="lastName") Last Name*
				input(required type="text" id="lastName" data-error="We can't verify your last name.")
				.help-block.with-errors

But I need to be like this according to the designers:

[![enter image description here][2]][2]

I am trying to do it with this code:

		.row.form-group
			.col-xs-12.col-sm-6
				label(for="firstName") First Name TEST*
				input(required type="text" id="firstName" data-error="We can't verify your name.")
			.col-xs-12.col-sm-6
				label(for="lastName") Last Name TEST*
				input(required type="text" id="lastName" data-error="We can't verify your last name.")

			.help-block.with-errors.full	

but I am getting only the last error message:

[![enter image description here][3]][3]

Any suggestions?

  [1]: https://i.stack.imgur.com/SNXht.png
  [2]: https://i.stack.imgur.com/JQcgn.png
  [3]: https://i.stack.imgur.com/nMBHJ.png

**Comment by 1000hz** [comment]
The validator only supports one field per form-group. You might be able to code a solution by hiding the help-blocks inside your form-groups and listening for `invalid.bs.validator` / `valid.bs.validator` events and copying the errors in `$field.data('bs.validator.errors')` into a different container.
