### ISSUE TITLE
Validation Firing immediately after clicking the field

### ISSUE THREAD

**Issue by pvpavan51** [1000hz/bootstrap-validator#460]
I am facing issue with validation. Validation is firing immediately after click on any field instead it should fire after leaving the field empty

**Comment by 1000hz** [comment]
Can't reproduce this. http://jsbin.com/xujuyibure/edit?html,css,js,output

If you can make a reproducible test case, I'll reopen.

**Comment by pvpavan51** [comment]
When i try to give placeholder value to a field,  validation is firing immediately once i click in the field.
It is working fine with Chrome but when comes to IE validation is firing immediately

**Comment by zhangwei8607** [comment]
Any update on this?
