### ISSUE TITLE
Multiselect default behavior

### ISSUE THREAD

**Issue by asyndesis** [1000hz/bootstrap-validator#463]
I'm having issues with multiselect boxes:
http://jsbin.com/hagewoyowi/1/edit?html,output

When you select ONE item in a multiselect, the field becomes valid.
Try holding down CTRL and selecting another item.  The field becomes invalid.

Edit: Same behavior in latest Chrome and FF.

**Comment by 1000hz** [comment]
Thanks for the report. I'll try to get a fix out soon.
