### ISSUE TITLE
E-mail validity

### ISSUE THREAD

**Issue by matejjanecek19** [1000hz/bootstrap-validator#465]
Hi, there is a problem with email matching. In your validator is the correct e-mail this: "a@b". This can be seen even in the example in docs. Try it. 

![ghfghdfhd](https://cloud.githubusercontent.com/assets/9271888/21315418/617486c6-c5fc-11e6-98de-be11c606473d.PNG)

**Comment by 1000hz** [comment]
This comes up a lot. `a@b` is in fact a valid email address according to the [W3C spec](http://w3c.github.io/html/sec-forms.html#valid-e-mail-address) that defines what constitutes a valid email address. See #455, #272, #31 and others.
