### ISSUE TITLE
Regex don't work's in Chrome browser

### ISSUE THREAD

**Issue by cajobao** [1000hz/bootstrap-validator#467]
Hi. 
I have a textfield where i put a pattern to validate a date:
`<input type="text" name="form.dataDascimento" pattern="^(((0[1-9]|1[0-9]|2[0-8])[\/](0[1-9]|1[012]))|((29|30|31)[\/](0[13578]|1[02]))|((29|30)[\/](0[4,6,9]|11)))[\/](19|[2-9][0-9])\d\d$)|(^29[\/]02[\/](19|[2-9][0-9])(00|04|08|12|16|20|24|28|32|36|40|44|48|52|56|60|64|68|72|76|80|84|88|92|96)$" id="textfieldDataNascimento" class="form-control input-sm" tabindex="6"/>`

This work's in firefox but, in Chrome (desktop or small device) don't.

Is a problem of compatibility?

**Comment by 1000hz** [comment]
The pattern attribute doesn't need `^` and `$` because they are already assumed (the pattern regex needs to match the entire string). Maybe that's the issue?

**Comment by cajobao** [comment]
I tested now and removing ^ and $ but don't work's

**Comment by 1000hz** [comment]
I think your parentheses are not balanced, and you also still have a couple `^$` in your subexpressions.
