### ISSUE TITLE
semicolons missing?

### ISSUE THREAD

**Issue by burakdobur** [1000hz/bootstrap-validator#468]
OK, this may be not a bug but a feature, Isn't it safer to use semicolons after statements etc. ? My IDE is complaining about 180+ this kind of issue. 

180 x 2 => 360 bytes is what you save. is that worth to make interpreter do the hard work here ?

**Comment by 1000hz** [comment]
It's for style and readability purposes. The code gets minified anyway so it's not about saving bytes or performance.
