### ISSUE TITLE
pointer-events allowing click

### ISSUE THREAD

**Issue by CydGoblin** [1000hz/bootstrap-validator#47]
I notices this part

```
Validator.prototype.toggleSubmit = function () {
    var $btn = this.$element.find('input[type="submit"], button[type="submit"]')
    $btn.toggleClass('disabled', this.isIncomplete() || this.hasErrors())
      .css({'pointer-events': 'all', 'cursor': 'pointer'})
  }
```

With this the button gets the class "disabled", using it with bootstrap it prevents the button being clicked but the line`.css({'pointer-events': 'all', 'cursor': 'pointer'}`  adds `style="pointer-events': 'all'"` allowing to click and sending a blank form; so this should be erased.

**Comment by 1000hz** [comment]
Can you reproduce the submit issue in a JSbin? I can't really offer any help at the moment as I have no visibility into the problem.
