### ISSUE TITLE
Use in Modal

### ISSUE THREAD

**Issue by HerleX** [1000hz/bootstrap-validator#472]
When i want to use the validator in a modal, I am able to click the disabled Submit button.
Is there a possibility to check the form in $('#myModalSubmit').click(function(e) { function, when #myModalSubmit is my form-submit button?

Because when having a form in a modal, i do not receive the forms submit js.

Thank you very much.

**Comment by 1000hz** [comment]
See https://github.com/1000hz/bootstrap-validator/issues/336#issuecomment-222778160. You need to initialize the validator after the `shown.bs.modal` event is fired.

I'm also not sure if you mean your submit button is outside of your `<form>` element. If that's the case, you'll need to use the `form="` attribute on your submit button. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-form

**Comment by HerleX** [comment]
Thanks for your answer!
But unfortunately i do not get the submit thing to work. Here is a minimalistic example of what i want to do:
`
<div id="myModal" class="modal fade" role="dialog">
      <div class="modal-dialog">

        
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title" id="modal_header">Modal Header</h4>
          </div>
          <form id="myForm" class="form-horizontal" data-toggle="validator">
                <div class="modal-body">
                    <div class="form-group has-feedback">
                        <label class="col-xs-3 control-label">Name</label>
                        <div class="col-xs-7">
                            <input type="text" class="form-control" id="name" placeholder="Nachname" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
					<button form="myForm" type="submit" class="btn btn-success">Jetzt bestellen!</button>
					<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    
    <script type="text/javascript">
    $('#myModal').on('show.bs.modal', function(e) {
		$(this).find('form').validator('destroy').validator();
    });
	$('#myForm').validator().on('submit', function (e) {
		if (e.isDefaultPrevented())
		{
			alert(1);
		}
		else
		{
			alert(2);
		}
	});
     </script>
`

It does only show alert(2); all the time. Even if my form is correct. Shouldn't it show alert1? What am i missing?

Thank you very much!
