### ISSUE TITLE
data-attributes are being read with stale values

### ISSUE THREAD

**Issue by irvv17** [1000hz/bootstrap-validator#475]
Hi I try invalid a select with differents values 

this is a simple example..
```javascript
$('#myForm').validator({
  custom: {
    invalidnumber: function ($el) {
      var number = $el.attr('data-invalidnumber')
      if ($el.val() == number) {
        return number + " is not a valid choice"
      }
    }
  }
})

$('#A').on('change', function (e) {
  var $el = $(e.target)
  $('#B').attr('data-invalidnumber', $el.val()).trigger('focusout')
})
```

and this is my html code

```html
<div>
<form id="myForm" data-toggle="validator">
      <div class="form-group">
        <label>Invalid Number</label>
        <input id="A" type="number" class="form-control" required>
      </div>
      <div class="form-group">
        <label>Value</label>

               <select class='form-control' name='sel_tesoreria'  data-invalidnumber="0"  
                       id='B' required>
   <option value='0' selected='selected'>Seleccione tesoreria....</option>
                    </select>
        <div class="help-block with-errors"></div>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
</div>
```

so... I try with custom but... the form gets validate but I want invalid when select is 0

can someone help me?

btw @1000hz u are the man ,love this powerfull plugin...thanks a lot!.

**Comment by irvv17** [comment]
this is the html 
    <form id="myForm" data-toggle="validator">
      <div class="form-group">
        <label>Invalid Number</label>
        <input id="A" type="number" class="form-control" required>
      </div>
      <div class="form-group">
        <label>Value</label>

               <select class='form-control' name='sel_tesoreria'  data-invalidnumber="0"  
                       id='B' required>
   <option value='0' selected='selected'>Seleccione tesoreria....</option>
                    </select>
        <div class="help-block with-errors"></div>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>

**Comment by 1000hz** [comment]
Thanks for the report. This is a bug. The problem is that the plugin uses `$.fn.data(attr)` to read values that are set as data attributes, but those stored values don't seem to get updated when the data attribute changes. The fix is to change the plugin to read the values using `$.fn.attr('data-' + attr)` instead so the values are read directly from the DOM.

**Comment by andrews05** [comment]
I think this is not the correct solution. I'm running into the opposite problem: If I change the data using `$el.data('foo', 'bar')` this will not update the data- attribute, which means the validator will no longer pick up the new value.
Using the .data() function is the correct way to get and set data in jQuery - the original author here just needs to change his code to use .data() instead of .attr().

**Comment by irving-caamal** [comment]
Hi @andrews05  man , You are very right, I didn't think about using .data(), works perfectly with first solution but with this is more logical and yes, i think is the correct solution.


what about the commit?, 
 ->
 https://github.com/1000hz/bootstrap-validator/commit/5d74c2200be7f9c5521bf2cbfd16a20f7a92e349

**Comment by andrews05** [comment]
Hopefully @1000hz can revert it? (I think it's actually 469c48d)
Until then you can keep using v0.11.8 as I am, since .data() doesn't work in v0.11.9.

**Comment by irving-caamal** [comment]
I'm using v0.11.9. because works perfectly with attr()... but , yes... he need revert it, it´s the best way.

I think you should open new Issue @andrews05 , maybe this notifiactions are invalid for him 'cause it's closed, I support your observation.

**Comment by 1000hz** [comment]
I'll probaby revert, but I have to spend some time catching back up with the project first.

**Comment by andrews05** [comment]
Sure, thanks in advance :)
