### ISSUE TITLE
bootstrapValidator is not a function     at HTMLDocument.<anonymous>

### ISSUE THREAD

**Issue by rupaldhamesha** [1000hz/bootstrap-validator#476]
I am getting this error and validation is not working.
I have included following files.

    
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>

  <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.2.js"></script>          

  
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>  
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.3/js/bootstrapValidator.min.js"> </script>
         <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

 <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.3/css/bootstrapValidator.min.css"/>  

thanks in advance

**Comment by 1000hz** [comment]
This is a different project than the one you're including.

**Comment by irvv17** [comment]
this is not formvalidation dude  you need to go to https://github.com/formvalidation/formvalidation.io

that is the correct repository .
