### ISSUE TITLE
hey 1000hz

### ISSUE THREAD

**Issue by redchief** [1000hz/bootstrap-validator#48]
Can't put validation on select fields of form please help as soon as possible

**Comment by rudzikdawid** [comment]
If you use disabled atribute in first option element
You shoud add something like that:
```
jQuery('form[data-toggle="validator"] select').on('change', function(event) {
    event.preventDefault();
    jQuery(this).find('option[disabled]').remove();
});
```
Some of Blackberry phones has problem with validation of disabled option elements.
And we need to remove this disabled element after user choice.

**Comment by Alvalvar** [comment]
Hi! If i use Bootstrap-select http://silviomoreto.github.io/bootstrap-select, validation does not work.

**Comment by NikeshMewada** [comment]
Hi, 
Any update on how to make validation work for:
Bootstrap-select http://silviomoreto.github.io/bootstrap-select,

**Comment by jonastg** [comment]
Hi,

For triggering the validation when you are using bootstrap-select you should use something like that:

```JS
$('.select').on( 'hide.bs.select', function ( ) {
    $(this).trigger("focusout");
});
```
