### ISSUE TITLE
custom function present only after destroy. Is this behavior expected?

### ISSUE THREAD

**Issue by adilshow** [1000hz/bootstrap-validator#480]
```
  QUnit.test('call custom validator', function (assert) {

      var form = '<form>'
  + '<div class="form-group has-error">'
  + '<input type="text" value="example" data-validation1 data-validation2>'
  + '<input type="text" value="mobilephone" data-requiredone="phone">'
  + '<div class="help-block with-errors">Fill at least one</div>'
  + '</div>'
  + '</form>'

      var $form = $(form)
        .appendTo('#qunit-fixture')
        .validator()

      var options1 = {
          custom: {
              validation1: function (element) { }
          }
      }

      var options2 = {
          custom: {
              validation2: function (element) { }
          }
      };

      var form = $('form').validator(options1)

      var validator = $(form).data("bs.validator")

      assert.ok(validator.options.custom.validation1 && validator.options.custom.validation1.toString() == options1.custom.validation1.toString(), 'validator.options.custom contains validation1')

      $('form').validator('destroy')

      $('form').validator(options2)

      validator = $("form").data("bs.validator")

      assert.ok(validator.options.custom.validation2 && validator.options.custom.validation2.toString() == options2.custom.validation2.toString(), 'validator.options.custom contains validation2')
  })
```

result: http://imgur.com/a/NW7uA

the first give an error the second is not.

I would like to know if expected behavior?

Thank you!

**Comment by 1000hz** [comment]
You already initialized the plugin without the custom validators with
```js
      var $form = $(form)
        .appendTo('#qunit-fixture')
        .validator()
```

The plugin doesn't reinitialize itself with new options if you call `.validator()` again. This might change in the future.

**Comment by adilshow** [comment]
since is an behavior change will you accept a pull request with that change?

**Comment by 1000hz** [comment]
I'm not sure, I'd need to think about the implications of such a change and how it is implemented.

I need to think about what the behavior would be upon reinitialization. Not sure if it should destroy the current instance of the validator or just replace the options? Or maybe merge the options?

**Comment by adilshow** [comment]
Maybe just add functionalities that don't change the behavior, something like:
validator('replace', options)
validator('marge', options)

The merge option is sweet sugar, since it can be achieved with little javascript and the replace option.

Please let me know when you made your mind, I would love to contribute!
