### ISSUE TITLE
Ajax Support

### ISSUE THREAD

**Issue by c0fe** [1000hz/bootstrap-validator#481]
Does this script work well with Ajax feedback or no? Have you tried?

**Comment by 1000hz** [comment]
It supports ajax via the `data-remote` validator. A planned future feature is returning a Promise from a custom validator which you could use to implement any asynchronous behavior.

**Comment by c0fe** [comment]
Are there any active examples of this implementation?

**Comment by 1000hz** [comment]
https://github.com/1000hz/validator-remote-example
