### ISSUE TITLE
Captcha Support

### ISSUE THREAD

**Issue by c0fe** [1000hz/bootstrap-validator#482]
Does this script support recaptcha version 2?

**Comment by 1000hz** [comment]
Probably not. Hopefully some time in the next few months I'll add support for returning Promises in custom validators which will allow you to integrate with any async behavior.

**Comment by 1000hz** [comment]
Here's a complete example of reCAPTCHA working with this plugin.
http://jsbin.com/kirevujexa/edit?html,js,output
