### ISSUE TITLE
remote validation for email

### ISSUE THREAD

**Issue by cambazz** [1000hz/bootstrap-validator#483]
I have tested the remote validator without problems.

How can I make it such that, for email validation for example, the query to be sent only when the email input is complete? Right now it will send a query for each letter the user types. (Provided that it passes the basic email check).

But for example if one is typing user@e after that e, for each typed letter a query will be sent.

I want it so that it will only send query when email input is out of focus, or right before form submit.

Best regards,
C

**Comment by 1000hz** [comment]
All validations (including remote validators) are debounced so they don't run until the user has stopped typing for a certain period of time (as determined by the `delay` option, default 500ms). You can adjust the delay option if you feel like it's too fast. If you still want to only run validators on loss of focus, you can call `$('#myForm').off('input.bs.validator change.bs.validator')` to remove those event handlers, but this will affect all inputs, not just your email field. Alternatively, you can add a listener on your email field for `input` and `change` events that calls `e.stopImmediatePropagation()`.
