### ISSUE TITLE
Submit button not changing to active

### ISSUE THREAD

**Issue by andrew-za** [1000hz/bootstrap-validator#487]
I have the validator activated by:
`$('#quoteForm').validator().on('submit', function (e) {`

With my wysiwyg I then run a `$('#quoteForm').validator('update');` in order to let it see the newly populated textarea field.

The button does not return to Active.

**When I remove the JS activating and use the data-toggle attribute the submit button works...** 

Hope you can help

**Comment by 1000hz** [comment]
You might need to bind your submit handler before you initialize the validator
