### ISSUE TITLE
ie9 support

### ISSUE THREAD

**Issue by rudzikdawid** [1000hz/bootstrap-validator#49]
is there a way to effect this validation on ie9?

**Comment by 1000hz** [comment]
You need to include a polyfill to shim the HTML5 Constraint Validation API. Something like https://github.com/ryanseddon/H5F might work, but I haven't tested it.

**Comment by rudzikdawid** [comment]
It works :D

**Comment by 1000hz** [comment]
Awesome!

**Comment by back-2-95** [comment]
Can you provide example @rudzikdawid ?
I added H5F and nothing happens on IE9. No errors nor validation.

**Comment by rudzikdawid** [comment]
https://jsfiddle.net/kxp9cgza/

**Comment by Taewa** [comment]
@rudzikdawid
Your jsfiddle is not working on IE9 (I am using IE via www.browserstack.com)
