### ISSUE TITLE
Can't update feedback only

### ISSUE THREAD

**Issue by Wardevour** [1000hz/bootstrap-validator#493]
I'd like a method to update the feedback and not validate the form. If I validate, the page scrolls to the first issue. I want to turn the label green or red manually after the input's value is changed internally.

For example, if I pull the city and state using the zip-code, after a user has already triggered the feedback, it stays red until the user places focus on the input again.

**Comment by 1000hz** [comment]
You can try `.$(feedbackField).trigger('focusout')` to trigger validation on just that single field.

**Comment by Wardevour** [comment]
Thanks for the quick reply! That worked just fine, I knew I was overlooking a simple solution.

**Comment by 1000hz** [comment]
Great!
