### ISSUE TITLE
What about Bootstrap 4 support

### ISSUE THREAD

**Issue by sweco-sepros** [1000hz/bootstrap-validator#495]
v4.0.0-alpha.6

**Comment by 1000hz** [comment]
Still alpha. I'll start working on support once it hits beta.

**Comment by nam-co** [comment]
Hi 1000hz, finally after years, B4 is in beta

**Comment by r-morgenstern** [comment]
Also looking forward to updated version to fit boostrap 4.

As a interim solution. I just added the missing styles to the page. 

```
.help-block { display: block; margin-top: .25rem; font-size: .875rem; color: #dc3545; }
.has-error .help-block { color: #dc3545; }
.has-error .col-form-label{ color: #dc3545; }
.has-error .form-control { border-color: #dc3545; -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075); box-shadow: inset 0 1px 1px rgba(0,0,0,.075); }
```

**Comment by nam-co** [comment]
Thanks, I notice everything is still working except errors.
Thanks for reply

**Comment by SimonTod** [comment]
Hey @r-morgenstern I couldn't get this to work with your css. What do you suggest I do ?
Validation is working great but I don't get the errors showing next to the form fiels.
Moreover now that I see your css, it looks like the plugin should be adding classes to inputs that are not valid. My inputs are not getting any new class.
I am using release 0.11.9

**Comment by r-morgenstern** [comment]
Hi Simon, sorry to hear that. You may look what field validation you use and check with a bootstrap 3 installation what style is been used and missing in 4 so that you can add it to your css. 

On the other hand, bootstrap 4 is close to final, so I expect that the bootstrap validator gets updated soon. 

Viele Grüße,
René

**Comment by SimonTod** [comment]
Thanks for your answer. I will look into it
