### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by huphtur** [1000hz/bootstrap-validator#497]
Is it possible to insert custom icons (preferable SVG) instead of using font-icons? 

iOS 9.1 has [some problems](https://cloudfour.com/thinks/seriously-dont-use-icon-fonts/#they-encroach-on-emoji-turf) with font-icons and shows weird emoji's instead.

**Comment by 1000hz** [comment]
Only font icons are supported. Although, all the plugin does is add a class to a `.form-control-feedback` element, which I guess you could just have be a div that contains two svg images and show/hides them according to the added class. Might need to override some styles Bootstrap sets on `.form-control-feedback` but shouldn't be too big of a deal. Something along these lines:
http://jsbin.com/qazuxawora/edit?html,css,js,output
