### ISSUE TITLE
CDN doesn't work in Chrome due to MIME type 'text/html'

### ISSUE THREAD

**Issue by tdkehoe** [1000hz/bootstrap-validator#498]
I got this error message in Chromium: 

"Refused to execute script from 'https://cdnjs.com/libraries/1000hz-bootstrap-validator' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled."

This is when using the CDN, I haven't tried downloading and installing the module.

**Comment by 1000hz** [comment]
That's not the address of the actual resource, but the link to the CDNJS library page.
Following that link shows you the actual CDN urls:
`https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.9/validator.js`
`https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.9/validator.min.js`
