### ISSUE TITLE
data-disable="true" adds "disabled" to classList not as attribute

### ISSUE THREAD

**Issue by pfeileon** [1000hz/bootstrap-validator#499]
As in the title, the submit-button is only superficially marked as "disabled". It's still active as long as "disabled" is only added to the classList (`<button type="submit" class="btn btn-default disabled">`) and not as an attribute (`<button type="submit" class="btn btn-default" disabled>`).

Is that behaviour intended?

***

Right now, I'm using the following css-hack to make the button truly disabled:
```
.my-btn.disabled {
        pointer-events: none;
}
```

**Comment by 1000hz** [comment]
It's intentional. Making the button truly disabled leads to a bad user experience because the user might not realize why they can't submit the form. With the button still clickable, the form errors will be revealed when the user tries to submit.

**Comment by davidholiday** [comment]
that may be the case - but the docs should reflect that :-)
