### ISSUE TITLE
How to check isValid

### ISSUE THREAD

**Issue by Mayur23491** [1000hz/bootstrap-validator#501]
I am using this in my model popup and running perfectly fine but I am also using angular js in my application so how to check that bootstrapvalidator given in form isvalid or not because on every click of submit button it calls my angular js function.

So there I have to check isvalid or not and based on that I can call further process.

**Comment by 1000hz** [comment]
Based on your comment [here](https://github.com/1000hz/bootstrap-validator/issues/61#issuecomment-280834907) you aren't using this plugin.
