### ISSUE TITLE
Email validation - RFC 6532

### ISSUE THREAD

**Issue by ElMacBgl** [1000hz/bootstrap-validator#502]
Hi,

Believing RFC 6532 (afaik, most recent normalization), email can now have special chars in both domain name, AND in local part.
Current validator accepts special characters (such éèà) in domain, but not in local part of the email.
Is there a way to fix this ? If so, how ?

**Comment by 1000hz** [comment]
Email validation is handled by the built-in browser validation API. Thus, it is implemented according to the [W3C spec](http://w3c.github.io/html/sec-forms.html#valid-e-mail-address). This spec would need to be updated to match the new RFC, and it would be up to browser vendors to implement this change. There's not really a way to override the native validators in this plugin.

**Comment by ElMacBgl** [comment]
I was afraid about such possibility.
Do you think it can be workaround, by using a normal textfield, and specific pattern ? I saw we can, in some cases, define a pattern for input text. I just don't know if that would work with bootstrap validator...

**Comment by 1000hz** [comment]
Yeah, you could do that. Not the best thing to do from a semantic
standpoint, but you should make the call on what is most important to you.

**Comment by ElMacBgl** [comment]
100% agree. Just afraid about the 0.0001% of population who 'could' eventually have such address and would not be able to fill the form because browsers are not up-to-date to last RFC.
All question remains to decide if 0.0001% is acceptable or not ;)
