### ISSUE TITLE
Multiple Step Form: Multiple Dropdowns !hasErrors although one dropdown not selected

### ISSUE THREAD

**Issue by stevepony** [1000hz/bootstrap-validator#504]
Hi Cina,

I have a strange issue with the form validation. Just setup a multiple step form and before going to the next step I'm checking via "var hasErrors = $('#registration_form').validator('validate').has('.has-error:visible').length;" whether there all fields of this step are filled or not.

If !hasErrors, then go to next step. If hasErrors, run the validator and highlight what's missing. It works great so far, but...:

I have 6 dropdown menus right next to each other:
Passport Expiry: dd - mm - yyyy (3 dropdowns)
DoB: dd - mm - yyyy (3 dropdowns)

All 6 dropdowns are required. If I select none, 1, 2, 3, or 4 of the dropdowns only, can't go to next step.

But if I choose 5 only (1 missing), it DOES go to the next step. At the final step can't submit the form though because 1 dropdown still missing. Problem is the user can't see that because step 1 isn't visible anymore. So seems like the final validation upon submit works differently than !hasErrors? Any idea on that?

I created a JSFiddle: http://jsfiddle.net/gkxvLs9u/4/

THANK you so much!
Steve

![example](https://cloud.githubusercontent.com/assets/20462571/23328023/10967474-fb4b-11e6-8cf1-480ed6ae9347.png)

**Comment by 1000hz** [comment]
You need each input inside of its own `.form-group`. Right now you have multiple `select` elements inside of a single group, so the .has-error class is being removed by one of the other select elements after it passes validation.
