### ISSUE TITLE
Active validation stuck in "off" state

### ISSUE THREAD

**Issue by biolectrikx** [1000hz/bootstrap-validator#505]
Hello,

I am trying to toggle the validator between active and passive states but it is remaining in "off" state due to code `$('#pardot-form').validator().
    off('input.bs.validator change.bs.validator focusout.bs.validator');`.

Steps involved
1) I disable active validation of my form fields using `$('#pardot-form').validator().
    off('input.bs.validator change.bs.validator focusout.bs.validator');` embedded within the following function initialized within the body of my HTML script
```javascript
function ToggleValidate(){
  if (ValidYesNo === 0){
    console.log("No");
    $('#pardot-form').validator().
    off('input.bs.validator change.bs.validator focusout.bs.validator');
  }
  else {
    console.log("Yes");
    $('#pardot-form').validator().
    on('input.bs.validator change.bs.validator focusout.bs.validator');
  }
}
```
Function called in HTML code via:
```html
<body>
    <form id="pardot-form" method="post" action="https://go.mylink.com>
        <script type="text/javascript">
                              $('pardot-form').ready(function() {
                                ToggleValidate();
                              })
        </script>
    </form>
</body>
```
2) The above works for allowing the user to initially fill out the form without any active validation while moving from field to field
3) On custom onclick button calls function `ValidateForm()`
The user then fills out form initially without any active validation - I call function `ValidateForm()` via an onclick event which validates form but also changes `var ValidYesNo = 1` and calls `function ToggleValidate()` which correctly runs the line `$('#pardot-form').validator().
    on('input.bs.validator change.bs.validator focusout.bs.validator');` However, this last line of code doesn't seem to turn active validation on. When I click through the various form fields and enter information, I do not get active validation when inputing data or changing focus. What is the correct piece of code to turn active validation back on once I have turned it off earlier? It seems to be stuck in the "off" state.
```javascript
function ValidateForm(){
  console.log("Enter Function")
  $('#pardot-form').validator('validate');
  if($('#pardot-form').has('.has-error').length === 0){ // form is valid
    $('pardot-form').submit();
  }
  else {
    ValidYesNo = 1;
    ToggleValidate();
    console.log(ValidYesNo);
  }
}
```

Note: `var ValidYesNo = 0;` is set in the header, but I confirm via multiple instances in my code that it indeed does change to 1 once the onclick event is triggered.

**Comment by 1000hz** [comment]
You can't just call `.on()` without binding to any functions. You need to reinitialize the plugin with `$().validator('destroy').validator()`

**Comment by biolectrikx** [comment]
Thank you for the quick reply.

Two additionally follow up questions:
1) Is there any way of reinitializing the plugin without loosing the feedback that exists for a users incorrect fields? Calling `().validator('destroy').validator()`  erases all "feedback" that appears after I had previously called `$().validator('validate')` onclick.

2) If no to above, then is there another way to re-enable `'input.bs.validator change.bs.validator focusout.bs.validator'` without re-initializing the plugin?

Thanks again.

**Comment by 1000hz** [comment]
1. No
2. You'll need to reach into `$.fn.validator.Constructor.prototype` to grab the `onInput` function. You need to be sure to bind the function to your instance of the validator using `$.proxy`.

```js
var $form     = $('pardot-form');
var validator = $form.data('bs.validator');
var onInput   = $.fn.validator.Constructor.prototype.onInput;
$form.on(
  'input.bs.validator change.bs.validator focusout.bs.validator',
  $.proxy(onInput, validator)
);
```

**Comment by 1000hz** [comment]
also your ready handler isn't targeting your form correctly:
```js
                              $('pardot-form').ready(function() {
                                ToggleValidate();
                              })
```

should be `$('#pardot-form')`

**Comment by biolectrikx** [comment]
This works beautifully thanks!
