### ISSUE TITLE
bootstrap-validator works in chrome, but not in firefox

### ISSUE THREAD

**Issue by jpflorido** [1000hz/bootstrap-validator#515]
Hi,
I'm testing bootstrap-validator on my form with the following example:

 <form class="form-horizontal" data-toggle="validator" role="form">
                <div class="form-group">
                    <label for="inputEmail" class="control-label">Email</label>
                    <input type="email" class="form-control" id="inputEmail" placeholder="Email" data-error="Bruh, that email address is invalid" required>
                    <div class="help-block with-errors"></div>
                </div>
</form>

Js dependencies are loaded in the following order:
    <script type="text/javascript" src="../bower_components/jquery/dist/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="../bower_components/bootstrap-validator/dist/validator.js"></script>

The above code works in Chrome, but not in Firefox. I've googled but with no success.
Any ideas?
Thanks

**Comment by 1000hz** [comment]
The validator generally works in Firefox, so this is likely an issue in your particular setup. This seems like a question better suited for StackOverflow.

**Comment by jpflorido** [comment]
It seems that there is a conflict with polymer in Firefox (in a "plain" HTML, it works on Firefox, however when integrated with polymer, it does not work)
