### ISSUE TITLE
Focus multiple inputs

### ISSUE THREAD

**Issue by andrews05** [1000hz/bootstrap-validator#516]
If a form-group contains more than one input (e.g. for a date range), the focusError function will call focus on all the inputs within the first .has-error. I suggest changing `.has-error:first :input` to `.has-error :input:first`.

**Comment by 1000hz** [comment]
Form groups should only have one input inside of them or else the validator won't function properly.

**Comment by andrews05** [comment]
That's generally true, but surely it wouldn't hurt to make this small change?

**Comment by 1000hz** [comment]
The change you suggest will try to focus every form group with an error (not the just the first one) which will have the effect of focusing the last one.

Secondly, you really shouldn't have multiple inputs in the same form group. You can nest form groups inside of each other, so you should just wrap your inputs in their own form group or else you'll get into situations where one of the inputs is clobbering another input's errors, etc.

**Comment by andrews05** [comment]
I've tried running the query and it always selects only one element, equivalent to ('.has-error :input').first(). If there's any concern, you could always use `.has-error:first :input:first` :)

Yeah, I know I shouldn't have multiple inputs but in my case it's a connected date range picker with a start date and an end date inside a single input-group. It works because the datepicker plugin ensures that the range is always valid (including filling in the other field when you only enter one of them), so the validation plugin is simply making sure that you have entered a date.

**Comment by 1000hz** [comment]
Ah, looks like you're right. It appears `:first` will always only return a single element. In that case I guess putting it at the end of the selector is the safer approach. I'll make that change.

**Comment by andrews05** [comment]
Thanks :)
