### ISSUE TITLE
Scrolling to Error Field?

### ISSUE THREAD

**Issue by rodneypoplin** [1000hz/bootstrap-validator#52]
Any way to add this?

**Comment by 1000hz** [comment]
You could maybe try something like this.

```javascript
$('form[data-toggle="validator"]').on('submit', function (e) {
  var errors = $('.has-error')
  if (errors.length) {
    $(document).scrollTop(errors.offset().top)
  }
});
```

**Comment by rodneypoplin** [comment]
I tried that but something is preventing it from working. I removed the validator.js file and it works but when in conjunction it doesn't. Any suggestions whats causing it?

Or is maybe i should add it to the .js file? and if so where?

**Comment by 1000hz** [comment]
Hmm, it seems like the `.has-error` class isn't always applied in time before that submit handler is run. You could use a `setTimeout(fn, 0)` to push the call to the next runtime stack.

```javascript
$('form[data-toggle="validator"]').on('submit', function (e) {
  window.setTimeout(function () {
    var errors = $('.has-error')
    if (errors.length) {
       $(document).scrollTop(errors.offset().top)
    }
  }, 0)
})
```
I'll start to think about the timing of things and perhaps raising actual `fail/failed` events on unsuccessful submits.
