### ISSUE TITLE
How can i use multiple custom validators?? The validator which is  placed first only works

### ISSUE THREAD

**Issue by davidj23e** [1000hz/bootstrap-validator#526]
<script>
        $('form[data-toggle="validator"]').validator({
            custom: {
                uiuser : function($asa) {                    
                    var matchVa = $asa.val(); 
                    if (chkuu==matchVa) {
                        return "Customer ID already registered!!" ;
                    }
                }
            }
        })
</script>
<script>
        $('form[data-toggle="validator"]').validator({
            custom: {
                equc: function($as) {
                    var matchValue = $("#c4").val();
                    if ($("#c5").val() !== matchValue) {
                        return "Passwords do not match!!!" ;
                    }
                }
            }
        })
</script>

**Comment by 1000hz** [comment]
You only need to initialize the plugin once, with both custom validators in the `custom` option object.
