### ISSUE TITLE
Detecting numpad 'enter' with JS fails when using data-match

### ISSUE THREAD

**Issue by bhartvigsen** [1000hz/bootstrap-validator#527]
Hi, I've noticed an issue where JS cannot detect numpad enter if I use data-match. I have this code:

```
<input type="hidden" id="confirmInputBox" value="">
<input id="inputTextBox" data-match="#confirmInputBox" data-error="This is an error msg" type="text" class="form-control">
<button id="buttonElement" type="button" class="btn btn-danger">Delete</button>

$('#inputTextBox').keyup(function(e) {
    if (e.which == 13 || e.which == 176) $('#buttonElement').click();
    return false;
});
```

This is inside of a bootstrap modal (which is probably irrelevant).

For some reason, it detects 'return' (key 13) correctly but just cancels out the dialog on numpad 'enter' (key 176'). Removing the data-match causes the keypress to be detected properly. I'm wondering if somewhere in this validator library you're properly checking/allowing for 'enter' but not numpad 'return'. I've looked through the code but I've not been able to locate the source of this issue.

**Comment by bhartvigsen** [comment]
UPDATE: From further testing, it appears that if I wait 3-5 seconds after the bootstrap modal shows up and then hit the numpad enter key, things work. So this may not actually be an issue in your library, but there's certainly some sort of timing conflict occurring, so if you've got any ideas I've love to hear them.

**Comment by 1000hz** [comment]
Nope, no idea. Sorry. I'm going to close this issue, but if you find there's something in the plugin that's broken feel free to comment again and I'll reopen.
