### ISSUE TITLE
when fields are set dynamic cant remove the error propperly

### ISSUE THREAD

**Issue by JvanLoon** [1000hz/bootstrap-validator#528]
Hello 1000hz

I have an page with 3 bootstrap modals.
i have a javascript method that removes attributes (required and data-validate)
i also have another method to set attributes to the fields i need to validate
at the end of that method i call $("form1").validator('update')

now my senario:
when i open the first modal and select a field but dont fill it in it becomes red en shows the error, everything good so far
then when i close the modal i remove the arrtibutes (required and data-validate)
and the call $("form1").validator('update')

now when i open the second modal and fill it in correctly the submit button stays disabled
that is becasue the validator seed the field in the first form and knows it contains the "error"
but i ran the update so i dont know why it still shows that field with the error

what if tried:
i tried:
$("form1").validator().trigger('reset.bs.validator')
i thought itll reset the validator (didn't work)

i also tried:
$("form1").validator('destroy')
and recreate it when i need it (didn't work)

i also tried:
to rebuild the reset/clearerrors and update method useing the logic of the validator (didn't work)

im out of idears now can you please tell me what i doing wrong?

Kind regards JvanLoon

**Comment by 1000hz** [comment]
It's hard to help you unless I have an example I can look at. If you fork this [JSBin](http://jsbin.com/kahehelipo/1/edit?html,css,js,output) and reproduce your problem, I have a better chance of seeing the issue. In the two code snippets you tried, you're not selecting your form correctly. You wrote `$("form1")` but you probably want `$("#form1")`. Not sure if that's what you actually had in your code or just wrote here as an example, but both destroy and reset should work for what you're trying to do. Also, you don't need to call `.validator('update')` if you're not adding/removing input _elements_ from the DOM.

**Comment by JvanLoon** [comment]
No indeed that was i typo i ment $("#form1"), its hard to show you what i got so ill try to explain it as best as i can with this as example: http://jsbin.com/haroqimuno/1/edit?html,css,js,output

i have 3 tabs, that all contain 1 modal, i want to validate only the inputs on the modal that is opend.
everything worked fine but when i click on the input in the first modal, then it becomes red and shows that it is empty. then when i close the modal the attributes are removed, then when i open the second modal, the submit button is disabled, when i fill in the correct data the button is still disabled, but when i click submit 2 thinks can happen, 1. it doesn't do anything, or 2. it still submits.

what i did is:
i added: console.log(this.$inputs.filter(fieldErrors));
to the hasError method in the validator. ( before the return)
when i do the thing i describes above and correctly fill in the second modal information.
it prints an array with the input of the first modal, telling me the validator still things it has an error.

Maby this claryfies it alittle bit?

kind regards JvanLoon

**Comment by 1000hz** [comment]
Sorry, that example isn't working. It doesn't seem like you're running into a bug with the plugin though, so I think this a question better suited for StackOverflow. If you do find that there is a bug in the plugin, feel free to comment and I'll reopen the issue.

**Comment by JvanLoon** [comment]
The example i gave was just to show what i have... its not actual propper code it was not made to work more to show what i got....... (just wanted to make this clear.....)

(NOTE): Its impossible for me to show you the code. i created an web application with visual studio.. so i use ASP elements a.k.a: <asp:TextBox ID="txtProjectNummer" runat="server" CssClass="form-control" TextMode="SingleLine" MinLength="2" MaxLength="50"></asp:TextBox>


So the example i included is a VERY CRUDE and SIMPLE receation of the form...
Ill show you my page and javascript, it wont be very usefull but more i can't do:
(NOTE): i have a "MasterPage" containing the form, and the link is the page with its content
form id="form1" runat="server" role="form" data-toggle="validator" data-focus="true"
        http://jsbin.com/mojoxakuru/edit?html,output (updated)
/form

P.S i had to remove the >< from the form to show it

Maby this clears some thing up?
kind regards JVL
