### ISSUE TITLE
Disable Scrolling error Field

### ISSUE THREAD

**Issue by zapcriativo** [1000hz/bootstrap-validator#532]
Hi, 

How to disable page scrolling to error field on click in submit?

**Comment by 1000hz** [comment]
`$('form').validator({focus: false})`

**Comment by zapcriativo** [comment]
Thanks for the answer! But how to use 'focus:false' with condition ?

						if ($('#tab1').validator('validate').has('.has-error').length != 0) {
							return false;
						}

**Comment by 1000hz** [comment]
That's not supported. You'd have to use `focus: false` and then implement your own focusing/scrolling behavior in an event handler bound to the `submit` event.

**Comment by zapcriativo** [comment]
Ok, Thank you!!
