### ISSUE TITLE
Form is submitted twice

### ISSUE THREAD

**Issue by aklimaruhina** [1000hz/bootstrap-validator#533]
i'm using ajax post. its submitting twice. how will my fix it? my code is 
$('#newUser').validator().on('submit', function (e) {
      if (e.isDefaultPrevented()) {
        alert('You must have some error.please check again');
      }
      else{
        var form = $( this );
        $.ajax({
            url: form.attr('action'),
            type: 'POST',
            data: form.serialize(),
            dataType: 'json',
            success:function(response){
               console.log(response);
            },
            error:function(response){
              alert('failor');
            }
          });
      }
  });

**Comment by 1000hz** [comment]
You need to call `e.preventDefault()` in order to stop the browser from submitting since you are doing it via ajax
