### ISSUE TITLE
Show errors only after form submit

### ISSUE THREAD

**Issue by dyegonery** [1000hz/bootstrap-validator#539]
Hey guys.

I was wondering that would be great if this plugin had a option that set the error messages to be shown only after form submit. I didn't saw this in docs. What do you think about it?

**Comment by 1000hz** [comment]
You can unbind this behavior by calling `.off('input.bs.validator change.bs.validator focusout.bs.validator')` after you initialize the plugin. It might be good to add this to the docs but I'm not sure enough people want to do this.
