### ISSUE TITLE
Instantly display a modal when the form is submitted (before validation)

### ISSUE THREAD

**Issue by moorcroftlad** [1000hz/bootstrap-validator#54]
Hi I'm trying to instantly display a modal 'loading' box when the submit button is pressed on a form.  I've achieved this by doing the following:

    $('form').on('submit', function (event) {
        showLoadingModal();
        if (!event.isDefaultPrevented()) {
            event.preventDefault();
            submitForm(this);
        } else {
            hideLoadingModal();
        }
    });

However I'm getting a problem where there is a small gap of time (under a second) between clicking the button and the modal being displayed.  I'm assuming this delay is caused by the time taken validating all the fields on the form of which there are quite a lot.  

This therefore leads me to believe that the validator 'form submit' is being executed before my code and I should be doing something different to call the `showLoadingModal()`

**Comment by 1000hz** [comment]
With assumption that the intention behind checking `!event.isDefaultPrevented()` is essentially "if the form is valid...", I think you'd need to break your submit handler up into two handlers. Since jQuery runs event handlers in the order they are bound, you'll need to add the `showLoadingModal()` call before the validator is initialized on your form.

I think the solution would be something like this:

```javascript
$('form')
  .on('submit', function (event) {
    showLoadingModal();
  })
  .validator()
  .on('submit', function (event) {
    if (!event.isDefaultPrevented()) {
        event.preventDefault();
        submitForm(this);
    } else {
        hideLoadingModal();
    }
  });

If you're using `data-toggle="validator"` to initialize the form, I think you'd need to remove it.

**Comment by moorcroftlad** [comment]
Thanks, I see what you mean with this, however it hasn't worked, in that I'm still getting the delay.

**Comment by moorcroftlad** [comment]
I forgot to mention, my form has various sections that show and hide.  Basically when you complete a section and hit next, I have the following code

    function areaIsValid(area) {
        area.validator('validate');
        return !area.data('bs.validator').hasErrors() && !area.data('bs.validator').isIncomplete();
    }

So when you click next within a section, this code is ran:

    var area = $(this);
    if (areaIsValid(area)) {
        showNextArea(area);
    }

**Comment by moorcroftlad** [comment]
I've played around with it, it's not to do with the section validation, because I've removed this and still am getting the issue
