### ISSUE TITLE
Unable to hook into form submission event

### ISSUE THREAD

**Issue by andreibondarev** [1000hz/bootstrap-validator#542]
The boostrap-validator is working but I'm unable to hook into the form submission event as suggested at the bottom of this page: http://1000hz.github.io/bootstrap-validator/#validator-events

Gemfile:
```
source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap-validator'
```

HAML template:
```
= form_tag '//test.list-manage.com/subscribe/post?u=59382d0e4943187c&amp;id=277921', remote: true, method: :post, id: 'form', data: {'toggle': 'validator'}
```

But whenever I call `.validator()` on my #form either in the JS file on document ready or in the developer console, I get the following:
```
Uncaught TypeError: $(...).validator is not a function
    at <anonymous>:1:11
```

Any suggestions here? Must be something simple I'm overlooking. Thanks in advance!

**Comment by 1000hz** [comment]
Not sure what's going on in your setup, but it doesn't seem like an issue with the plugin itself. Sounds like the plugin isn't ever being loaded on the page. You might want to check that. You'd probably find better help asking this question on StackOverflow.
