### ISSUE TITLE
Any updates for recaptcha support?

### ISSUE THREAD

**Issue by c0fe** [1000hz/bootstrap-validator#543]
I wanted to check back to see if there is any updates for recaptcha support?

**Comment by 1000hz** [comment]
Nope, sorry. Still being blocked by async validators. No ETA.

**Comment by c0fe** [comment]
Is this something you think can be overcome or just DOA?

**Comment by c0fe** [comment]
Are you willing to provide additional details to this?

**Comment by 1000hz** [comment]
Actually now that I think about it more, I don't think you'd want to implement recaptcha support using async validators. You could probably accomplish it with a hidden field that you set the value of inside of a callback on recaptcha verification.

Here's an example of what I mean (using a stubbed-out version of recaptcha).
http://jsbin.com/dikacuqizu/edit?html,js,output

**Comment by c0fe** [comment]
What is the possible harm in implementing it with async validators?

```
var response = grecaptcha.getResponse();

if(response.length == 0)
    //reCaptcha not verified

else
    //reCaptch verified
```
**or**

```
function get_action(form) 
{
    var v = grecaptcha.getResponse();
    if(v.length == 0)
    {
        document.getElementById('captcha').innerHTML="You can't leave Captcha Code empty";
        return false;
    }
    else
    {
        document.getElementById('captcha').innerHTML="Captcha completed";
        return true; 
    }
}
```

Could be done this way

**Comment by 1000hz** [comment]
I don't think you want to make an API request to recaptcha every time you try to validate the form. You only need to do that once. For instance, if the user completed the captcha but left another field of your form blank, you wouldn't want to revalidate the captcha.Or for example, if recaptcha still used the old-style of verification where you have to type letters and numbers, you wouldn't want to make an API request automatically as they typed. You don't need that tight of an integration (that async validators would provide) for something like a captcha.

Async validators would be more useful for things which you want immediate feedback on, i.e. checking a server endpoint to see if a username is available. Or making a call to an API to see if a password is complex enough and isn't too commonly used.

**Comment by c0fe** [comment]
>  I don't think you want to make an API request to recaptcha every time you try to validate the form. You only need to do that once.


I am sorry but why not? What problem would it cause to have this? I was under the impression that calling an API call every time is the standard. At least I haven't seen any other application of it.

**Comment by 1000hz** [comment]
You might be rate limited on the number of times you make a request, for example. I'm not saying you couldn't do it using async validators, just that you don't need them to do what you wanna do.

Plus, they aren't implemented yet.

**Comment by c0fe** [comment]
But then how are the plugins you can find on CodeCanyon doing this? Any theories?

**Comment by 1000hz** [comment]
Not sure what you mean? By "async validators" I mean supporting returning a promise from a custom validator.

**Comment by c0fe** [comment]
Ok look at this one for example:

http://envato.jigowatt.co.uk/demos/codecanyon-ultimate-php-html5-ajax-contact-form-bootstrap/

If you attempt to submit the form without the captcha it spits back an error. There is no php in that front end file, it is html format, php back and has its own validator. Are you using a different method than they might be?

**Comment by 1000hz** [comment]
The captcha validation is only being handled on the server in that example. That's why you can submit the form without completing it.

Here's a complete example of reCAPTCHA working with this plugin.
http://jsbin.com/kirevujexa/edit?html,js,output

**Comment by c0fe** [comment]
Ok that's what I was looking for/hoping for. 

That being said, if I write up the PHP backend to actually send the information by email, would you be willing/able to help in making sure it works properly with your validation library?

Obviously, it would be public, free for anyone to use.
