### ISSUE TITLE
Regex problem

### ISSUE THREAD

**Issue by manuel-84** [1000hz/bootstrap-validator#544]
Why this RegEx `^([a-zA-Z\xC0-\uFFFF]{1,60}[ \-\']{0,1}){1,3}$`
used as `pattern` attribute is not working? Should be fine https://regex101.com/r/6bw6V7/1

> Pattern attribute value ^([a-zA-Z\xC0-\uFFFF]{1,60}[ \-\']{0,1}){1,3}$ is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /^([a-zA-Z\xC0-\uFFFF]{1,60}[ \-\']{0,1}){1,3}$/: Invalid escape

Update: noted that in debug `[ \-\']` becomes `[ -']`
If I use `^([a-zA-Z\xC0-\uFFFF]{1,60}[ \-\\']{0,1}){1,3}$` (double slash) it works

**Comment by 1000hz** [comment]
The pattern attribute assumes `^` and `$`, so you shouldn't include it. Also, I don't think you need to escape the `'` at all.
