### ISSUE TITLE
Inline Validation

### ISSUE THREAD

**Issue by c0fe** [1000hz/bootstrap-validator#548]
Have the project maintainers considered adding optional inline validation mechanism, such as an example here: http://contactform.x10host.com/

**Comment by 1000hz** [comment]
Unless I'm misunderstanding you, this is already how the plugin works.

**Comment by c0fe** [comment]
I meant adding an option for a checkmark or x mark to show up as part of the validation.

**Comment by 1000hz** [comment]
That's already supported. Look at the `feedback` option. Check the Twitter field in the example on http://1000hz.github.io/bootstrap-validator/

**Comment by c0fe** [comment]
I can't believe i overlooked it, thanks!
