### ISSUE TITLE
 PHP Backend

### ISSUE THREAD

**Issue by c0fe** [1000hz/bootstrap-validator#549]
So I have this PHP file from a previous contact form, I am not sure if it would work with this validation library and if not can someone advise me as to what needs to be changed in it to make it work. I have it here:

https://hastebin.com/ekesozuvuq.php

**Comment by 1000hz** [comment]
Hi! This plugin is for client-side validation only and is not influenced by your backend and server-side validations (which you will still need). Likewise, it also doesn't impose any requirements upon your server.

To enable the plugin, you only need to make sure your form template includes the proper markup. If you don't use the `data-toggle="validator"` attribute to activate the validator on your form you'll also need to call the plugin via the javascript API. Please consult the project documentation for more details. As this an issue tracker and not intended to be a support forum, please ask a question on StackOverflow if you need more instructional help.

**Comment by c0fe** [comment]
Is there a way to notify that the message was successfully sent then?

**Comment by 1000hz** [comment]
Not sure what you mean. If you're asking if there's a way to show the user a message that the form was submitted, the answer is yes, but it's outside of the scope of the plugin. You just need to add a submit handler to your form after you initialize the plugin and check if `event.isDefaultPrevented()`, then show your message however you need to. Check the **Conditionally handling the submit event** section of the docs.

**Comment by c0fe** [comment]
Is the message function built into the validation library or would I have to add another script to pop that message out?

**Comment by c0fe** [comment]
And do you by chance have a sample of a kickback?

**Comment by 1000hz** [comment]
No, it's not built into the validation library.

**Comment by c0fe** [comment]
If I write that code, would you be willing to merge it?

**Comment by 1000hz** [comment]
No, it's outside of the scope of what the plugin should be responsible for.
