### ISSUE TITLE
submit buttons for Sign In & Facebook Sign In

### ISSUE THREAD

**Issue by javierbertran** [1000hz/bootstrap-validator#550]
Hi, 

I have two submit buttons in the same web page one for my application Sign In and one for Facebook Sign In. I only want to perform validation for my application's submit button and not for Facebook Sign In submit button. Is it possible to validate one button and not validate another button?

Thanks beforehand,

Javier

**Comment by 1000hz** [comment]
Not sure about this, but I think you might want your facebook button to be `type="button"`, which would prevent it from being disabled by the validator.

**Comment by javierbertran** [comment]
Cina, 

That helped... workaround for anyone interested... for the Facebook button:

<button type="button" onclick="javascript:__doPostBack( ...

Thank you.
