### ISSUE TITLE
How to disable validation when I leave the page by clicking on the link?

### ISSUE THREAD

**Issue by XX** [1000hz/bootstrap-validator#552]
When I click on any link on the page (not a submit button), validation occurs and error is displayed before leaving this page. Additionaly, in the case when a link is located under a form, error message shift down this link and page leaving doesn't occurs. How to fix this?

**Comment by 1000hz** [comment]
Sounds like you want to disable the validation that happens on `focusout`. Do `$('#myForm').off('focusout.bs.validator')`, though be aware that the form will no longer let the user know if they skipped through an invalid field.

**Comment by terdelyi** [comment]
The correct call is `$('#myForm').validator().off('focusout.bs.validator')`.
