### ISSUE TITLE
Manually Trigger Error on Field.

### ISSUE THREAD

**Issue by TheDagger** [1000hz/bootstrap-validator#554]
Please refer to my stackoverflow post here, https://stackoverflow.com/questions/44359891/trigger-error-manually-on-a-field-with-1000hz-bootstrap-validator

In short, I need to display the error on a different field manually from the one that detected the error.  Is this possible?

**Comment by TheDagger** [comment]
Note that I can't use 'require' in this case since blank input is actually ok in my case just not where both are blank.  I am looking into a method right now of turning require on/off not sure if this is best way.

**Comment by 1000hz** [comment]
You can trigger validation on a field by calling `$field.trigger('input')` (or `change` or `focusout`).

In your case though, I wouldn't handle this with a custom validator. I would use input event handlers that toggle `.attr('required', hasValue)` whenever the required status should change.

Here's an example:
http://jsbin.com/ruxiwudime/edit?html,js,output
