### ISSUE TITLE
Validator is not validating selectized field

### ISSUE THREAD

**Issue by Minstel** [1000hz/bootstrap-validator#555]
Issue https://github.com/1000hz/bootstrap-validator/issues/193 is closed, so I'm creating this one. I'm using 0.11.9 version of validator, and it is not validating field, that uses [selectize](http://selectize.github.io/selectize.js/). Although it's stated in closed issue, that not visible fields should be validated starting from validator version 0.11.0.

**Comment by 1000hz** [comment]
Can you put together an example on JSBin? Here's a template: http://jsbin.com/vojebunope/1/edit?html,css,js,output
