### ISSUE TITLE
Button and Ajax/SSE

### ISSUE THREAD

**Issue by jonathanparentlevesque** [1000hz/bootstrap-validator#557]
I'm currently changing my `<button type="submit"` for `<button type=" button"` which allow me to use Ajax and server-sent events to partially refresh the page instead of reloading the whole page.

The problem is that those buttons are no longer disable on invalid fields. 

Would it be possible to add support some kind of custom attribute or something similar so I could indicate to the API to consider those Ajax buttons as it would with submit button?

Thank you

**Comment by 1000hz** [comment]
You should use `type="submit"` and call `event.preventDefault()` inside a `submit` event handler to prevent the page reload.
