### ISSUE TITLE
Remote validation data needs to be URI encoded before submission

### ISSUE THREAD

**Issue by jugglebird** [1000hz/bootstrap-validator#56]
We saw this with an email input that had a remote validation:
```
<input type="email" name="email" data-remote="/api/validate/user" data-remote-error="That email has already been taken">
```

If the user enters, 'user+1@example.com', that API service will receive a GET request with:
```
/api/validate/user?email=user+1@example.com
```

but should be sending:
```
/api/validate/user?email=user%2B1%40example.com
```

To fix the issue, you could either call encodeURIComponent on the key and value prior to joining them with the equals sign, or build up an object and let jQuery do the encoding (the approach that I took in the pull request).

**Comment by 1000hz** [comment]
Good catch! I'll push a fix and version the library.

**Comment by 1000hz** [comment]
Wait, did you mean to send a pull request? If so, I don't think it got submitted.

**Comment by jugglebird** [comment]
I was just a little slow on following up with the pull request.

Should all be there now.
