### ISSUE TITLE
Add more layout that contains input, validation only work for first layout input 

### ISSUE THREAD

**Issue by kilban13** [1000hz/bootstrap-validator#564]
I have a form where there is add more button for adding new layout with same input of the first layout.
Now problem is,
              <form class="" action="" method="post" data-toggle="validator" 
                           role="form" ng-controller="PLCDetails" >

data-toogle="validator" working for first portion, but not working other portion( click add more button generate new layout with input )
*** add more layout is done by angular 1.5.6
+++++++++++++++++++++++++++++++++++++++++
What i have done reinitialize the $('form').attr('data-toggle','validator') in add new event of angular but it is not working..

**Comment by 1000hz** [comment]
You need to use the `$().validator('update')` method if the set of fields that need to be validated changes. See the docs for more info.
