### ISSUE TITLE
textarea    is not in this validation

### ISSUE THREAD

**Issue by MsThink** [1000hz/bootstrap-validator#566]
<textarea  class="form-control" required data-match="/[@#\$%\^&\*]+/g"></textarea>

Please add    textarea

Thanks

**Comment by 1000hz** [comment]
Textareas are supported. You are not using the `data-match` validator correctly. Please see the docs. You want the `pattern` validator, but HTML5 doesn't support that natively for textareas, so you'll need to use a custom validator. See #349 for an example.

**Comment by 1000hz** [comment]
It looks like the example is broken because it's based on an old version of the validator. Here's an updated example:

http://jsbin.com/tohiyewigu/edit?html,js,output

**Comment by MsThink** [comment]
resolved   
  
Thank you very much
