### ISSUE TITLE
Is it possible to use POST method with data-remote

### ISSUE THREAD

**Issue by simonclifton** [1000hz/bootstrap-validator#567]
Is it possible to override the GET request when performing AJAX remote validation queries rather than the default GET?

**Comment by 1000hz** [comment]
Nope, sorry. This will be possible once I add support for async custom validators using promises, but I can't tell you when that's gonna come. I haven't had much time lately to work on the plugin, so it could be awhile. Your best bet in the meantime is to fork the project.

**Comment by simonclifton** [comment]
Many thanks for the fast response - any pointers to the code that currently handles the AJAX call?

**Comment by 1000hz** [comment]
Yup, you just need to change this method to `$.post`

https://github.com/1000hz/bootstrap-validator/blob/98654674893740666773ebfb62798a2611e1a7cc/js/validator.js#L218

**Comment by simonclifton** [comment]
Thank you Cina - very much appreciated and good luck with the next release.
Simon.
