### ISSUE TITLE
Not validate dynamic inputs

### ISSUE THREAD

**Issue by maxalmonte14** [1000hz/bootstrap-validator#578]
I'm creating dynamic input elements by press a button, I put the validation rules in these inputs (for example required rule) but the plugin ignores that rules.

This is my code, but not works:

```javascript
$('#add-account').click(function(e) {
$('#table-body').append(`
            <tr>
                <td>
                    <input class="form-control" name="identifiers_name[]" value="${account}" required/>
                    <input type="hidden" name="identifiers[]" value="${accountId}">
                </td>
                <td>
                    <input class="form-control" name="affectedAmount[]" value="${affectedAmount}" required/>
                </td>
                <td>
                    <input class="form-control" name="types[]" value="${type}" required/>
                </td>
                <td>
                    <button class="btn btn-sm btn-danger delete-button">
                        <i class="fa fa-times"></i>
                    </button>
                </td>
            </tr>
        `);
}
```

**Comment by emregan** [comment]
Have you tried the update method  $('myForm').validator('update') after you append the dynamic fields?

From the documentation:

By default, the validator will only validate fields that are present when the plugin is initialized. If your form has a dynamic set of fields, you will need to call $(...).validator('update') to inform the plugin that the set of fields to be validated has changed.

**Comment by 1000hz** [comment]
Yup, you need to use `.validator('update')`
