### ISSUE TITLE
issue with data-disable

### ISSUE THREAD

**Issue by githubedu** [1000hz/bootstrap-validator#58]
Hello

I'm trying to use the option data-disable to disble the submit button if there is any error on the form.

However all of these tries didn't work:
 <form data-toggle="validator" id="NewUserForm" role="form" data-disable="false">
 <form data-toggle="validator" id="NewUserForm" role="form" data-disable="true">
 <form data-toggle="validator" id="NewUserForm" role="form" data-disable>

Or if there is way to check if the form is validated during submit will help also
  $('#NewUserForm').submit(function(e) {

}

Could you help me? Thank you

**Comment by 1000hz** [comment]
I don't really understand the problem you're having. the `disable` option is true by default, so you shouldn't have to do anything to get the submit button to be disabled when the form is invalid.

As to your question about how you can tell if the form is invalid during submit, you can check if the submit event `isDefaultPrevented()`:
```javascript
$('#NewUserForm').submit(function(e) {
  if (e.isDefaultPrevented()) {
    console.log("#NewUserForm is invalid!")
  }
}
```

**Comment by dtseaman** [comment]
I have the same problem.  My "submit" button is not disabled.

I added data-disable="true" to the form element, and nothing happened.  I also tried adding it to the submit button and nothing happened...

Whether or not I add the data disable option, when I click my submit button, all my fields suddenly mark themselves as "valid" and my form submits.
It's a modal form...
```
<!-- Sign Up Modal -->
<div id="signUp" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal Content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Sign Up for {{SITE_NAME}}</h4>
      </div>
      <div class="modal-body">
        <form class="form-horizontal"  id="signUpForm" data-toggle="validator" role="form">
            <div class="form-group has-feedback">
                <label for="inputUsername" class="control-label col-xs-2">Username</label>
                <div class="col-xs-10">
                    <input  type="text" class="form-control" id="inputUsername" name="username" placeholder="Username" data-remote="/namequery" data-error="This name is either too short (min 5 char), or is already in use.">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            <div class="form-group has-feedback">               
                  <label for="inputEmail" class="control-label col-xs-2">Email</label>                  
                    <div  class="col-xs-10">                    
                      <input type="email" name="email"  class="form-control" id="inputEmail" placeholder="Email" data-error="That email address is invalid">
                      <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                      <div class="help-block with-errors"></div>
                    </div>  
            </div>
            <div class="form-group has-feedback">
                <label for="inputPassword" class="control-label col-xs-2">Password</label>
                <div class="col-xs-8">
                    <input type="password" name="password"  class="form-control" id="inputPassword" placeholder="Password" data-minlength="5">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            <div class="form-group has-feedback">
                <label for="samePassword" class="control-label col-xs-2">(Confirm)</label>
                <div class="col-xs-8">
                    <input type="password" name="samepassword"  data-match="#inputPassword" class="form-control" id="samePassword" placeholder="(confirm password)">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                    <div class="help-block with-errors"></div>
                </div>
            </div>        
      </div>
      <div class="modal-footer">
        <div class="form-group">
          <div class="btn-group" role="group" aria-label="...">
            <button  type="submit" class="btn btn-primary">Sumbit</button>
            <button type="reset"  class="btn btn-primary">Clear</button>
            <button type="button" class="btn btn-primary">Close</button>
          </div>
        </div>
        </form>
      </div>
    </div>    
  </div>
</div>
```

**Comment by 1000hz** [comment]
@dtseaman you haven't marked any of your fields as `required`, so they are valid when empty. Also, you don't need to use the `data-disable` attribute.

**Comment by dtseaman** [comment]
argggh ok.  thank you.  It works now.

**Comment by marietouT** [comment]
Hello i have same probleme, all my fields are required but my "submit" input is not disabled.

       <form data-toggle="validator" role="form" method="POST" id="post">
            <div class="form-group has-feedback">
                <label for="firstname">Prénom*</label>
                <input type="text" pattern="^[_A-z0-9]{3,}$" maxlength="40" id="firstname" class="form-control" required>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                <div class="help-block with-errors"></div>
            </div>
            <div class="form-group has-feedback">
                <label for="lastname">Nom*</label>
                <input type="text" id="lastname" pattern="^[_A-z0-9]{3,}$" maxlength="40" class="form-control" data-error="Veuillez insérer un nom valide" required/>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                <div class="help-block with-errors"></div>
            </div>
            <input id="submit" type="submit" value="Enregistrer">
        </form>

**Comment by 1000hz** [comment]
@marietouT you need to use a `<button type="submit">` instead of `<input type="submit">`

**Comment by marietouT** [comment]
it works now. thanks :+1:
