### ISSUE TITLE
Validate a field if it has a value in it / i.e. how to validate an option field

### ISSUE THREAD

**Issue by emregan** [1000hz/bootstrap-validator#584]
I have a field that is "optional".  I want to skip validation if the field is empty, however as soon as a value is input into it, I want it to validate.  What is the best approach for this?

I've created a custom validator, that uses the field attribute I created called "data-allowempty":

custom: {
     allowempty: function($el) {
          var allowEmpty = $el.data("allowempty");
          if (allowEmpty == "true" && $el.val() == "") { // If attribute is true and value is not empty
               // How do I validate this as "True"?
          }
     }
}

Here is my field:

`<input id="foo" name="foo" data-allowempty="true" min="0" max="10" step="1" type="number" required>`

I want this to only validate if someone puts a number in it.  Otherwise, don't validate it.

Is this the best approach? Or is there a better way?

Please let me know, thank you!

Erin

**Comment by emregan** [comment]
I found a simple solution that does not require custom validators, thanks to StackOverflow.

All you have to do is remove the **required** attribute and add a pattern attribute with the following regex:

pattern="^0[1-6]{1}(([0-9]{2}){4})|((\s[0-9]{2}){4})|((-[0-9]{2}){4}‌​)$"

So my field looks like this:

`<input id="foo" name="foo" min="0" max="10" step="1" type="number" pattern="^0[1-6]{1}(([0-9]{2}){4})|((\s[0-9]{2}){4})|((-[0-9]{2}){4}‌​)$">`

This attribute triggers the validation if there is a value that doesn't fit the pattern, while allowing an empty field.

**Comment by watsonnnnn** [comment]
I'm in this situation now. I don't want to validate when the value is empty. I do this follow your steps but it will validate successfully when i don't write any value in my input. So can u have any other idea?
