### ISSUE TITLE
How to validate dynamically created inputs?

### ISSUE THREAD

**Issue by kko123** [1000hz/bootstrap-validator#587]
http://jsbin.com/yeluvagasa/edit?html,js,output
Work only first input. All dynamically created inputs won't work.
How to validate it?

**Comment by 1000hz** [comment]
You need to call `$().validator('update')` to refresh the set of inputs that get validated. See the docs for more info.

**Comment by minexew** [comment]
Are there any plans for an automatic on-form-DOM-changed listener?

It would be nice for decoupling validation from existing form logic.
