### ISSUE TITLE
 Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by sourabhdevera18** [1000hz/bootstrap-validator#591]
I get an error when i try to revalidate field 

" Cannot read property 'apply' of undefined"
![screenshot_2017-09-26_16-00-03](https://user-images.githubusercontent.com/30370669/30855790-c8b46892-a2d3-11e7-9ebb-2b3a45cb96f1.png)

**Comment by 1000hz** [comment]
This is not the repository for the plugin you are using.
