### ISSUE TITLE
it couldn't work on javascript-rendered html dom. 

### ISSUE THREAD

**Issue by chenyahui** [1000hz/bootstrap-validator#599]
it couldn't work on javascript-rendered html dom. 
I write some code to test this problem, in [here](https://jsbin.com/dufejux/edit?html,output)

in addition， I also found that if js render html on load page, the bootstrap-validator could work. But if I generate html after loading page , like through clicking button, it couldn't work.
 
Is it a bug?
if not, how can I deal with it.

**Comment by 1000hz** [comment]
You have to call `.validator('update')` anytime you alter the set of form fields.
