### ISSUE TITLE
How can I handle the events? I did not understand it on docs.

### ISSUE THREAD

**Issue by fschuindt** [1000hz/bootstrap-validator#60]
I am trying to fire some stuff when a determined field got errors. So I have tried the Events as said here: http://1000hz.github.io/bootstrap-validator/#validator-events

Pretty much like this:

```javascript
$('#new_user').on('invalid.bs.validator', function () {
  console.log('invalid input!');
});
```

But actually nothing happens, what am I doing wrong?

Thank you.

Edit: '#new_user' is my form element.

**Comment by 1000hz** [comment]
Seems to be working?
http://jsbin.com/fotayelubo/2/edit

**Comment by fschuindt** [comment]
That's right. After spent some time trying to figure out what was wrong (btw thank you for the jsbin) I finally understand that it was something about the Ruby on Rails Turbolinks, that reloads the page by Ajax. So I came around the problem by doing something like this:

```javascript
var reloadValidator;
reloadValidator = function() {
  $('#new_user').validator();
  $('#new_user').on('invalid.bs.validator', function () {
    alert('invalid input!');
  });
};

$(document).on('page:change', reloadValidator);

```

In this way everything worked fine. Thank you for the help.
