### ISSUE TITLE
No CSS markup?

### ISSUE THREAD

**Issue by Shadowrs** [1000hz/bootstrap-validator#617]
In the demo a correct input field has a green border, and invalid is red. Anyone know why this doesn't happen for me? I assume this lib generates CSS because I don't see any in the src

Thanks

![](https://i.gyazo.com/a9b95b0deeb375a2d63666649a05df4f.png)

**Comment by holmes2136** [comment]
It would be more easier if you can provide a jsbin or jsfiddle

**Comment by Shadowrs** [comment]
I assumed there was default CSS but I don't think there was. Used another solution, thanks!
