### ISSUE TITLE
email validation process

### ISSUE THREAD

**Issue by sbatschelet** [1000hz/bootstrap-validator#62]
It would seem more constructive for the user experience if the validation of email address happened after the user moved to another field or attempted to submit form.  Perhaps a few second delay from the last input.  The way it is now user is getting an error before they are completed with input.  

example: from your demo if you enter in myname it will show error before you get a chance to put @. Perhaps a slight delay could avoid this?

**Comment by 1000hz** [comment]
There is already a configurable `delay` option.
