### ISSUE TITLE
Validating checkbox group

### ISSUE THREAD

**Issue by be4code** [1000hz/bootstrap-validator#63]
Is there any possibility to validate checkboxes group when at least one is required? When I try to add "required" to every checkbox then every checkbox is required instead of situation when one checked checkbox is enough.

**Comment by 1000hz** [comment]
You can add an event handler that removes the required attribute on all the other checkboxes once one is checked or something.

```js
$('#myForm .checkbox-group').on('change', 'input[type="checkbox"]', function (e) {
  var $group = $(this)
  var $checkbox = $(e.target)
  $group.not($checkbox).attr('required', !$checkbox.attr('checked'))
})
```

This isn't a feature I'd be adding into the plugin though.

**Comment by maximelebreton** [comment]
referenced issues:
https://github.com/1000hz/bootstrap-validator/issues/96
https://github.com/1000hz/bootstrap-validator/issues/201
