### ISSUE TITLE
Validate form which is expand

### ISSUE THREAD

**Issue by ArturGabrys** [1000hz/bootstrap-validator#65]
Hi, 
I have registration form with 3 sections.

1 section:
Basic information is always visible.

2 section:
additional information A - is collapse

3 section:
additional information B - is collapse

I have a problem because 1 section validate fine, but when I expand 2 or 3 section by using checkbox with data-toggle="collapse" required fields does not validate? Is it normal or I have some kind of error?

Thank you

**Comment by 1000hz** [comment]
Can you reproduce the problem on JSBin?

Here's a template to get you started.
http://jsbin.com/jalacucace/1/edit?html,css,js,output

**Comment by ArturGabrys** [comment]
Thank you. Here you have it:
http://jsbin.com/yacisufiyi/1/edit?html,output

**Comment by ArturGabrys** [comment]
Any idea?

**Comment by 1000hz** [comment]
I'll need to add a change to the plugin to only validate visible input elements.

**Comment by ArturGabrys** [comment]
That would be great :)

Is there any quick fix which I could use until v0.8.0 will be release?
