### ISSUE TITLE
does it works with tabbed forms?

### ISSUE THREAD

**Issue by rheligon** [1000hz/bootstrap-validator#66]
i would like to know how to validate tabbed forms, i have webpage with 2 tabbed forms and dont know how to validate them.
![ex1](https://cloud.githubusercontent.com/assets/2424928/6157720/d8735a4c-b215-11e4-88d5-72009e02c9af.png)

**Comment by 1000hz** [comment]
I'm not really sure how you've structured your page, but I would probably set up each tab as its own separate form that's validated individually.

**Comment by rheligon** [comment]
actually i have them all in the same form, following bootstrap tabbed forms tutorial in their page.
Would you recomend me to change it to a form per tab structure instead?.
I have sort of like this build for the forms:

<ul class="nav nav-tabs" id="emp-tab">
    <li class="active"><a href="#datos-tab" data-toggle="tab">blah <i class="fa"></i></a></li>
    <li><a href="#nomen-tab" data-toggle="tab">Nom <i class="fa"></i></a></li>
    <li><a href="#conc-tab" data-toggle="tab">Con <i class="fa"></i></a></li>
</ul>

<form id="ConfEmpForm" method="post" class="form-horizontal">
<div class="tab-content">
        <div class="tab-pane active" id="datos-tab">
            <div class="form-group">
                 <label></label>
                 <div><input></div>
            </div>
             .
             .
         </div>
</div>
<div class="tab-pane" id="nomen-tab">....</div>
<div class="tab-pane" id="conc-tab">...</div>
</form>

**Comment by rheligon** [comment]
i think i did made it work with my own build, thanks very much for the plugin btw its a nice work!

i've an other doubt, for a required field if you don't especify error msg, where does it get it from? since it still appears some kind of message telling you that field its needed

**Comment by 1000hz** [comment]
The browser supplies a default error message based on your locale.
