### ISSUE TITLE
How to know input is valid or not in script?

### ISSUE THREAD

**Issue by jesuskim16** [1000hz/bootstrap-validator#67]
![image](https://cloud.githubusercontent.com/assets/3094708/6182927/87040ca2-b390-11e4-85eb-598f4e099efb.png)

-----------------------------------------------
```javascript
$("#userName").validator().on('change', function (e) {
	  if (e.isDefaultPrevented()) {
	  } 
})
```
When $("#userName") is changing the value, How do we know whether it is valid or not?

e.isDefaultPrevented() always return false.

**Comment by aroolaart** [comment]
I'm having the same issue (#61).  Form is always invalid.

**Comment by n0peration** [comment]
just call `$("#userName").validity.valid`

my solution:
```javascript
if (e.isDefaultPrevented()) {
    var inputs = $(e.delegateTarget).children().find('input');
    var valid = true;
    $.each(inputs, function(key, val){
        if(!val.validity.valid){
            valid = false;
            return;
        }
    });
    if(valid){
        everything is fine ...
    }
} else {
    everything is fine ...
}
```

**Comment by 1000hz** [comment]
You can bind to the `valid.bs.validator` and `invalid.bs.validator` events on the form. The `e.isDefaultPrevented()` test is only applicable to the `submit` event.
