### ISSUE TITLE
Resetting form doesn't clear validation errors

### ISSUE THREAD

**Issue by th0th** [1000hz/bootstrap-validator#68]
I resetting form by:

    $("form#custom-form")[0].reset();

but validation errors from previous validation attempt doesn't disappear.

A method to reset the validation status would be awesome I guess.

**Comment by th0th** [comment]
I found a workaround, i am resetting form and validator separately. Like this:

    $("form#custom-form").validator("destroy");
    $("form#custom-form")[0].reset();

**Comment by vebinua** [comment]
hi @th0th , "destroy" will completely remove the form's validation so if you wanted to keep the validation in effect, you could perhaps try: 

$(".frm-create-user-admin").bootstrapValidator('resetForm', true); //for older version

$(form).data('formValidation').resetForm(); //for later version

**Comment by emmychen** [comment]
@vebinua Thanks.  resetForm() works!

**Comment by KarthikTv** [comment]
Hi ,
I'm using this   **v-0.9.0** version of Validator.js, 
When i use reset form i;m getting below error,

> Uncaught TypeError: Cannot read property 'resetForm' of undefined.
I used below code, 
` $('#frmNew').data('formValidation').resetForm();` 
Please correct me if i used wrongly

**Comment by fghawi** [comment]
I'm using 0.9.0 version but the method resetForm() is not found

I have this form:

`<form role="form" data-toggle="validator" method="post" name="loginForm" id="loginForm">
...
</form>`

which I init it's validator with:

 `$('#loginForm').validator(defaultValidatorCofig)`

but when I try to execute:

 `$('#loginForm').data('formValidation').resetForm();`  

I get undefined method

What am I doing wrong?

**Comment by KarthikTv** [comment]
@fghawi Please see the [issue 262](https://github.com/1000hz/bootstrap-validator/issues/262).

I got answer for the my question is [stackoverflow](http://stackoverflow.com/questions/35145339/1000hz-bootstrap-validator-resetform-validation-results/35156592#35156592) But, I didn't tried that solution. This may helps you

**Comment by fghawi** [comment]
Thanks @KarthikTv , this was helpful.
Actually reset form won't help me, because all I want is to clear errors of inputs with empty values, and keep errors of invalid input values.
I did that by:
`var arr = panel.find('.has-error');
$.each(arr, function(index, item){
	if ($(item).find('input').val()===''){
		$(item).removeClass('has-error');
		$(item).find('.help-block').empty();
        }
});`

**Comment by nelson6e65** [comment]
You may want to use 'validate' instead of 'destroy':

```js
$f = $("form#custom-form")[0];
$f[0].reset();
$f.validator('validate');
```
This 
> "Immediately validates the entire form."

Ref: http://1000hz.github.io/bootstrap-validator/#validator-methods

**Comment by AndTheGodsMadeLove** [comment]
var form = $('#form')[0];
$(form).removeClass('was-validated');
form.reset();

resets the form without showing validation-errors while validation is still workin'
