### ISSUE TITLE
Accessing one field's errors

### ISSUE THREAD

**Issue by th0th** [1000hz/bootstrap-validator#70]
Is it possible to access and modify errors related to a field? I am doing an ajax call and I want to set field's error according to the response.

**Comment by 1000hz** [comment]
Have you looked at the `remote` validator? From the docs:

> `data-remote="/path/to/remote/validator"` to make an AJAX request to determine if the field is valid or not. Be sure to give the input a name attribute, as the request will be sent to `/path/to/remote/validator?<name>=<value>`. The remote endpoint should return a `200 OK` if the field is valid, and a `4xx` otherwise.

This will automatically use the response error as the error message.

**Comment by th0th** [comment]
I checked `remote` validator. The API I am trying to deal doesn't support validating fields individually. Hence, I need to submit form by ajax and then handle multiple errors returned in response myself.

**Comment by 1000hz** [comment]
In that case, I guess you can access the errors directly on the `<input>` fields via `$.fn.data`:
```javascript
$('#myInput').data('bs.validator.errors')         // read
$('#myInput').data('bs.validator.errors', errors) // write

**Comment by BasoPRO** [comment]
Are you sure, that AJAX request will use the response error as the error message ?

**Comment by 1000hz** [comment]
@BasoPRO Currently, it's using the *status text*, though I'll probably change it to use the response text in the next version.

**Comment by BasoPRO** [comment]
Anyway, I found I can use data-remote-error tag in the input element to specify error text, in this case. But it would be nice to use custom text returned by API, e.g. suggested usernames instead of used one (as it'll be in my case).

**Comment by 1000hz** [comment]
You can set the status text from your server, it's just not as obvious as setting the response text.

Check https://github.com/1000hz/validator-remote-example

**Comment by BasoPRO** [comment]
My remote validator is constructed via PHP and I am not able to set status or response text... trying with

header ("HTTP/ 433 some text")
or 
header("some text", true, 433) 

not works :(

**Comment by senzpo** [comment]
Are you shure that http derver can change status text? I think that this text from specification: http://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html
