### ISSUE TITLE
How to validate Select element?

### ISSUE THREAD

**Issue by dlegendkiller** [1000hz/bootstrap-validator#71]
First of all, thank you for this contribution. It's been a great help in my development. However, I have encountered an issue that needs to be resolved.

I have a select element which has a default value that has an attribute data-hidden.

The select element returns the text if the user continued submitting the form. Is there a built-in function of this validator that caters select elements? Thanks!

**Comment by dlegendkiller** [comment]
Nevermind. Solved it. I never thought the solution could be this easy.

I set the value of the first option to an empty string. Thanks for reading anyway :)

**Comment by rudzikdawid** [comment]
If you use disabled atribute in first option element
You shoud add something like that:
```
jQuery('form[data-toggle="validator"] select').on('change', function(event) {
    event.preventDefault();
    jQuery(this).find('option[disabled]').remove();
});
```
Some of Blackberry phones has problem with validation of disabled option elements.
And we need to remove this disabled element after user choice.
