### ISSUE TITLE
Submit button is outside the form tag.

### ISSUE THREAD

**Issue by dlegendkiller** [1000hz/bootstrap-validator#74]
Hi. I am using a bootstrap modal and the footer has my button submit.

The form tag is inside the modal body. How do I assign other buttons to be the submit button even when they are outside the form tag? thanks! :+1:

**Comment by bugejakurt** [comment]
Hi,
Try adding the form attribute and the ID of the form.
http://stackoverflow.com/a/12567605/995369

**Comment by 1000hz** [comment]
@bugejakurt that's not going to make the button react to form changes, only triggering the validator when clicked.

@dlegendkiller there's no way to do this right now, but I can add support for using the method @bugejakurt described.
