### ISSUE TITLE
Disable form from Submission if data-remote is in action

### ISSUE THREAD

**Issue by keithzeng** [1000hz/bootstrap-validator#75]
I use data-remote="CheckName" to check the uniqueness of the username, however it takes roughly around 0.5 seconds to show "Conflict" message. That means if I type very fast in my "username" field, and hit enter immediately, the form is submitted. Is there anyway to block the form from submission while the data-remote is firing the ajax call?

**Comment by 1000hz** [comment]
Closing as dupe of #72
