### ISSUE TITLE
Button group (radio) issue

### ISSUE THREAD

**Issue by FishkaStudio** [1000hz/bootstrap-validator#77]
Hello, I have a problem using radio as group buttons, after checking radio its green, but If I press a submit button, it says that that is an error (please select an option).

Here's a code:

            <div class="form-group">
              <div class="col-sm-4 control-label">Vaše povolání:</div>
              <div class="col-sm-8">
                <div class="btn-group" data-toggle="buttons">
                  <label class="btn btn-default">
                    <input type="radio" autocomplete="off" data-error="Vyberte své povolání, prosím" name="student" required>Student
                  </label>
                  <label class="btn btn-default"> 
                    <input type="radio" autocomplete="off" data-error="Vyberte své povolání, prosím" name="nowork" required>Bez zaměstnání
                  </label>
                  <label class="btn btn-default">
                    <input type="radio" autocomplete="off" data-error="Vyberte své povolání, prosím" name="work" required> Zaměstnán
                  </label>                      
                  <label class="btn btn-default">
                    <input type="radio" autocomplete="off" data-error="Vyberte své povolání, prosím" name="business" required> Podnikatel
                  </label>                                
                </div>
                <div class="help-block with-errors"></div>
              </div>
            </div>

**Comment by 1000hz** [comment]
The radio buttons need to have the same `name` attribute to be considered part of the same group. You need to use the `value` attribute instead to specify the submitted value.
