### ISSUE TITLE
Button onclick - form not valid but submit

### ISSUE THREAD

**Issue by ArturGabrys** [1000hz/bootstrap-validator#78]
Hi,
I have problem with one form, first of all even if the form is not valid (one of the required fields is empty) the button doesn't have lighter color, second if I click button the validator will show error but let the button to submit.

The button have onclick action and the form uses Ajax. Is this common error or I should check something?

Thanks.

**Comment by ArturGabrys** [comment]
No one can help? I really need to figure it out I use your Validator in my project and It works great in every other form at website, just have problem with this one specific case. I really don't want to change whole project just because one form.

**Comment by 1000hz** [comment]
It sounds like maybe your button either doesn't have `type="submit"` or it's not inside of your form element. Additionally, you should change the ajax submit from being triggered by the button's onClick to the form's onSubmit. You should also check if the submit event `.isDefaultPrevented()` before you send the ajax request.

It's hard to know for sure without looking at your code though.

**Comment by ArturGabrys** [comment]
Button have ```type="submit"``` and it's inside form.
I had modified code a little bit and now a have regular submit button and form with:
```
<form id="myForm" action="javascript: void(0);" onsubmit="xajax_saveForm(xajax.getFormValues('myForm'));" method="post"> 
```

But no luck. How can I add ```.isDefaultPrevented()``` to this?
