### ISSUE TITLE
setDefaults?

### ISSUE THREAD

**Issue by davidrenne** [1000hz/bootstrap-validator#80]
Cant seem to find this method?

setDefaults

http://stackoverflow.com/questions/18754020/bootstrap-3-with-jquery-validation-plugin

All over the web this is referenced but I cannot find a version of the code that has this occurrence.

Any ideas?

Maybe that is a different open source project?

How do I Add custom CSS to show an alert-danger?

            $.validator.setDefaults({
                highlight: function(element) {
                    console.log($(element));
                    $(element).closest('.form-group').addClass('has-error').addClass('alert').addClass('alert-danger');
                },
                unhighlight: function(element) {
                    console.log($(element));
                    $(element).closest('.form-group').removeClass('has-error').removeClass('alert').removeClass('alert-danger');
                }
            });

You would think that if this supported bootstrap you would use standard classes?  Confused.

**Comment by 1000hz** [comment]
That's a different plugin. See here: http://jqueryvalidation.org/

**Comment by davidrenne** [comment]
Any help on possibly setting custom "standard bootstrap classes" to the messages using your project?

**Comment by davidrenne** [comment]
Still confused why you dont add the danger classes as well as show the elements if they are hidden.

Basically I tried setting something like this:

```
<div class="help-block with-errors alert alert-danger">
```
But the blank div shows the red box when there is no error.

So I need to know how to configure JS events with your plugin to inject a standard bootstrap class when an error is found during validation.

**Comment by 1000hz** [comment]
You don't need to add the alert classes to the help-block. This plugin will add a `has-error` class to the `.form-group` when an input is invalid, which how Bootstrap handles form states.

See http://getbootstrap.com/css/#forms-control-validation

**Comment by 1000hz** [comment]
I guess this plugin's docs could be made more clear to point out that having a `form-group` class on the parent container of your inputs is required.

**Comment by davidrenne** [comment]
I have everything working fine after playing with it and putting in form-group without reading the docs.

The problem with the has-error class in my case is that the div floats over a dark background and not a white background.

So setting the alert-danger is my one route I need to take.

Should I just fork the project and swap out that class for my needs?  Seems like I should be able to override the CSS class like http://jqueryvalidation.org/ does.  

OK you are right, it is standard, but we need some control over which class is added or removed I guess in my case
