### ISSUE TITLE
Fields in the same form-group

### ISSUE THREAD

**Issue by bokkie** [1000hz/bootstrap-validator#83]
When I have multiple fields in the same form-group class, and just one of the two needs validation, both fields are highlighted as an error when just one is not filled in correct.
An example of someone else's issue on jsfiddle: http://jsfiddle.net/o7Lrw54e/

**Comment by olziinaa** [comment]
+1

**Comment by haleksandre** [comment]
This isn't a issue from this validator.  How Bootstrap change the look of the input is by adding 'has-success', 'has-warning' and 'has-error' to the parent div 'form-group'.

For more info see here http://getbootstrap.com/css/#forms-control-validation

With that being said you can easily change your HTML div's order to make this work
See https://jsfiddle.net/o7Lrw54e/5/ for your updated example.

**Comment by 1000hz** [comment]
@haleksandre is right. There should only be one form element in a `.form-group`.
