### ISSUE TITLE
Don't validate hidden inputs

### ISSUE THREAD

**Issue by goog62** [1000hz/bootstrap-validator#84]
The error indicators work properly while editing the form, but after clicking the (disabled) submit button, they disappear:

http://jsbin.com/moyojafuvu/1/edit?html,css,output

Can someone tell me what I'm doing wrong?

Thanks!

**Comment by 1000hz** [comment]
I think the hidden fields in the `.form-group` are causing the validator to thing there's no error, so it's clearing them.

I should probably exclude validation on those.

**Comment by goog62** [comment]
Thanks, Cina!

I was hoping to use your validator for a project that's due shortly. I'd
fix it myself, but I'm not a JavaScript developer. I'd be happy to pay to
have it fixed if you or someone you know would be willing to do it.

I'd also be happy to donate to keep this project going, because I love its
declarative design. So let me know how I can help.

Thanks again,

Steve Kramer

**Comment by 1000hz** [comment]
Just pushed v0.7.3 of the plugin. It was a simple fix. Let me know if works out for you.

**Comment by goog62** [comment]
Hi Cina,

I tested it on jsbin, but it doesn't seem to work. Maybe I'm doing
something wrong. Does it work for you?

Thanks,

Steve

**Comment by 1000hz** [comment]
I hadn't pushed the new version up to the docs page, where the JSBin is pulling the script from. I just updated it and the JSBin is working for me.

**Comment by goog62** [comment]
Cina, it works!

Thanks for your quick response,

Steve
