### ISSUE TITLE
Check if option in Select2 is selected

### ISSUE THREAD

**Issue by anne-sophie-balestra** [1000hz/bootstrap-validator#86]
Hello, 

I am trying to check if my select2 has an option selected. Right now it has a placeholder and nothing is selected, when I click on it and go to the next input without selecting anything, Bootstrap Validator says that my field is ok when it is required.

Below is the code I have for my select2.

```HTML
<form id="form" method="post" role="form" data-toggle="validator"> 
        <div class="form-group">
            <label class="control-label" for="operation">Opération :</label>
            <select name="operation" id="operation" data-error="Choose an operation" required class="form-control select2">
                <option></option>
                <option id="1">Operation 1</option>
                <option id="2">Operation 2</option>
            </select>
            <div class="help-block with-errors"></div>
        </div>
...
```
```javascript
$(document).ready(function() {
        $("#operation").select2({
            placeholder: "Choose an operation..."
        });
});
```

I have noticed that my select2 becomes green when I go through it and select nothing but it shows the error and turns my select2 red when I try to validate my form.

My select2 works fine and the Bootstrap validator works fine on my other fields.

Did someone else run into the same issue ? 

Thanks for your help

Anne-Sophie

**Comment by 1000hz** [comment]
Seems to work when I try to reproduce it on JSBin.
http://jsbin.com/kugafenoku/1/edit?html,js,output

**Comment by anne-sophie-balestra** [comment]
Thanks for the answer, I see that my error is not shown on your jsbin...
That's not a real problem I guess since my form is still validated correctly, i just have my select2 fields (or just labels actually) turning green when i click on it, select nothing and go to another input...

**Comment by 1000hz** [comment]
What version of this plugin are you using? Try upgrading to v0.8.0 and see if the problem still persists.

**Comment by estasenred** [comment]
I have the same problem and I have last version. In JSBin don't work validator with select2, If I click submit button and no option is selected no error is shown

**Comment by 1000hz** [comment]
Well, I guess this broke as a result of the fix for #65, which doesn't run validators on invisible form inputs. Since select2 hides the native select input and replaces it with an artificial one, the validators never run.

I'll need to think about if there's any way I support select2. I might need to add support for a special data attribute on inputs like `data-validate="true"` that overrides any other assumed behavior.

**Comment by wasiqaftab** [comment]
HI any respond on this issue. i am having the same issue with select2 it even dont highlight the if its correct or wrong

**Comment by arandilopez** [comment]
yep me too. Validation doesn0t work with select2

**Comment by 1000hz** [comment]
I don't know what to tell you guys other than it works whenever I try to use it:

http://jsbin.com/supofasuxi/edit?html,output

If the select element isn't visible (it's set to `display: none`) the validator won't try to validate it. This is most likely what's causing problems, so you can tell the validator to validate hidden elements by changing the selector it uses. Add this to your JS before you initialize the validator on your element:

```js
$.fn.validator.Constructor.INPUT_SELECTOR = ':input:not([type="submit"], button):enabled'
$('#myForm').validator()
```

**Comment by arandilopez** [comment]
@1000hz yeah that works... maybe an option to enable this behavior will rock
