### ISSUE TITLE
How to: Requiring at least one field

### ISSUE THREAD

**Issue by izzio84** [1000hz/bootstrap-validator#87]
Hi, 
the form might have multiple fields with the same validator rules but at least one of them is required.
For example any "forgot password" form where you can  choose between username or password
Thanks!
Mauro

**Comment by 1000hz** [comment]
You could write a custom validator in v0.8.0 to do this.

Something like:
```js
$('#myForm').validator({
  custom: {
    minchecked: function ($el) {
      var min = $el.data('minchecked')
      var $checkboxes = $el.closest('form').find('input[name=' + $el.attr('name') + ']')

      return $('input[name=' + $checkboxes.has(':checked').length >= min
    }
  },
  errors: {
    minchecked: 'Please check more boxes'
  }
})
```

**Comment by j0nes2k** [comment]
For future reference, here is a working version of the code above provided by @1000hz :

    $('#myform').validator({
        custom: {
            minchecked: function ($el) {
              var min = $el.data('minchecked');
              var $checkboxes = $el.closest('form').find('input[name=' + $el.attr('name') + ']');
              return $('input[name=' + $checkboxes[0].name).has(':checked').length >= min;
            }
          },
          errors: {
            minchecked: 'Please check more boxes'
          }
    });
