### ISSUE TITLE
Cannot reliably change label visibility when form is valid

### ISSUE THREAD

**Issue by 3zero2** [1000hz/bootstrap-validator#95]
A have a hidden label with id="Working" that I want to set to visible when the form is valid, so that the user is given an indication that the data is being uploaded.
```js
$('form').validator().on('submit', function (e) {	 
  if (e.isDefaultPrevented()) {
    // handle the invalid form...
  } else {
    $("#Working").show();
    // everything looks good!
  }
})
```
The above code does not work reliably all the time. It seems to work when the form is invalid, fixed and submitted, but not when submitted properly the first time.

Any pointers please?

**Comment by 1000hz** [comment]
Can you try to reproduce it on JSBin?

Here's a template to get you started
http://jsbin.com/xevehonopo/3/edit

**Comment by 3zero2** [comment]
I am having a hard time reproducing this using a simple form on JSBin or even on my machine for that matter. Will have to dig deeper about this. Might be an incompatibility between one of the various scripts I'm using.

I might have to re-create my current form step by step in order to ascertain where the current behaviour is being reproduced.

Will be back with further details.

**Comment by 3zero2** [comment]
I have created a new form and I can reproduce the issue. Zipped file here contains the relevant code: https://app.box.com/s/zydvuj3s35sxalr7zfh1il82m1257m7z

Here the **uploading** text does not always appear when the form is validated properly and hence submitted.

**Comment by 1000hz** [comment]
Shows up for me...
 
![image](https://cloud.githubusercontent.com/assets/1395018/6819312/2c9746c8-d28d-11e4-94ab-f345d1f40e66.png)

It seems like there's no issue with the plugin here so I'm gonna close this issue. Someone on StackOverflow will probably be able to help you further. Good luck!
