### ISSUE TITLE
Not working with Safari Version 8.0.2 (10600.2.5)

### ISSUE THREAD

**Issue by nihalsharma** [1000hz/bootstrap-validator#99]
Hi,

I am using the validator plugin and it works perfectly fine with Chrome but there seems to be some issue with Safari. The build is Version 8.0.2 (10600.2.5). Is there anything which I might be missing? It does not work at all with my Safari. 

Thanks

**Comment by 1000hz** [comment]
Seems to be working for me when I visit the [docs page](http://1000hz.github.io/bootstrap-validator).

**Comment by nihalsharma** [comment]
I know, it should work. I thought I might be missing something, so posted. Anyways, I would be trying to resolve this on my own. 

Thanks

**Comment by 1000hz** [comment]
Does the docs page work for you in Safari?
